Feature/pagination component
Open-Study-College/osc pull request #1134
Opened 2023-06-13 12:26 UTC by mattwendzina

Closes #171 

## 📝 Description

Adds Pagination component to OSC-UI library

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Adds a Pagination component

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-06-14 09:06 UTC, stevenbister commented
Oh something else I just noticed, Chromatic has failed. Looks like the progress component is missing from the package-lock file?
<img width="1489" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/6d097bcf-e83a-4529-837a-03cb0b08a961">
Might just need to push that up

2023-06-14 09:24 UTC, stevenbister requested changes
Looks good! Left a couple of questions and I think the styling needs some tweaks but nothing major :)

2023-06-14 09:24 UTC, stevenbister commented on packages/osc-ui/src/components/Pagination/Pagination.spec.tsx
Do you think it's worth including a test for the `onPaginate` prop?

2023-06-14 09:24 UTC, stevenbister commented on packages/osc-ui/src/components/Pagination/Pagination.tsx
> +            <span>
Do we need all of these `span`s? I think this would be okay
`<span> You've viewed {numberLoaded} of {total} {itemTypeDescription}</span>`

2023-06-14 09:24 UTC, stevenbister commented on packages/osc-ui/src/components/Pagination/pagination.scss
> +    &__button {
I think this button looks like it needs more work to match the design (too much letter spacing, font weight too heavy for example)

Si and I discussed consolidating the buttons styles when the component was built so rather than trying to create a specific button element here we should just use the existing ones (tertiary variant might be a better fit than secondary 🤔) Appreciate the design doesn't show that.

2023-06-14 09:24 UTC, stevenbister commented on packages/osc-ui/src/components/Pagination/pagination.scss
Missing a few styles I think, from looking at the design:

<img width="331" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/d58ddd4b-7dd8-4557-b426-1fbaf95b268c">
<img width="316" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/931c4000-da59-4715-8eeb-ca5dee392239">

The font weight is too heavy and we need to include some spacing between the elements

2023-06-16 10:13 UTC, mattwendzina commented on packages/osc-ui/src/components/Pagination/pagination.scss
> +    &__button {
Secondary and tertiary both have uniform border and font colours, so either way it seemed like I'd have to change the font or border colour, unless I'm missing something? Couldn't see a way to change text to lower case in the component which is why I added this in here, again maybe there is a way that I'm missing? 😅 
Tbh, didn't notice the font weight difference. I think it's marginal, but I can see it now you mention it. I was going with the lightest that we had in the system - `fw-reg`, so would you recommend just creating a lighter variety?

2023-06-16 10:31 UTC, mattwendzina commented on packages/osc-ui/src/components/Pagination/pagination.scss
Ah yeah that's my bad on the spacing. It actually was there before lol, so I don't know what I did to remove it 😅 but that's fixed. Sorted out the font-weights too.

2023-06-16 14:34 UTC, mattwendzina commented on packages/osc-ui/src/components/Pagination/pagination.scss
> +    &__button {
Scrap the above comment lol. Si and I chatted about it and now understand what you meant - ie just use one of our designs rather than their design in Figma! Done - using the `Tertiary` button.

2023-06-19 10:20 UTC, stevenbister reviewed
Looks really good mate, only thought I've had how are we handling changing the colour of the progress bar within the component? It looks like the progress is abstracted away as an internal component so AFAICT there's no way to pass props through to it right now? Perhaps just needs a `colorVariant` prop here as well?

2023-06-19 12:01 UTC, mattwendzina commented
> Looks really good mate, only thought I've had how are we handling changing the colour of the progress bar within the component? It looks like the progress is abstracted away as an internal component so AFAICT there's no way to pass props through to it right now? Perhaps just needs a `colorVariant` prop here as well?

Ah yeah, good shout! Added ✅

2023-06-19 14:23 UTC, stevenbister approved these changes
🚀

2023-06-21 16:08 UTC, merged