Feature/add infinite hits to instantsearch
Open-Study-College/osc pull request #1136
Opened 2023-06-13 12:39 UTC by mattwendzina

Closes #1135 

## 📝 Description

Integrates the <InfiniteHits> component into the Search page and adds the Pagination component.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

Currently there is no pagination

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

We are integrating the `useInfiniteHits` hook rather than the `usePagination` hook because we want to load results cumulatively rather than one a page by page basis. This requires integrating the <Hit> component into the <InfiniteHits> component and this effectively replaces the <Hits> component which has been removed.

2023-06-14 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/InfiniteHits.tsx
> +                    className="o-grid o-grid__col--12 o-container o-container--4xs"
I think this looks too wide comparing it to the design
<img width="396" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/7f8688aa-f4e7-43bc-b779-4f5f8f23064e">
<img width="344" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/d2c48652-29a4-47f8-8a28-b8e921c2c0d6">

I think rather than trying to control it with the grid and a container in this case you might be better off flexing it and setting a max width. This gets you pretty close
```tsx
<div className="o-flex o-flex--center o-grid__col--12">
    <OSCPagination
        itemTypeDescription="courses"
        total={results?.nbHits}
        numberLoaded={hits.length}
        onPaginate={onPaginateHandler}
        isLoading={isLoading}
    />
</div>
```

2023-06-14 09:49 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +            padding-inline: $space-7xl;
Not sure if I'm looking in the wrong place but I don't think this is doing anything?

2023-06-14 09:53 UTC, stevenbister commented
Oh also you might want to add the `build:ecommerce` label to this to build the preview link 😎

2023-06-16 14:30 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +            padding-inline: $space-7xl;
This was being used but is no longer needed, so it's gone!

2023-06-16 14:32 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/InfiniteHits.tsx
> +                    className="o-grid o-grid__col--12 o-container o-container--4xs"
Had a chat with Si on this. We ended up adding two more container sizes - `--xs5` and `--xs6`. So this is now using `--xs6`, which is a tiny bit wider than the design, but it means we keep the 'You've viewed...' text all on one line when we're into the 100's of courses.

2023-06-16 14:32 UTC, mattwendzina commented
> Hey man, pretty cool that! Couple of comments around styling hopefully nothing too major.
> 
> Only other comment I have is the component looks a bit too close to the top and bottom especially on desktop
> 
> <img alt="image" width="954" src="https://user-images.githubusercontent.com/23461173/245751431-a4550da9-5e96-4fb9-a473-e34715365d75.png"> <img alt="image" width="739" src="https://user-images.githubusercontent.com/23461173/245751482-e9dc5a38-04d8-4971-9954-ccbb316bd76b.png">

Ah yeah, good spot. Added some more spacing 👍

2023-06-19 10:28 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/InfiniteHits.tsx
> +                    className="o-grid o-grid__col--12 o-container o-container--4xs"
Ahh nice yeah that makes sense! You might need to take the padding utility off now though :S I would maybe look at adding the `o-container--flush` class just to trim off the container's padding as well

![image](https://github.com/Open-Study-College/osc/assets/23461173/956d1d80-e58a-429f-bfbc-653cb0edaa0a)

Just on this, I would take the `o-grid` class off here too. You don't really need it here and the `gap` that comes with it is adding some extra space between each item which is adding to the margin

2023-06-19 10:33 UTC, stevenbister requested changes
Looks good! Couple of little comments but should be gtg once those are sorted 👍

2023-06-19 10:33 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +        padding: 0;
Rather than adding padding and gap here I would take off the `o-grid` and `u-p` utility classes you have on the component

2023-06-19 12:13 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +        padding: 0;
Updated

2023-06-19 12:14 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/InfiniteHits.tsx
> +                    className="o-grid o-grid__col--12 o-container o-container--4xs"
Updated 👍

2023-06-19 14:29 UTC, stevenbister approved these changes
🚢

2023-06-22 08:59 UTC, merged