Feature/admin user create
Open-Study-College/osc pull request #1162
Opened 2023-06-15 14:48 UTC by hall2521

- Closes #887 
- Closes #886  
- Closes #885 

## 📝 Description

Gives an admin the ability to create a user using:

- name
- email 
- organisation
- role
- extra permissions

## ⛳️ Current behavior (updates)

## 🚀 New behavior

Admin now can create another internal user and can get a list of permissions to select extra permissions for the user

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2023-06-16 10:39 UTC, Tom-Pearce requested changes

2023-06-16 10:39 UTC, Tom-Pearce commented on packages/osc-api-auth/src/utils/account.ts
> +        }
We probably want to validate this earlier as at this point the user has already been created and it's a bit awkward to handle the UX if you then throw an error for the data.

Same way you've validated the user role early on.

2023-06-16 10:39 UTC, Tom-Pearce commented on packages/osc-api-auth/src/utils/account.ts
> +    });
Can we change this to cater for multiple role selections please? E.g. Learner services will probably have both user administrative roles as well as learner service roles. We as dev's will probably have a range of roles too.

It'll either be a series of checkboxes or a multiselect on the front end

2023-06-19 13:51 UTC, Tom-Pearce approved these changes
LGTM 🚀

2023-06-19 13:51 UTC, Tom-Pearce commented on packages/osc-api-auth/src/utils/account.ts
> +    // Check for existing user, all enpx primails must be unique
Can you fix this comment - just looks like you started typing an npx command with editor focused

2023-06-19 13:55 UTC, hall2521 commented on packages/osc-api-auth/src/utils/account.ts
> +    // Check for existing user, all enpx primails must be unique
yup. sorted

2023-06-23 10:33 UTC, merged