Feature/details grid
Open-Study-College/osc pull request #1187
Opened 2023-06-23 11:39 UTC by stevenbister

- Closes #1174 
- Closes #1175 
- Closes: #1176 
- Closes: #1177 

## 📝 Description

Adds the details grid component to Sanity/ecommerce. This is a simple two column grid of cards that becomes an accordion on small devices.

https://github.com/Open-Study-College/osc/assets/23461173/8a00471d-b272-4f32-a9df-6b1db1f8a187

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

- Adds `detailsGrid` schema to Sanity
- Adds `<DetailsGridModule>` component to ecommerce
- Adds tests for `<DetailsGridModule>`

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2023-07-06 12:08 UTC, hi-im-si requested changes
Overall Looks good - very minor feedback and 1 question

2023-07-06 12:08 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/Card.tsx
> +export interface BlogCardProps extends Omit<CardProps, 'variant'>, HTMLAttributes<HTMLDivElement> {
so what would be the reason for omitting the 'varant' here?

2023-07-06 14:18 UTC, stevenbister commented on packages/osc-ui/src/components/Card/Card.tsx
> +export interface BlogCardProps extends Omit<CardProps, 'variant'>, HTMLAttributes<HTMLDivElement> {
Because we've already got a `variant` prop in this component that as the values `'featured' | 'media-object'` it conflicts with the new `variant` prop in the extended `CardProps` which has `'primary' | 'secondary'`. So we're just removing them here and relying on this component's `variant` prop instead.

2023-07-06 14:20 UTC, stevenbister commented on packages/osc-ecommerce/app/components/DetailsGrid/DetailsGrid.tsx
> +                    className="o-grid__col--12 o-grid__col--6@tab"
Don't need it :) `o-grid__col` doesn't get generated in the main stylesheet

https://github.com/Open-Study-College/osc/assets/23461173/a73c06dd-7e61-4cc8-bb5c-f1480c436f56

2023-07-07 08:04 UTC, hi-im-si commented on packages/osc-ecommerce/app/components/DetailsGrid/DetailsGrid.tsx
> +                    className="o-grid__col--12 o-grid__col--6@tab"
Ahhh i guess i can get a bit pedantic when it comes to the rules of BEM'ing :D Always define the element before you start to modify it ;)

2023-07-07 08:04 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/Card.tsx
> +export interface BlogCardProps extends Omit<CardProps, 'variant'>, HTMLAttributes<HTMLDivElement> {
Thanks for explaining @stevenbister - good to understand these things :)

2023-07-07 08:06 UTC, hi-im-si commented on packages/osc-ecommerce/app/components/DetailsGrid/DetailsGrid.tsx
> +                    className="o-grid__col--12 o-grid__col--6@tab"
i do actually think this needs to be adressed at some point. I think its as simple as adding:

```
// By default always show 12 columns from mobile upwards
    &__col {
        grid-column: auto / span $grid-columns;
    }
```

means we can get rid of the `o-grid__col--12`

2023-07-07 13:11 UTC, stevenbister commented on packages/osc-ecommerce/app/components/DetailsGrid/DetailsGrid.tsx
> +                    className="o-grid__col--12 o-grid__col--6@tab"
> Ahhh i guess i can get a bit pedantic when it comes to the rules of BEM'ing :D Always define the element before you start to modify it ;)

Aha fair enough 😄 I've pushed an update.

Yeah I agree probs worth doing -- I'll open an issue for it

2023-07-07 13:42 UTC, hi-im-si approved these changes

2023-07-07 13:45 UTC, merged