Feature/add new cards to search route
Open-Study-College/osc pull request #1205
Opened 2023-06-26 15:49 UTC by mattwendzina

Closes #1150 
Closes #1151 
Closes #1152 
Closes #1153 
Closes #1154 

## 📝 Description

This adds Cards for the the newly created post_types - Other and Blog. I've refactored the Cards out of the `Hit` component and into their own folder to make things a little cleaner. There are also a few adjustments to the BlogCard in OSCEcommerce in order to cater for the usage in the Search page. 

## ⛳️ Current behavior (updates)

All Hits use the Course Card. The Result type refinement list is empty. 

## 🚀 New behavior

The Hits now use the appropriate card dependent upon the post_type - ie, blog, course, other. 

The Result type refinement list now allows you to filter the the post_type. I have only updated one Shopify Product with the `post_type` course so you will only see one populated against `Courses`. This will need to be updated for all of the shopify products.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-06-28 09:25 UTC, stevenbister requested changes
Looks good man, left a couple of comments. 

Noticed a few things on the front end but this might be related to the algolia app we're using
<img width="1252" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/2b0ec6ff-cff6-4d70-989d-458d29ca8e00">
Only 1 course? 👀  


<img width="1150" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/37f67ff8-321d-4b03-a10d-e27c5df3de11">
Courses disappears from the refinement list when I search

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchBlogCard.tsx
> +            button_variant: 'quinary',
Is there a reason for snake casing these rather than camel casing? Feels a bit inconsistent with everything else?

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchBlogCard.tsx
> +            button_variant: 'quinary',
Also would it be possible to change the variant on list view? Probably to secondary I reckon 🤔

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchCourseCard.tsx
> +                view === 'listview' ? 'c-card--bordered' : 'c-card--shadow'
Rather than adding the classes here like this can you use the props? `hasShadow` / `hasBorder`?

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchOtherCard.tsx
> +                hit.post_type === 'Other' && view === 'gridview' ? 'secondary' : 'quinary',
Secondary might be a good one to use on list view as well, the quinary one only really works on the "featured" card variant I think

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +        // TODO - Add in once courses have been updated with post_type
Guessing this is for a later piece of work?

2023-06-28 09:25 UTC, stevenbister commented on packages/osc-ecommerce/app/types/sanity.ts
> +    width?: number;
Making the height and width optional here is causing ts to error on this type
```
Interface 'imageModule<T>' incorrectly extends interface 'SanityImage<T>'.
  Types of property 'height' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
```
Is there a reason for it to be optional? Ideally we should always be getting the height/width for the image

2023-07-04 11:08 UTC, mattwendzina commented
> Looks good man, left a couple of comments.
> 
> Noticed a few things on the front end but this might be related to the algolia app we're using <img alt="image" width="1252" src="https://user-images.githubusercontent.com/23461173/249417635-2b0ec6ff-cff6-4d70-989d-458d29ca8e00.png"> Only 1 course? 👀
> 
> <img alt="image" width="1150" src="https://user-images.githubusercontent.com/23461173/249417768-37f67ff8-321d-4b03-a10d-e27c5df3de11.png"> Courses disappears from the refinement list when I search

There's only one course because this is a post_type that will need adding to all the courses, I just added to one to test it works. This is why is disappears when you start searching. If you were to type 'course replacement cover' you would see it stay as this is the only product that currently has that post_type property.

2023-07-04 11:32 UTC, mattwendzina commented
I've added the change to the content in, as per comment in SanityAlgolia PR. I've actually removed it from Blog cards and only applied to Other cards. Looking at the design, the Blog card doesn't appear to have content, just the title, and it looks a bit crowded adding it, especially on Grid view.

2023-07-04 11:35 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchCourseCard.tsx
> +                view === 'listview' ? 'c-card--bordered' : 'c-card--shadow'
Done

2023-07-04 11:36 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Components/Cards/InstantSearchOtherCard.tsx
> +                hit.post_type === 'Other' && view === 'gridview' ? 'secondary' : 'quinary',
Agreed. Updated.

2023-07-04 11:42 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +        // TODO - Add in once courses have been updated with post_type
Yes, created a ticket here:
https://github.com/Open-Study-College/osc/issues/1238

2023-07-04 11:49 UTC, mattwendzina commented on packages/osc-ecommerce/app/types/sanity.ts
> +    width?: number;
Hmm, maybe there was but can't see why now. I've removed and made sure it hasn't affected any other changes and it seems to be fine.

2023-07-05 12:36 UTC, stevenbister approved these changes
> I've added the change to the content in, as per comment in SanityAlgolia PR. I've actually removed it from Blog cards and only applied to Other cards. Looking at the design, the Blog card doesn't appear to have content, just the title, and it looks a bit crowded adding it, especially on Grid view.

Yeah that makes sense, agreed it probs doesn't need to be there on blog cards :)

LGTM!

2023-07-11 09:05 UTC, merged