Feature/sen requirements
Open-Study-College/osc pull request #1206
Opened 2023-06-27 10:39 UTC by Tom-Pearce

- Closes #884 

## 📝 Description

Adds Prisma model for SEN data.
Adds Prisma model for `UserAdditional` data - currently includes bio and SEN additional
Adds queries and mutations to manage SEN data for a student/user

## ⛳️ Current behavior (updates) 

None

## 🚀 New behavior

### Queries
- `studentSen` pulls a list of student SEN presets (e.g. ADHD, Dyslexia, etc)

### Mutations
- `saveSen` save SEN presets for a student or the logged in user
- `saveSenAdditional` save SEN additional data against `UserAdditional` - free text 512 char limit

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2023-06-27 14:07 UTC, hall2521 commented on prisma/schema.prisma
> +  shorthand   String?   @db.VarChar(32)
Short hand here is optional but required in schema file. Is this intentional?

2023-06-27 14:08 UTC, hall2521 commented on prisma/schema.prisma
> +  userId        Int       @unique
will this be unique? Is a user only allowed 1 entry into this model?

2023-06-27 14:19 UTC, Tom-Pearce commented on prisma/schema.prisma
> +  userId        Int       @unique
Yes, it's one record per user for storing additional data like their bio

2023-06-27 14:19 UTC, Tom-Pearce commented on prisma/schema.prisma
> +  shorthand   String?   @db.VarChar(32)
Will fix, think this was just a codeium autocomplete I missed

2023-06-30 12:01 UTC, hall2521 approved these changes
LGTM

2023-07-21 13:37 UTC, hi-im-si requested changes
As per Tom's continued work, moving this away from 'approved'

2023-07-21 14:55 UTC, hall2521 requested changes

2023-07-21 14:55 UTC, hall2521 commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +            country: response.properties.country,
Are all these fields required or will they sometimes be null?

2023-07-21 14:55 UTC, hall2521 commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> + * @param id - The ID of the user whose contact info is being updated.
fix this to externalId

2023-07-21 14:55 UTC, hall2521 commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +                country: input.country,
can a users email not be updated at this stage?

2023-07-21 14:55 UTC, hall2521 commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +            : new Error('Uknown API error: crm.syncSen');
minor spelling mistake Unknown

2023-07-21 14:55 UTC, hall2521 commented on prisma/schema.prisma
> +  createdBy Int
might be worth linking this to user id as well

2023-07-21 15:02 UTC, Tom-Pearce commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +            country: response.properties.country,
They may be empty but the field will always be there from Hubspot, so we're always going to want to return it regardless

2023-07-21 15:03 UTC, Tom-Pearce commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +                country: input.country,
Correct, as we probably want to perform some extra auth around it as it will be changing their login details

2023-07-21 15:03 UTC, Tom-Pearce commented on packages/osc-api-crm/src/integrations/hubspot/index.ts
> +            : new Error('Uknown API error: crm.syncSen');
Good spot, I also typo that word somehow

2023-07-21 15:04 UTC, Tom-Pearce commented on prisma/schema.prisma
> +  createdBy Int
It already is?

2023-07-21 15:25 UTC, hall2521 approved these changes
LGTM

2023-07-26 13:07 UTC, hi-im-si approved these changes

2023-07-26 13:07 UTC, merged