Feature/add collections page
Open-Study-College/osc pull request #1207
Opened 2023-06-29 11:05 UTC by mattwendzina

Closes #985 
Closes #986 
Closes #991  
Closes #992  
 
## 📝 Description

Creates the Collections $slug route page. 

## ⛳️ Current behavior (updates)

Currently the route is just a shell.

## 🚀 New behavior

- Adds a custom Hero that combines data from Sanity and Shopify
- Adds a description property to Collections page in Sanity
- Adds a SelectBar component 
- Updates the Configuration component so we can refine the search results
- Refactors the Search component into its own file so that it is reusable
- Updates the /search route to use the resuable Search component, as well as tweaks for Configuration and Refinement data

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

It's possible that the CSS isn't pulling through for the 'Select Your Course' in the SelectBar, sometimes it appears to not be centralised and not in bold. Not sure why this is happening. Also creating an opacity on the Select has a knock on effect of making the dropdown itself use this opacity setting.

2023-06-30 14:20 UTC, stevenbister requested changes
Looks really good mate! Left a few comments mostly around css. 

Only other thought I had, think it's worth increasing the vertical padding inside the select trigger here:
<img width="475" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/8c8ee632-8fa8-437a-b57b-2c65c4c3ebef">
So that you click on most (if not all) of the box, rather than having to select the text specifically?

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +            flex: 2;
These flex values feel a bit magic. And they expand quite far on really large screens (not sure how good that screenshot will be)

<img width="1175" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/1566da71-c9e9-4ec7-b467-c0cf194d1f23">

Is there a reason you went for this over using the grid utility classes to position and size things?

I'd also recommend putting a container class on the div with `c-select-bar`

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +        @include mq($mq-tab) {
Can you move this up to the top above line 11? Just to group it with the `c-select-bar` styles, might get missed down here if we ever add/refactor anything

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +            <Row
Rather than adding this `Row` and `Content` could you reuse the `ContentModule` component we're using in the `Modules` loop?
You've missed a couple of props on the `Content` component I think that would potentially get passed from the CMS (buttons, alignment etc.)

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
>                  <PreviewSuspense fallback={<PageContent {...page} />}>
Might need to update the `{...page}` here as well?

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-studio/schemas/documents/collection.tsx
> +            type: 'module.content',
I wonder rather than giving them the full contend module we just use `'body'` instead (just the text box). I imagine this part being fairly controlled and not really changing much page to page, would save us having to handle all of the other components that come bundled in 🤔

2023-06-30 14:20 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +                        <SelectPrimitive.Value>{placeholder}</SelectPrimitive.Value>
Is there a reason we've changed this? The Radix docs look like they suggest the previous way?
<img width="798" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/b9292a3a-759f-4766-9196-cfcbe3e2860e">

2023-07-04 13:28 UTC, mattwendzina commented
> Looks really good mate! Left a few comments mostly around css.
> 
> Only other thought I had, think it's worth increasing the vertical padding inside the select trigger here: <img alt="image" width="475" src="https://user-images.githubusercontent.com/23461173/250112868-8c8ee632-8fa8-437a-b57b-2c65c4c3ebef.png"> So that you click on most (if not all) of the box, rather than having to select the text specifically?

Good idea! Done ✅

2023-07-04 13:32 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Hero/Hero.tsx
> +                    <Slide {...slide} initialSlide={true} key={slide?._key} children={children} />
Yup, done 👍

2023-07-04 13:35 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                    name={'view_select'}
LOL. Maybe if you kept a money jar that would help 😂

2023-07-04 13:51 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                        <SelectItem key={index} value={item.handle} to={item.handle}>
Yeah good point... So originally I tried wrapping the SelectItem in a <Link/> component and this didn't work. 
I've tried doing this direct on the component itself using an <a/> tag with a conditional but this also doesn't work. 
What about if we still wrapped it in the Link but still used the navigate function? This adds the semantics in at least. Or is this a ridiculous suggestion? 😅 
I'll reach out to the Radix team to see if they have any suggestions.

2023-07-04 14:07 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +            opacity: 0.8;
Sorted

2023-07-04 14:11 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +            padding-right: $space-3xl;
Done 👍

2023-07-04 14:26 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +            flex: 2;
Ahhh, old habits! Always forget when best time to use Grid is... Much easier though lol. Updated. 
Don't see the need for a container on the `c-select-bar` div though?

2023-07-04 14:28 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +        @include mq($mq-tab) {
It's no longer needed now it's using grid so it's been removed instead = )

2023-07-04 17:08 UTC, mattwendzina commented on packages/osc-studio/schemas/documents/collection.tsx
> +            type: 'module.content',
Yeah good shout. Updated.

2023-07-04 17:41 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +            <Row
I've updated to the `ContentModule` and added the horizontalAlignment and button props in. I've also removed rowSettings as now just using the body (as per below comment).

2023-07-04 17:45 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +                        <SelectPrimitive.Value>{placeholder}</SelectPrimitive.Value>
Yeah, so this one flummoxed me and I faffed about for a while trying to figure out what was going on. Basically the way it was set up (passing in as prop) just stopped working... I found that passing it through to the component was the only way to fix this. See image below:
 
<img width="819" alt="Screenshot 2023-07-04 at 18 43 00" src="https://github.com/Open-Study-College/osc/assets/36510083/890e6da2-13a0-46a7-8c6a-37dfd6d7b313">

2023-07-05 12:46 UTC, stevenbister commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                        <SelectItem key={index} value={item.handle} to={item.handle}>
Cool, I wouldn't spend too long on it. I don't think `select` or `option` takes an `a` tag but I guess this is technically a `button` 🤔 But that might not be valid html either... I was thinking use something else like a popover maybe 🤔 But appreciate that would probably require some effort to match it to the design.
Happy to leave as is.

2023-07-05 12:55 UTC, stevenbister commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +        @include mq($mq-tab) {
Noice

2023-07-05 13:05 UTC, stevenbister requested changes
Looking good man, couple of extra little things I've noticed, and I think a comment from the previous review might have been missed. Nearly there thought!

2023-07-05 13:05 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Hero/Hero.tsx
> +                        children={children}
Sorry, missed this one last time, you can change this to match the one below?

2023-07-05 13:05 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const stylesheets = getComponentStyles(data.page);
Is there a reason for using the `DynamicLinksFunction` over the regular `LinksFunction`? 
We don't really need to use it on route pages unless you're expecting the styles to be dynamic? But AFAICT we need the styles as a minimum for the `Search` component, so could we use the same `LinksFunction` that we have on the `/search` route?

2023-07-07 07:39 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                        <SelectItem key={index} value={item.handle} to={item.handle}>
Yeah, so I reached out to Radix and they suggested that we could try the DropDownMenu instead, but weren't 100% sure whether this would support a/link tags.  But yeah either way this would probably take a bit of work to get it to match the design. Could create a ticket to come back and optimise this at a future date?

2023-07-07 07:50 UTC, stevenbister commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                        <SelectItem key={index} value={item.handle} to={item.handle}>
Yeah I think leave it as is for now, don't want to take up too much time here. Yeah I think a ticket or even a discussion actually might be a good idea

2023-07-07 07:51 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
>                  <PreviewSuspense fallback={<PageContent {...page} />}>
This is update now.

2023-07-07 07:55 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Hero/Hero.tsx
> +                        children={children}
Updated

2023-07-07 08:15 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const stylesheets = getComponentStyles(data.page);
I thought this was basically needed for pages where Marketing can pull in modules - as in it's a way to ensure that styles for the page data gets correctly pulled in?

2023-07-07 08:40 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const stylesheets = getComponentStyles(data.page);
Yeah, so this already pulls through the styles from the modules in Sanity which is what the `getComponentStyles` is doing, you don't need to change that, from what it was. This is pushed through the `handle` and picked up by the `DynamicLinks` component in the root.

The other stylesheets you've added (e.g. `stylesheets.push({ rel: 'stylesheet', href: selectStyles });`) should ideally sit in the regular `LinksFunction` as they're required by the page and will load sooner.

Admittedly it probably doesn't matter but I think it's clearer to differentiate them 🤔

2023-07-07 09:30 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const stylesheets = getComponentStyles(data.page);
Ah! Yeah, that makes total sense = ) Updated 👍

2023-07-07 10:27 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/select-bar.scss
> +            flex: 2;
Ah right. Got it. Added the o-container and o-container--flush, but also needed to add an outer container to house the background colour for when it extends beyond the container itself.

2023-07-07 10:28 UTC, mattwendzina commented
As per @hi-im-si suggestion - I've added `select` and `trigger` to the postcss-purgecss safelist.

2023-07-07 10:38 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/SelectBar/SelectBar.tsx
> +                        <SelectItem key={index} value={item.handle} to={item.handle}>
Cool. I've started a discussion here: 
https://github.com/Open-Study-College/osc/discussions/1250 

I've also raised/linked a task which can be found here:
https://github.com/Open-Study-College/osc/issues/1249

2023-07-07 14:05 UTC, merged