Feature/unit testing api
Open-Study-College/osc pull request #1210
Opened 2023-07-03 10:41 UTC by hall2521

Closes #1117 

## 📝 Description

Added unit testing to APIs

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Framework for unit testing APIs has been added.
Tests have been written for osc-api-auth & osc-api

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
2 commands added -
npm run test:unit - runs unit tests
npm run test:unit:ui - runs unit tests and shows results in the UI

2023-07-04 15:01 UTC, Tom-Pearce requested changes
Mostly LGTM, just question on some commented lines of code, and a questionable `return`.

Abstraction of input objects is a suggestion, but not a required change.

2023-07-05 09:24 UTC, Tom-Pearce approved these changes
LGTM

2023-07-06 07:39 UTC, stevenbister requested changes
Looks good mate! Left a couple of comments around package.json files which might impact the CI stuff but other than that good to go

2023-07-06 07:39 UTC, stevenbister commented on packages/osc-api-auth/package.json
> +    "test:unit": "vitest -c ./vitest.config.ts",
Rather than `test:unit` could we call this just `test`? Nx is currently setup to pick up the `test` command so when running on CI it might miss this one. 

I do like the explicitly of this though so maybe it can be something we update all of the other packages to in the future 🤔

2023-07-06 07:39 UTC, stevenbister commented on packages/osc-api-admin/package.json
Do we need to add the `test` script to these files? Looks like there's a couple that are missing it?

2023-07-06 07:39 UTC, stevenbister commented on packages/osc-api/package.json
> +    "test:unit": "vitest -c ./vitest.config.ts",
Similar to my other comment can we update the command?

2023-07-06 08:20 UTC, hall2521 commented on packages/osc-api-admin/package.json
yup i've added these in and added a simple test to all the different apis to show it working

2023-07-06 08:36 UTC, stevenbister approved these changes
LGTM!

2023-07-12 15:56 UTC, merged