Feature/store and read notifications
Open-Study-College/osc pull request #1244
Opened 2023-07-06 10:02 UTC by hall2521

Closes #1126 
Closes #1127 
Closes #1125 
Closes #1124  

## 📝 Description

Adds a notification system to the backend with the ability to store notifications as well as access notifications via status + type
## ⛳️ Current behavior (updates)

## 🚀 New behavior
2 new queries and 1 new mutation:
- getAllNotifications - allows you to get all your own users notifications. can filter on this list by status (Unread, Read, All)
- getAllNotificationsByType - allows you to get all your own users notifications, can filter on this list by type and status

- storeNotifications - create a new notification

## 💣 Is this a breaking change (Yes/No): Yes

Makes an update to the prisma schema so changes will need to implemented via npx prisma db push

## 📝 Additional Information

2023-07-07 13:16 UTC, Tom-Pearce requested changes

2023-07-07 13:16 UTC, Tom-Pearce commented on prisma/schema.prisma
> +  url       String
Thinking about the URL generation. If we hardcode it in the way we have it, then if we were to change the routing on the front end the URLs would then be wrong.

What do you think about storing the `url` as a template (e.g. `ah.osc.com/assignments/submissions/{subId} against the `notificationType` and then just storing the relevant ID here as `targetId` or something. Then on the front end they just find/replace the template to generate the final URL. This way the URL can be changed inline with any front end routing changes.

We may also need to consider the need for multiple `targetId` though. Let me know your thoughts on this?

2023-07-07 13:16 UTC, Tom-Pearce commented on prisma/schema.prisma
> +  type          String
Can we rename this to `title`?

2023-07-07 13:16 UTC, Tom-Pearce commented on packages/osc-api-settings/src/resolvers/resolver.ts
> +            return await notifications.storeNotification(input);
I think somewhere we may want to perform a check against the `userId` and their `systemPreferences` for the notification type - Or maybe more appropriately we should add a ToDo and a new issue for adding support for `notificationTypeSubscriptions` which we can then check against before creating the notification?

2023-07-12 09:59 UTC, Tom-Pearce requested changes
Want to keep the properties as camelCase and keep PascalCase for the model/type name

2023-07-12 09:59 UTC, Tom-Pearce commented on packages/osc-api-settings/src/schemas/schema.ts
> +        Type: NotificationType
Being pedantic but can we make the `T` lowercase in `Type` Guessing it's coming through from the prisma schema?

2023-07-12 10:39 UTC, hall2521 commented on packages/osc-api-settings/src/schemas/schema.ts
> +        Type: NotificationType
yup this comes from the prisma schema. it happens in a number of relations so may be worth tagging this as a separate issue?

2023-07-12 12:11 UTC, Tom-Pearce commented on packages/osc-api-settings/src/schemas/schema.ts
> +        Type: NotificationType
Sounds good to me we'll do that instead

2023-07-12 12:12 UTC, Tom-Pearce approved these changes
LGTM 🚀

2023-07-14 11:49 UTC, merged