Feature/setup page routes
Open-Study-College/osc pull request #1252
Opened 2023-07-07 13:41 UTC by jkellerman

Closes #1231
Closes #1232 
Closes #1233 
Closes #1234 
Closes #1235 
Closes #1236 

## 📝 Description

Setup page routes for osc-recruitment

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

N/A

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-07-10 14:32 UTC, stevenbister requested changes
Good work man! A few minor comments, mostly around eslint warnings -- which should hopefully be fixable by re-saving the files now Prettier is working in your editor 🤞

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/components/Module.tsx
> +import { V2_ServerRuntimeMetaDescriptor } from '@remix-run/server-runtime';
You okay to save this file again now that we've got your prettier working? This is throwing an eslint warning

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/queries/fragments/buildUrls.ts
> +        "slug": "/${PATHS.JOBS}/" + store.slug.current,
Can you take `store.` off this? so it should just be `slug.current` like this
```suggestion
        "slug": "/${PATHS.JOBS}/" + slug.current,
```

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/queries/fragments/childModules.ts
As we've taken a bunch of these components out it would be good housekeeping to remove the queries for them, both in this file and the fragments themselves (I'm not gonna comment on every single one, so don't forget to check them).

I'd recommend trying to get into the habit of only querying/using what you need as it helps keep the responses smaller (& the code a bit tidier).

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/root.tsx
> +import { LoaderFunction, json, type LinksFunction } from '@remix-run/node';
Another eslint warning here that I think Prettier should be able to solve, if not just change the import to 
```suggestion
import { LoaderFunction, json } from '@remix-run/node';
import type { LinksFunction } from '@remix-run/node';
```

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/routes/$slug.tsx
> +import { LoaderFunction, V2_MetaFunction, json } from '@remix-run/node';
Similar to previous comments, can you extract this into a type import?

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/routes/index.tsx
> +import { LoaderFunction, V2_MetaFunction, json } from '@remix-run/node';
See previous comments re eslint warnings

2023-07-10 14:32 UTC, stevenbister commented on packages/osc-recruitment/app/routes/jobs/$slug.tsx
> +import { LoaderFunction, V2_MetaFunction, json } from '@remix-run/node';
See previous comments re eslint warnings

2023-07-10 15:59 UTC, jkellerman commented on packages/osc-recruitment/app/components/Module.tsx
> +import { V2_ServerRuntimeMetaDescriptor } from '@remix-run/server-runtime';
Getting Module '"@remix-run/server-runtime"' has no exported member 'V2_ServerRuntimeMetaDescriptor'.ts(2305)

I tried saving and restarting ts server but no fix

2023-07-11 11:28 UTC, stevenbister approved these changes
LGTM!

2023-07-18 10:04 UTC, merged