Feature/assignment lists
Open-Study-College/osc pull request #1262
Opened 2023-07-12 15:25 UTC by hall2521

Closes #1068 
Closes #1069 
Closes #1077 
Closes #1061 
Closes #1060 
Closes #1062 
Closes #1059 
Closes #1123  

## 📝 Description

Added numerous lists for tutors and students to see a number of list views for assignments

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior
Queries: 
 - getAllUnmarkedAssignmentsTutor
 - Get all unmarked assignments for a tutor
 - getRecentlyMarkedAssignment
 - Student gets recently marked assignment
- getCountAllUnmarkedAssignmentsTutor
- Get a count of all unmarked assignments for a tutor
- getNextAssignmentDue
- get the next assignment that's due for a student
- getAllAssignmentsTutor
- get all assignments through all courses for a tutor
- getAllAssignmentsStudent
- gets all assignments through all courses for a student

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2023-07-14 11:14 UTC, Tom-Pearce requested changes
Queries are good, but could you just format them similar to the `getCount`. Mainly the schema I've flagged as probably needing tweaking

2023-07-14 11:14 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/schemas/schema.ts
> +        getAllAssignmentsStudent(id: Int!): [getAllAssignments]
Think we should keep methods like `get` to the query, and try and make the type itself as versatile as possible - Anywhere we talk about an assignment should _try_ to return the same type/data.

I think we want `Assignment` to be the assignment itself against he course.
`AssignmentSubmission` is obviously anything the student uploaded along with relevant identifiers (course ID/title, assignment ID/title etc).

For instance `getNextAssignmentDue`, `getAllAssignmentsTutor` and `getAllAssignmentsStudent` queries should all return the same data type `Assignment`. With the `getNext...` being a singular `Assignment` and the `getAll...` queries returning an array `[Assignment]` they're just filtered differently.

`getAllUnmarked..` `getRecentlyMarked` should both return an array of `[AssignmentSubmission]` again just being filtered differently one for marked one for unmarked.

Also probably want to flag `count` as `@shareable` otherwise as soon as we add it to another schema it'll complain it doesn't know where to go to resolve.

We also want to keep the type single and PascalCase and if it's plural, it's just an array - same as how it works with Prisma models.

2023-07-14 11:43 UTC, hall2521 commented on packages/osc-api-assignments/src/server/rules.ts
> +);
I think it's worth looking at the rules/permissions as a whole. have some global ones set that get reused is good, but I think just having the rules in 1 place in general is good practice.

2023-07-17 15:51 UTC, hall2521 commented on packages/osc-api-assignments/src/utils/assignments.ts
> +    >`Select DISTINCT asub.*, c.title as courseTitle, u.firstName as studentFirstName, u.lastName as studentLastName, a.title as assignmentTitle from \`courses.tutors\` ct RIGHT JOIN \`courses.studen
Response was oldest first by default but able to switch it around in preferences

2023-07-17 15:52 UTC, hall2521 commented on packages/osc-api-assignments/src/utils/assignments.ts
> +LIMIT 1`;
Most assignments are done in order but no set due date. certain courses take a more structured timetable though

2023-07-31 15:30 UTC, Tom-Pearce requested changes

2023-08-09 10:31 UTC, Tom-Pearce approved these changes
LGTM 🚀

2023-08-14 13:41 UTC, merged