Feature/setup design tokens
Open-Study-College/osc pull request #1263
Opened 2023-07-12 15:28 UTC by jkellerman

Closes #1229 

## 📝 Description

Adds fonts, colours and logo for recruitment website

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

N/A

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

N/A

## 📝 Additional Information

2023-07-17 10:13 UTC, stevenbister requested changes
Good work! Couple of comments but otherwise looks pretty solid

2023-07-17 10:13 UTC, stevenbister commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomSecondary = '#1c4a50';
Do we need to include the other secondary colours?
<img width="1348" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/3851857f-f836-44cc-a5e4-cd181c385baf">

2023-07-17 10:13 UTC, stevenbister commented on packages/osc-ui/src/components/Logo/Logo.tsx
> +    logoId?: 'logo' | 'bloom-logo';
I think `id` rather than `logoId` would work better here 🤔 You're already on the `<Logo>` component so feels unnecessary/repetative to include the word "logo" in the prop.

What do you think?

2023-07-17 10:13 UTC, stevenbister commented on packages/osc-ui/src/components/Logo/Logo.stories.tsx
> +Bloom.args = {};
I would add the `logoId` as a default prop here otherwise this story is the same as the primary one

2023-07-17 10:13 UTC, stevenbister commented on packages/osc-ui/src/styles/settings/_tokens.scss
> +        tertiary: hsl(42, 72%, 81%),
Did you manually add these? Not sure how these values would have been generated?

This file is generated by the `tokens:generate` command so will be replaced everytime it runs. If you want to include these colours here you'll need to add them to the `colors.js` file in `osc-design-tokens`

2023-07-17 14:16 UTC, jkellerman commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomSecondary = '#1c4a50';
Secondary colours have been added in commit [c208707](https://github.com/Open-Study-College/osc/pull/1263/commits/c208707fb6d638e10b18241b5f587cbf6d5f23c3)

2023-07-17 14:16 UTC, jkellerman commented on packages/osc-ui/src/components/Logo/Logo.tsx
> +    logoId?: 'logo' | 'bloom-logo';
Yup, agreed

2023-07-19 09:58 UTC, stevenbister requested changes
Nice man! One little minor comment but otherwise we're there :)

2023-07-19 09:58 UTC, stevenbister commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomOctonary = 'hsl(166, 39%, 65%)';
Can you update these values to include the deg format, just so they're consistent with the other values
e.g
```suggestion
const bloomOctonary = 'hsl(166deg 39% 65%)';
```

2023-07-19 10:14 UTC, stevenbister commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomTertiary = 'hsl(42, 72%, 81%)';
Not sure how I feel about how some of the colours are mapping across, for example in the testimonials PR I don't think that browney/gold colour looks that nice when used in the cards 🤔

2023-07-19 11:15 UTC, jkellerman commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomTertiary = 'hsl(42, 72%, 81%)';
The browney/gold colour and the red that is currently the background of one of the content blocks are not intentional. For example, the browney/gold colour is supposed to be white but for some reason sanity is mapping the colours incorrectly.

Also, we discussed in the brief with marketing that each section will probably need a different background colour instead of the whole page being yellow, meaning we need the theme colours for Bloom in sanity to select different colour backgrounds for each content block. I believe this is the best way to go about this because these content blocks are imported as modules (hope that makes sense, please correct me if I am wrong).

I'm planning on changing the colours of the site so it should look a lot different to what it does now, I was also going to do this in a separate PR, so maybe we should accept these changes and then change the colours in different PR, what do you think?

2023-07-20 07:46 UTC, stevenbister requested changes

2023-07-20 07:46 UTC, stevenbister commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomOctonary = 'hsl(166deg, 39%, 65%)';
Ah sorry one more! When using the "deg" syntax you don't need the commas. I _think_ they won't work correctly if you use commas as well as the "deg". You okay to remove them, and also re-run the `tokens:generate` command to test and update new scss file?

2023-07-20 07:47 UTC, stevenbister commented on packages/osc-design-tokens/tokens/colors.js
> +const bloomTertiary = 'hsl(42, 72%, 81%)';
Yeah that's all good! Let's tackle that once the colours in Sanity are sorted!

2023-07-21 07:37 UTC, stevenbister approved these changes

2023-07-24 10:41 UTC, merged