Fix/ecommerce header nav
Open-Study-College/osc pull request #1271
Opened 2023-07-14 10:49 UTC by jkellerman

Closes #

## 📝 Description

Fixed header for ecommerce site due to creation of new HeaderInner sub component

## ⛳️ Current behavior (updates)

![Screenshot 2023-07-14 at 11 35 22](https://github.com/Open-Study-College/osc/assets/89940123/c987e2aa-6712-4725-9aa6-e8554528b232)

## 🚀 New behavior

![Screenshot 2023-07-14 at 11 33 40](https://github.com/Open-Study-College/osc/assets/89940123/120967f5-b3fa-4b35-809b-4eaa0c252100)

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-07-17 10:31 UTC, stevenbister reviewed
Looks good! I do have a question which I've left against the file

2023-07-17 10:31 UTC, stevenbister commented on packages/osc-ui/src/components/Header/Header.tsx
> -        <div className="u-bg-color-primary">
I see you've passed it in as a class on the parent `<Header>`. Is there a reason for moving this out of here and putting it there?

2023-07-17 10:32 UTC, stevenbister commented
Oh also don't forget to include the `build:osc-ecommerce` label here as you'll want this branch to build a preview link and deploy when we merge

2023-07-17 16:35 UTC, jkellerman commented on packages/osc-ui/src/components/Header/Header.tsx
> -        <div className="u-bg-color-primary">
Yes, firstly, the ecommerce website uses tertiary for the background colour, recruitment uses primary, so the class needs to go on the component for flexibility. Also, the class needs to be on the Header component to prevent only the inner header having the styles (see below). 
![Screenshot 2023-07-17 at 17 26 25](https://github.com/Open-Study-College/osc/assets/89940123/25057f7a-1077-4aef-bfbf-cce6e5117647)

2023-07-19 10:00 UTC, stevenbister requested changes

2023-07-19 10:00 UTC, stevenbister commented on packages/osc-ui/src/components/Header/Header.tsx
> -        <div className="u-bg-color-primary">
Okay cool yeah that makes sense. In that case can we remove this `div`? Keeps the markup tidy

2023-07-20 07:44 UTC, stevenbister approved these changes
LGTM!

2023-07-26 15:56 UTC, merged