Feature/testimonial page
Open-Study-College/osc pull request #1275
Opened 2023-07-17 13:10 UTC by jkellerman

Closes #1235  

## 📝 Description

Set up schemas and types for testimonial cards for testimonials page

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

N/A

## 📝 Additional Information

2023-07-19 10:16 UTC, stevenbister commented on packages/osc-recruitment/app/components/Cards/Cards.tsx
Might be worth removing the `adaptiveHeight` prop on line 107 in here so the cards are all the same height? What do you think?

2023-07-19 11:19 UTC, jkellerman commented on packages/osc-recruitment/app/components/Cards/Cards.tsx
Agreed

2023-07-19 11:26 UTC, jkellerman commented on packages/osc-recruitment/app/components/Cards/TestimonialCard.tsx
> +                <CardImage isRounded>
I put this in as a placeholder. In the discussion with marketing, we talked about them taking control of all the content so pretty much all images and copy are placeholders, and i'm not sure what image they will be using here or if they will be using one at all.

Also, as discussed in design-tokens PR, the colour scheme isn't intentional, it is supposed to be white in the interim but sanity is giving back this colour. Haven't decided on what colour the background for the cards will be yet.

2023-07-19 13:42 UTC, jkellerman commented on packages/osc-recruitment/app/components/Cards/TestimonialCard.tsx
> +                <CardImage isRounded>
How it's looking with the latest commits.
<img width="1340" alt="Screenshot 2023-07-19 at 14 13 56" src="https://github.com/Open-Study-College/osc/assets/89940123/65913b2d-1c04-486a-9deb-b303f79a7296">
<img width="1294" alt="Screenshot 2023-07-19 at 14 14 37" src="https://github.com/Open-Study-College/osc/assets/89940123/10ec66a9-a4ea-4bbf-a7cc-5f33957ce6d4">

This is how they look depending on whether an image is selected in the CMS or not

2023-07-20 07:57 UTC, stevenbister commented on packages/osc-recruitment/app/components/Cards/TestimonialCard.tsx
> +                <CardImage className="not-rounded">
This class should match the BEMIT naming so should be `is-not-rounded`

2023-07-20 07:57 UTC, stevenbister commented on packages/osc-recruitment/app/components/Cards/TestimonialCard.tsx
> +                <CardImage isRounded>
Ahh okay so do you imagine they will likely use pictures of faces in there then? 🤔 If we're not sure perhaps it could be a question for marketing? Or maybe we add a control to Sanity to give them the option to use either rounded or non-rounded images?

2023-07-20 07:57 UTC, stevenbister requested changes

2023-07-20 07:57 UTC, stevenbister commented on packages/osc-ui/src/components/Card/card.scss
> +                // width: 120px;
Try not to leave commented out code like this. If we don't need it can you remove it?

2023-07-20 07:58 UTC, stevenbister commented on packages/osc-recruitment/app/components/Cards/TestimonialCard.tsx
> +                <CardImage isRounded>
Oh also just noticed. When I pull the branch down I don't have any padding above the image?

<img width="510" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/f908b7a6-8067-4e49-9020-5a5473b7aa9c">

2023-07-27 10:24 UTC, stevenbister approved these changes
LGTM

2023-07-27 12:41 UTC, merged