Feature/build autocomplete as sanity component
Open-Study-College/osc pull request #1277
Opened 2023-07-17 16:11 UTC by mattwendzina

Closes #1159 
Closes #1160

## 📝 Description

Enables CMS users to add a search module in Sanity and adds it to osc-ecommerce

## ⛳️ Current behavior (updates)

No way for CMS to add a Search Module

## 🚀 New behavior

- Search Module in Sanity with a customisable title, placeholder, background and input/text colours
- 

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2023-07-19 08:46 UTC, stevenbister requested changes
Looks good! Got a few comments/suggestions also getting some interesting behaviour with the url. I've added a recording for you below:

https://github.com/Open-Study-College/osc/assets/23461173/36d9ff60-fa06-49e6-b962-dfe74a265ff3

Navigating back changes the search params, which changes the number of results and then when you go all the way back to the home page it keeps you on the homepage but changes the url to /search/

2023-07-19 08:46 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/algolia.helpers.ts
Do you think these should sit in our `constants.ts` file or maybe the `types/algolia.ts`? These aren't really utility functions so feels like they shouldn't sit in here? What do you think?

2023-07-19 08:46 UTC, stevenbister commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'title',
I feel like this should either be a text input or named something other than title? Using the body type means all kinds of content can be added here so title feels a bit misleading when reading the code in the components in ecommerce.

2023-07-19 08:46 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
The button on line 287 doesn't do anything, should it point to the /search page?

2023-07-19 08:46 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const algoliaSearchModule = page.modules.some((module) => module._type === 'module.search');
Getting an error on the collections pages, I _think_ it's related to this line

<img width="1484" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/1b9e4c50-7799-4620-b201-3f8bf961b401">

```
TypeError: Cannot read properties of null (reading 'some')
    at loader5 (/Users/stevebister/SITES/osc/packages/osc-ecommerce/build/index.js:9632:88)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.callRouteLoaderRR (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at async callLoaderOrAction (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:3626:16)
    at async Promise.all (index 1)
    at async loadRouteData (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2954:19)
    at async queryImpl (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2735:20)
    at async Object.query (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2611:18)
    at async handleDocumentRequestRR (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:163:15)
    at async requestHandler (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:61:18)
```

2023-07-21 13:48 UTC, mattwendzina commented
> Looks good! Got a few comments/suggestions also getting some interesting behaviour with the url. I've added a recording for you below:
> 
>  Screen.Recording.2023-07-19.at.09.28.55.mov 
> Navigating back changes the search params, which changes the number of results and then when you go all the way back to the home page it keeps you on the homepage but changes the url to /search/

Now fixed by moving away from programmatic navigation to using anchor tags and the native form submission. The url does still change - pretty sure this is the url syncing from Algolia, but it doesn't add a step in the history so pressing back still takes you back to the previous page, so don't think this should be an issue..!

2023-07-21 14:23 UTC, mattwendzina commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'inputColor',
Ah yeah good point. I've added them to the "Content" group. Not sure what you mean by - "should maybe be the default?"

2023-07-21 14:28 UTC, mattwendzina commented on packages/osc-studio/schemas/objects/module/search.ts
> +                input: ColorPickerRestricted,
I thought it didn't make sense to give them so many colour choices for the text and textInput colour. I think ideally it would just be solid input colours but didn't want to faff about with creating another ColorPicker file so thought that at least restricted reduced the options. That said, having the option to have different greys is pretty important so think I'll just change it. I guess if they want a wild gradient for the text and input then they will at least have the option 😂

2023-07-21 14:35 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Components/SearchBox.tsx
> +import { useEffect } from 'react';
Sorted

2023-07-21 15:08 UTC, mattwendzina commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'title',
Yeah good point. Well ideally we need them to be able to adjust the colour and size so thought it was easiest just to use Content as it has the colour picker. Is there a type that allows just text and those kinds of adjustments?

2023-07-21 15:09 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
Updated 👍

2023-07-21 15:42 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/collections/$slug.tsx
> +    const algoliaSearchModule = page.modules.some((module) => module._type === 'module.search');
Ah good spot. I've just added optional chaining to all of these cases.

2023-07-24 07:41 UTC, stevenbister commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'inputColor',
If you look at any of the other modules (e.g. tabs.ts) there is a `groups` array and one of the items has a `default: true` property on it
![image](https://github.com/Open-Study-College/osc/assets/23461173/979a14e0-0c5d-4aa0-9ccf-53922e8a2711)

That makes Sanity open that group up rather than the `all fields` tab when an editor is editing the module

2023-07-24 07:56 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/algolia.helpers.ts
I don't seem to be getting an issue putting them into `constants`, and I can't see why that would be the case? What's the error you're getting? 

Tbf types probably isn't the best pace for them, but I do think `constants` is. In my mind that `utils` folder should only really be for holding functions, rather than data

2023-07-24 07:58 UTC, stevenbister commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'title',
Yeah the type is fine, I just think the name "title" isn't the clearest when reading the code as it can be more than just the title ya know?

2023-07-25 06:54 UTC, mattwendzina commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'inputColor',
Ah, nice. Done 👌

2023-07-26 07:06 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/algolia.helpers.ts
Now sorted this. As per discussion, I used the `typeof document` in that file. They have been set to null as we pull them through the loader but it's not happy if you don't deal with them on the client. 
I've also managed to move the searchClient outside of the components by setting up a getClient and config file to and pulling in the app id and api key through the root, similar to what you've set up with Sanity.

2023-07-26 07:06 UTC, mattwendzina commented on packages/osc-studio/schemas/objects/module/search.ts
> +            name: 'title',
Updated to 'Description' 👍

2023-07-26 07:07 UTC, mattwendzina commented
I've temporarily removed the Algolia Insights Plugin as it was causing and issue and isn't actually being used atm anyway. I've added a ticket to ensure this gets implemented when I do the insights work:
https://github.com/Open-Study-College/osc/issues/1336

2023-07-26 08:39 UTC, stevenbister requested changes
Looking good man! Couple of (hopefully minor) things. There is an issue with the search route on the deployed link however. I've left a comment a little further down about this

2023-07-26 08:39 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Autocomplete/AutocompleteInlineSearch.tsx
> +                <Content value={module.title} />
Think this need to be `module.description` now?

2023-07-26 08:39 UTC, stevenbister commented on packages/osc-ecommerce/app/queries/sanity/fragments/modules/search.ts
> +    title,
Think this needs to be updated to description now? To match the new schema name

2023-07-27 06:40 UTC, mattwendzina commented on packages/osc-ecommerce/app/root.tsx
> +        ALGOLIA_API_KEY_SEARCH: process.env.ALGOLIA_API_KEY_SEARCH,
Sorted

2023-07-27 06:56 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/search.tsx
> +            throw new Response('Not found', { status: 404 });
Ah yeah, looks like I'd forgotten to add the Collections env var! Updated 👍

2023-07-27 07:04 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Autocomplete/AutocompleteInlineSearch.tsx
> +                <Content value={module.title} />
Oops 😬 Good spot. Forgot to update the query too 😅  All sorted now and should be pulling the description through..!

2023-07-27 07:04 UTC, mattwendzina commented on packages/osc-ecommerce/app/queries/sanity/fragments/modules/search.ts
> +    title,
👍

2023-07-27 12:41 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/search.tsx
> +            throw new Response('Not found', { status: 404 });
Everything looks good man! I'm still getting a 404 on this page though :/
https://pr-1277-osc-ecommerce.fly.dev/search

2023-07-28 12:50 UTC, mattwendzina commented
Finally... this now appears to all be working in https://pr-1277-osc-ecomgitmerce.fly.dev 😅 

Turns out I had double curly brackets for the docker env vars, and the collections env var needed adding to the secrets.

2023-07-31 09:19 UTC, stevenbister approved these changes
LGTM! 🚢

2023-08-02 09:45 UTC, merged