Feature/download upload assignment
Open-Study-College/osc pull request #1285
Opened 2023-07-19 14:47 UTC by hall2521

Closes #1082 
Closes #1073 
Closes #1072 
Closes #1076 
 

## 📝 Description

Aws S3 Integration in AH
Provides presigned urls for download and upload
Provides endpoints for:
- markedAssignment
-uploadAssignment
- reviewAssignment

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

New Table - ReviewAssignmentSubmission to link an IV review to an assignment submission
Added endpoints -
- downloadUrl - gets a presigned download url for aws s3
- uploadUrl - gets a presigned upload url for aws s3

The following mutations to be requested after uploading relevant files to AWS
- reviewAssignment - submit an IV review of a marked assignment.
- markedAssignment - mark a student submitted assignment
- uploadAssignment - create an assignmentSubmission record and send out notifications

## 💣 Is this a breaking change (Yes/No): Yes

Modification to Prisma Schema
run npx prisma db push to apply changes

## 📝 Additional Information

2023-07-20 10:41 UTC, Tom-Pearce requested changes
Theres a few things to change here nothing major. Theres also a few console.logs dotted around that need removing.

We also at some point will want to cater for our legacy data which I don't particularly wont to migrate over to our new folder structure as it's going to be a nightmare. Probably, just going to fully reference the location and flag it as legacy so it will just be an if/else. But we'll add this as a to-do, and i'll flag it in the data migration task

2023-07-20 10:41 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/schemas/schema.ts
> +        markedAssignment(input: MarkAssignmentInput!): AssignmentSubmission
Can we rename this mutation to `markAssignment` keeps it more inline with present tense of the others

2023-07-20 10:41 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/schemas/schema.ts
> +    }
From what I can tell we're not using `studentId`, and it may be more prudent to get `courseId` ourselves from the `assignmentId`/`Assignment` instead of relying on the caller to pass the correct info.

2023-07-20 10:41 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/schemas/schema.ts
> +    }
Not using `assessmentId` or `fileName` 

Probably want to determine `courseId` ourselves here again based on the `submissionId`

2023-07-20 10:41 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/server/permissions.ts
> +        uploadAssignment: and(isAuthenticated, canUploadAssignment),
Probably going to want to extend this and make it a bit more specific to the user uploading vs who the upload is for to make sure they have perms for them. I.e.they are their tutor, but I think towards the end of the API work we'll probably want to fully review the permissions across the whole suite anyway

2023-07-20 15:26 UTC, hall2521 commented on packages/osc-api-assignments/src/utils/assignmentManagement.ts
> +    }
A user can have more than 1 role so this process needs to be thought about some more. I suggest we create an issue to resolve this logic as it may appear elsewhere as well

2023-08-09 10:40 UTC, Tom-Pearce approved these changes
Just a lingering `console.log`, but LGTM 🚀

2023-08-09 10:40 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/utils/s3.ts
>          console.log(`Path '${path}' already exists.`);
Do we want to remove this.

2023-08-14 16:03 UTC, merged