Feature/product form single options
Open-Study-College/osc pull request #1352
Opened 2023-07-30 11:05 UTC by stevenbister

- Closes #1337 

## 📝 Description

When courses don't have variants the default behaviour for Shopify is to return "title" and "default title" for product variants from the API. This means that if there are cases where we aren't adding variants to courses then we end up displaying the word "Title" and "Default Title" on the course page. E.g.

![image](https://github.com/Open-Study-College/osc/assets/23461173/5f9da30f-c99d-4098-809a-7dc9fae6a06c)

Similarly there might be cases where we are only providing one study method (e.g. online) and therefor seems unnecessary to display the form fields where they can't be interacted with.

I've updated the product form and the cart to remove the form fields where the default value is present and to display a message when only one study method is present. e.g.

<img width="1420" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/2da22b2a-1199-49f0-bb7a-2636d094472f">

<img width="701" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/af75662a-d696-44d9-9ea5-50ef206373be">

This is purely frontend so the values will still pass through to the checkout if they are available within Shopify (a level biology in this case has no variants)

<img width="515" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/f02d07a2-946b-4763-ab9f-2390bc03cf15">

## ⛳️ Current behavior (updates)

The product form will display the study method and course options regardless of how many variants we have and will also display the default data for variants returned from the storefront API.

## 🚀 New behavior

The product form will no longer display the default data, and if only one study method variant is present it will display a message.

## 💣 Is this a breaking change (Yes/No): No
 

## 📝 Additional Information

2023-08-02 09:27 UTC, mattwendzina commented
Looks good mate. Couple of comments here:
Below is a screenshot of `/courses/anatomy-physiology-combined-3-4`. I'm pointing at Sanity Production and it says Study-Method rather than Study Options. I'm guessing this is just a case of where the variants haven't been updated for this product in Shopify?
![Screenshot 2023-08-02 at 10 21 46](https://github.com/Open-Study-College/osc/assets/36510083/baff8b31-92ec-4b38-bdf6-f7f9420c7c22)

Just throwing this thought out there... wonder if it's worth doing the same for Course Options where there isn't any options. This way it would be clear what the course option is and would keep a consistent look across all of the products.

2023-08-02 09:29 UTC, mattwendzina requested changes
Hey mate, looking good. Left a couple of comments.

2023-08-02 13:39 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/storefront.helpers.spec.ts
> +    test('returns true if option name matches', () => {
Aha yeah, we can probably ditch that & `__DEV__ProductOptions`. I'll probs do that outside of this PR though

2023-08-02 15:22 UTC, stevenbister commented
> Looks good mate. Couple of comments here: Below is a screenshot of `/courses/anatomy-physiology-combined-3-4`. I'm pointing at Sanity Production and it says Study-Method rather than Study Options. I'm guessing this is just a case of where the variants haven't been updated for this product in Shopify? ![Screenshot 2023-08-02 at 10 21 46](https://user-images.githubusercontent.com/36510083/257766159-baff8b31-92ec-4b38-bdf6-f7f9420c7c22.png)

Looks okay on my end? You defo got the prod creds?
<img width="1481" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/56c19dbe-dc92-42b7-af73-fdc6dec7eee6">

> Just throwing this thought out there... wonder if it's worth doing the same for Course Options where there isn't any options. This way it would be clear what the course option is and would keep a consistent look across all of the products.

Looks like Marketing are asking to leave it off

I also noticed an eslint error so have pushed up a little fix for that

2023-08-03 09:07 UTC, mattwendzina commented
> > Looks good mate. Couple of comments here: Below is a screenshot of `/courses/anatomy-physiology-combined-3-4`. I'm pointing at Sanity Production and it says Study-Method rather than Study Options. I'm guessing this is just a case of where the variants haven't been updated for this product in Shopify? ![Screenshot 2023-08-02 at 10 21 46](https://user-images.githubusercontent.com/36510083/257766159-baff8b31-92ec-4b38-bdf6-f7f9420c7c22.png)
> 
> Looks okay on my end? You defo got the prod creds? <img alt="image" width="1481" src="https://user-images.githubusercontent.com/23461173/257860917-56c19dbe-dc92-42b7-af73-fdc6dec7eee6.png">
> 
> > Just throwing this thought out there... wonder if it's worth doing the same for Course Options where there isn't any options. This way it would be clear what the course option is and would keep a consistent look across all of the products.
> 
> Looks like Marketing are asking to leave it off
> 
> I also noticed an eslint error so have pushed up a little fix for that

Cool. All sounds good. I had another check and it does seem to be displaying correctly now 👍

2023-08-03 09:08 UTC, mattwendzina approved these changes
Looks good mate 🚢 
Prob just worth getting a ticket for updating tests/removing the `__DEV__ProductOptions` at some point so it doesn't get forgotten 👍

2023-08-03 16:16 UTC, merged