Feature/update sanity algolia webhook
Open-Study-College/osc pull request #1377
Opened 2023-08-01 17:49 UTC by mattwendzina

- [x] Close issues
- [x] Request reviewers
- [x] Assign yourself
- [x] Add labels (e.g. `build:osc-ecommerce`)
- [x] Add project
- [x] Set project status
- [x] Add milestone

---

## ☑ List all github issues that this PR will close:

- Closes #1005 
- Closes #1272 
- Closes #1273 
- Closes #1274 

## 📝 Description

Adds all product variants to Algolia through the SanityAlgolia webhook. In order to do this a lot of the original SanityAlgolia webhook code has had to be adapted to do this and as such the indexer function that was originally pulled in from the package now exists in our codebase in it's amended form.

## ⛳️ Current behaviour (updates)

The SanityAlgolia webhook was just syncing the pages and blogs.

## 🚀 New behaviour

The SanityAlgolia webhook now syncs all product variants alongside the pages and blog posts.

## 💣 Is this a breaking change (Yes/No):
No

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible cross-device impacts (iOS, Android)
- [ ] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

Need to add some info here on how to test...

2023-08-02 09:37 UTC, stevenbister requested changes
Nice man, scripting isn't my forte but nothing glaring. I still need to test it but left a few comments/possible suggestions

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
> +    const sanityClient = await getClient(true);
I don't think this needs to be awaited? `getClient` isn't an async function

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +    const shopifyIdAsNumber = shopifyResult && +shopifyResult?.product?.id.split('/').slice(-1)[0];
Am I right in thinking this is turning this `gid://shopify/Product/12345` into `12345`? I actually made a utility for this to help with the cart. `extractIdFromGid` is in `storefront.helpers.ts`

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +// TODO - pass in the limit rather than hard coding it. Update types
Do we still need this?

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const limitContent = (content: any) => {
Can we narrow this type at all? Looking at usage most of the arguments getting passed are `PortableTextBlock[]`

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export async function readBody(readable: ReadableStream) {
Do we need some jsdoc on this function too?

2023-08-02 09:37 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
Do you think naming this `isDeleted` or `isNotDeleted` or something might be clearer? `visibilityFunction` to me feels a bit vague 🤔 What do you think?

2023-08-02 10:10 UTC, stevenbister reviewed
Sorry should have done this as part of my review earlier but a couple of things I noticed on the frontend

Prices doesn't seem to be adjustable, that's both with courses selected and with no filter applied to result type
<img width="1436" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/41abad86-5e43-4b77-99b6-03869219854b">


I don't know if this is a result of this PR but when only one result is returned it sits in the middle of the page rather than the top
<img width="1811" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/f5173169-d124-47d0-920a-dcd4254a1b81">

2023-08-02 13:46 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
> +    const sanityClient = await getClient(true);
Removed

2023-08-02 13:59 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +    const shopifyIdAsNumber = shopifyResult && +shopifyResult?.product?.id.split('/').slice(-1)[0];
Nice! Added.

2023-08-02 15:26 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const limitContent = (content: any) => {
Hmm, what gets passed through from Accordion is a bit different. Plus I don't want to restrict what could get passed in because really it's just to limit the max number of entries so the actual content doesn't matter. What if I update to `unknown[]` which at least makes it clear that it should be an array of data.

2023-08-02 16:12 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +                options[0].toLowerCase() === 'study-method' &&
Goood shout. Done.

2023-08-02 16:23 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export async function readBody(readable: ReadableStream) {
Done

2023-08-02 16:28 UTC, mattwendzina commented
> Sorry should have done this as part of my review earlier but a couple of things I noticed on the frontend
> 
> Prices doesn't seem to be adjustable, that's both with courses selected and with no filter applied to result type <img alt="image" width="1436" src="https://user-images.githubusercontent.com/23461173/257778588-41abad86-5e43-4b77-99b6-03869219854b.png">
> 
> I don't know if this is a result of this PR but when only one result is returned it sits in the middle of the page rather than the top <img alt="image" width="1811" src="https://user-images.githubusercontent.com/23461173/257779846-f5173169-d124-47d0-920a-dcd4254a1b81.png">

The prices is sorted, just forgot to add as a facet in Algolia. The styling issue, yeah that's a good spot. Not quite sure how to fix this... Had a look and it may be something to do with the grid it sits in. Maybe we could have a quick look at this together?

2023-08-03 07:25 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const limitContent = (content: any) => {
Based on conversation yesterday, I've managed to make it happy by using type `unknown[]` for the content and then casting the results inside of the respective map functions. I know unknown isn't perfect, but it's an internal function (removed the export as it's not being used elsewhere) with specific, known use cases.

2023-08-03 14:29 UTC, Tom-Pearce requested changes
I've noticed there are a considerable number of optional chaining operators (`?.`). It may be prudent to double check that in all cases the value of `undefined` is acceptable in the cases where it fails to resolve the specified index. Otherwise it may lead to some unexpected behaviour. Maybe in some cases a null coalescing operator `??` may be better to provide a default value, or at least an acceptable value if it's type restricted?

2023-08-03 14:29 UTC, Tom-Pearce commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
I agree with Steven here. The function itself is looking at an `isDeleted` value, so it's far more accurate, consistent and maintainable to name the function as such.

2023-08-03 14:29 UTC, Tom-Pearce commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +                return Object.assign(standardValues(document), await serializer(document));
Dont think we need `await` here

2023-08-04 07:50 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const limitContent = (content: any) => {
Okay cool, yeah happy with that. I think `unknown` is fine for cases like this 👍

2023-08-14 07:50 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
Okay, updated 👍

2023-08-14 08:02 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
>      const body = await request.body;
This is a Remix server side function and all examples of it are as an async function so just following the convention here:
https://remix.run/docs/en/main/route/action

2023-08-14 09:24 UTC, Tom-Pearce commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
>      const body = await request.body;
Curious, as it's only running express under the hood, and afaik you don't need to await the request object.

Looking at it further the example is actually `await`ing the `formData()` function call, _not_ the `request` object itself. Here the `get()` function is not returning a `promise` so I still don't believe you need the `await`

2023-08-14 09:29 UTC, Tom-Pearce commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
>      const body = await request.body;
An example from https://remix.run/docs/en/1.19.3/utils/sessions#using-sessions. Not `await`ing the `headers.get()` function

```typescript
const session = await getSession(
    request.headers.get("Cookie")
  );
  ```

2023-08-14 15:51 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
I've changed my mind on this again...
The place this is used is here:
```
const visibleRecords = createdOrUpdatedDocs.filter((document) => {
            return visible ? visible(document) : true;
        });
```
`visible()` runs the `visibilityFunction` - yes it's checking if it's deleted, but it does this to decide if it should be visible. 

```
export const visibilityFunction = (document: DocumentStub) => {
    if (document.store?.isDeleted) {
        return false;
    }
    return true;
};
```

If it is deleted it returns false - ie it should *not* be visible on the front end. 

If this function is called `isDeleted` it doesn't make sense in context and looks confusing when you read the if statement - ie - if its deleted, return false. I think you would expect it to return true given the name of the function. It makes more sense when you understand that it's returning whether or not the product should be visible.

2023-08-14 15:56 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/actions/sanityAlgolia.tsx
>      const body = await request.body;
Sorry mate, I think I must have been half asleep when I read this, for some reason I thought you were saying that the Action function shouldn't be async... no idea where I got that from lol. 
Yes, that await isn't needed there, agreed!
Removed 👍

2023-08-14 16:01 UTC, mattwendzina commented
> I've noticed there are a considerable number of optional chaining operators (`?.`). It may be prudent to double check that in all cases the value of `undefined` is acceptable in the cases where it fails to resolve the specified index. Otherwise it may lead to some unexpected behaviour. Maybe in some cases a null coalescing operator `??` may be better to provide a default value, or at least an acceptable value if it's type restricted?

Thanks, this was a helpful comment. I've gone through checking everything, in many cases I've been able to remove chaining operators, added some null coalescing and in certain cases thrown errors or early returns for cases where certain pieces of data may be missing.

2023-08-15 08:09 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
The inner part of the `indexer` function is less of an issue as you're assigning the function to the `visible` parameter. I'm more concerned about reading it here:

```ts
const sanityAlgolia = indexer(
        {
            post: {
                index: allRecordsIndex,
            },
            page: {
                index: allRecordsIndex,
            },
            productVariant: {
                index: allRecordsIndex,
            },
        },
        (document) => {
            switch (document._type) {
                case 'post':
                    return algoliaPostAndPageDocument(document, 'Blog');
                case 'page':
                    return algoliaPostAndPageDocument(document, 'Other');
                case 'productVariant':
                    return algoliaProductDocument(document, 'Courses', storefront);
                default:
                    throw new Error(`Unknown type: ${document.type}`);
            }
        },
        (document) => {
            return visibilityFunction(document);
        }
```
At a glance `visibilityFunction` doesn't mean much.

Looking back over it, I think your suggestion of `isVisible` would be the best name for this as like you said it's returning `true` if the document hasn't been deleted. 

It would make it clearer as to the intent when it's used here then:
```ts
const sanityAlgolia = indexer(
        {
            post: {
                index: allRecordsIndex,
            },
            page: {
                index: allRecordsIndex,
            },
            productVariant: {
                index: allRecordsIndex,
            },
        },
        (document) => {
            switch (document._type) {
                case 'post':
                    return algoliaPostAndPageDocument(document, 'Blog');
                case 'page':
                    return algoliaPostAndPageDocument(document, 'Other');
                case 'productVariant':
                    return algoliaProductDocument(document, 'Courses', storefront);
                default:
                    throw new Error(`Unknown type: ${document.type}`);
            }
        },
        (document) => {
            return isVisible(document);
        }
    );
```

2023-08-15 08:51 UTC, stevenbister reviewed
Just the visibility function thing, but otherwise I think I'm happy with this :)

2023-08-15 11:31 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/sanityAlgolia.helpers.ts
> +export const visibilityFunction = (document: DocumentStub) => {
Yeah okay, fair. I guess in the context of it being a package `VisibilityFunction` makes more sense, because the idea is a consumer can provide a visibility function. But of course we're implementing this ourselves, and so within our own code I can see that it makes more sense to just name this as it is. Updated 👍

2023-08-16 09:47 UTC, stevenbister approved these changes
LGTM

2023-08-22 09:35 UTC, hall2521 approved these changes
LGTM

2023-08-23 10:19 UTC, hi-im-si commented
When saving a collection with updates courses we are returning the following error and algolia does not update accordingly:

```
SanityAlgolia sync ERROR: FetchError: request to https://open-study-college.myshopify.com/api/2023-01/graphql.json failed, reason: connect ETIMEDOUT 23.227.38.74:443
    at ClientRequest.<anonymous> (/Users/simonshahriveri/Desktop/SITES/__OSC/osc-mono/node_modules/@remix-run/web-fetch/src/fetch.js:111:11)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
  ```

2023-08-24 07:48 UTC, stevenbister commented
Can confirm I'm getting the same error as @hi-im-si 
```
SanityAlgolia sync ERROR: FetchError: request to https://openstudydev.myshopify.com/api/2023-01/graphql.json failed, reason: connect ETIMEDOUT 23.227.38.74:443
    at ClientRequest.<anonymous> (/Users/stevebister/SITES/osc/node_modules/@remix-run/web-fetch/src/fetch.js:111:11)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  erroredSysCall: 'connect'
}
```

2023-09-04 12:27 UTC, closed without merging