Feature/bloom connections styling
Open-Study-College/osc pull request #1384
Opened 2023-08-03 15:18 UTC by jkellerman

## ☑ List all github issues that this PR will close:

- Closes #

## 📝 Description
This branch:

- adds all the styling for the recruitment website
- fixes the issue in the hero component where the hero title does not remain centred when the hero body is removed in Sanity CMS
- Changes the utility class prefixes for border to enable consistency of naming

## ⛳️ Current behaviour (updates)

This is the bug we have in the hero component. When the hero body is removed in the CMS, the title will push to the top of the grid.
![Screenshot 2023-08-04 at 14 13 26](https://github.com/Open-Study-College/osc/assets/89940123/4a2dc2d1-5b93-46f6-9b99-1bc5934cec88)

![Screenshot 2023-08-04 at 14 08 29](https://github.com/Open-Study-College/osc/assets/89940123/b084a22d-c86f-4017-829a-a1a695f25444)

## 🚀 New behaviour

When there is no body content selected in the CMS, it should now be in the  centre of the grid as shown below.
![Screenshot 2023-08-04 at 14 03 47](https://github.com/Open-Study-College/osc/assets/89940123/71a1196b-46ec-4bc7-9a80-b4962a419684)

> Please describe any breaking changes. 

**Breaking change**

- References to the utility class u-b-bottom or u-b-none in ecommerce will need to be changed to u-bb-3 or u-bb-none.
 

## 📝 Additional Information

- For the hero bug fixes to applied in ecommerce, the HeroContentWrapper component needs to be implemented the same way it is in recruitment, see below.

```
 <HeroInner
                flourishColor={copyFlourishes?.color}
                flourishPattern={copyFlourishes?.pattern}
                flourishVariant={copyFlourishes?.variant}
            >
                {variant === 'tertiary' ? (
                    <HeroContentWrapper>
                        <HeroTitleGroup>
                            <Title />
                        </HeroTitleGroup>
                        {content?.body ? (
                            <HeroContent>
                                <Content
                                    value={content?.body}
                                    align={content?.horizontalAlignment}
                                    {...content}
                                />
                            </HeroContent>
                        ) : null}
                    </HeroContentWrapper>
                ) : (
                    <>
                        <Title />
                        {content?.body ? (
                            <HeroContent>
                                <Content
                                    value={content?.body}
                                    align={content?.horizontalAlignment}
                                    {...content}
                                />
                            </HeroContent>
                        ) : null}
                    </>
```

2023-08-04 09:32 UTC, stevenbister requested changes
Looking good! Left a few comments, nothing major. 

Just check the PR I think we're missing things like assignee, project status, milestone etc. and it would be good if you could fill out the description with some more details. For example a brief explanation as to why have we added the overrides or the fact you're fixing the tertiary hero.
It's good make a record of these things so if we need to go back to this PR later it would be easier to see what and why things have changed.

Could you also add the `build:osc-studio` label so we can deploy these Sanity changes.

2023-08-04 09:32 UTC, stevenbister commented on packages/osc-ui/src/styles/utilities/_util.scss
> +        prefix: "bd",
I would probably have this as just "b" rather than bd so it's consistent with the other utils

2023-08-04 09:32 UTC, stevenbister commented on packages/osc-recruitment/app/components/Hero/Hero.tsx
> +                <div className="o-grid__col o-grid__col--12 o-grid__col--5@desk ">
Could we move the fixes you've put into the hero into osc-ui? This is an issue on the ecommerce site as well so would be great if we could fix it across both sites

2023-08-04 09:32 UTC, stevenbister commented on packages/osc-recruitment/app/routes/jobs/index.tsx
> +        { rel: 'stylesheet', href: recruitmentStyles },
I don't think you need this in here. You've already declared it in your `root.tsx` so it will filter through

2023-08-04 09:32 UTC, stevenbister commented on packages/osc-recruitment/app/styles/objects/_page.scss
> +    padding: $space-xl;
I wonder if this needs a media query? Feels a bit narrow on my phone and when the menu opens it doesn't align with the edges of the header
![image](https://github.com/Open-Study-College/osc/assets/23461173/96ce72f0-5711-40da-beb4-cc4e7e16b6c8)

Perhaps on smaller devices it fills the width of the viewport and only when we get to the larger screens does it get the padding? More like this
![image](https://github.com/Open-Study-College/osc/assets/23461173/53169fec-634c-4586-93cd-53adeb39d602)

2023-08-04 12:10 UTC, jkellerman commented on packages/osc-recruitment/app/styles/objects/_page.scss
> +    padding: $space-xl;
Yeah was thinking this myself, works better with no padding in mobile

2023-08-04 12:50 UTC, jkellerman commented
This feature branch hasn't been assigned to a sprint so it should be left as no milestone right?

2023-08-04 14:23 UTC, stevenbister commented on packages/osc-recruitment/app/styles/objects/_page.scss
> +    padding: $space-xl;
Ah yeah loads better!

2023-08-04 14:34 UTC, stevenbister requested changes
Nice! Thanks for those changes :) Last one. Just make sure to double check the component in Storybook. If you're making edits to osc-ui components I would recommend doing it in Storybook so you can see how the changes effect each story for that component

2023-08-04 14:34 UTC, stevenbister commented on packages/osc-ui/src/components/Hero/hero.scss
> +                grid-template-rows: 1fr;
Could you check how the hero looks in storybook? These grid rows and the other changes are needed for the other variants.
I think you'll need to change this value further down so it' nested within the `&--tertiary` modifier, same with the `ttl__group` class maybe?

2023-08-04 14:36 UTC, stevenbister commented
> This feature branch hasn't been assigned to a sprint so it should be left as no milestone right?

It still part of the work in this sprint though, isn't it? Even though it doesn't have a task

2023-08-07 08:05 UTC, stevenbister requested changes
Looks really good! Sorry I missed this on the last one (so this should actually be the last change now 😅 )
Could you update any of the `u-b-bottom` or `u-b-none` in osc-ecommerce to the new classes? Don't want to push up a breaking change if we can help it!

2023-08-07 08:27 UTC, stevenbister approved these changes
LGTM!

2023-08-07 08:43 UTC, merged