Feature/blog buttons group
Open-Study-College/osc pull request #1403
Opened 2023-08-11 17:29 UTC by jkellerman

## ☑ List all github issues that this PR will close:

- Closes #

## 📝 Description

This is part of [Article filter #1003](https://github.com/Open-Study-College/osc/issues/1003) Task. This PR adds the buttons group for the articles filter.

![Screenshot 2023-08-11 at 18 22 35](https://github.com/Open-Study-College/osc/assets/89940123/7c31856d-7bea-4e3f-8132-b7060f3d5904)

## ⛳️ Current behaviour (updates)

N/A

## 🚀 New behaviour

N/A

## 💣 Is this a breaking change (Yes/No): No

> Please describe any breaking changes.

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible cross-device impacts (iOS, Android)
- [ ] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

> Any additional contextual information, such as relevant links/articles/documentation

2023-08-15 09:42 UTC, stevenbister requested changes

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ecommerce/app/queries/sanity/categories.ts
> +        _rev,
Do you plan on using the `_rev` property? I don't think you need to return it?

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/Button.stories.tsx
> +export const SeptenaryDecorator = (Story) => (
Do we need this? It's causing an error in Storybook
![image](https://github.com/Open-Study-College/osc/assets/23461173/149c1c4f-f95f-49eb-93af-35124f83e358)

If you need to add a background colour or some other settings to a story you're better off creating a template like we do above, so something like

```tsx
const SeptenaryTemplate: Story<ButtonProps> = ({ children, ...args }) => (
<div className="...">
    <Button {...args}>{children}</Button>
</div>
);
```
Then replacing the template on line 134
```tsx
export const Septenary = SeptenaryTemplate.bind({});
Septenary.args = {
    children: 'button',
    variant: 'septenary',
};
```

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +            bg-hover-color: var(--btn-hover-color-tertiary),
I wonder if it's worth making the hover colours match the active state in the design, so that semi-transparent background
<img width="313" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/efdafab5-31e5-4839-bfa9-489ec993d9ac">
I think it would look odd if it was navy and then became pink

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                lg: (
As there's only one instance of this the only size should be `md` as that's the default `size` for the buttons. Saves you having to remember to pass is as a prop when using the variant then.

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                    padding: $space-l $space-3xl,
I would reduce the size of the vertical padding to `$space-m`. It'll bring the height of the buttons down to closer match the design. They feel a bit big at the moment.
```suggestion
                    padding: $space-m $space-3xl,
```

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                    font-size: $fs-m
I think the font is too big as well, looking at the design it should be `16px`, so you can use `--font-scale-base` in this case to bring it to `1rem`
```suggestion
       font-size: var(--font-scale-base);
```

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
I would prefer to use `none` here rather than `unset`, I think. More of a personal preference as I find it a bit more explicit. `unset` could inherit from somewhere so might end up with some weird behaviour 🤔

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +            gap: none;
`none` doesn't exist as a property for `gap` should be `0` instead
```suggestion
            gap: 0;
```

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +        &--row {
Do we need this explicitly being added? `display: flex` defaults to `row` anyway so not sure what benefit we gain by adding this modifier?

2023-08-15 09:42 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +        &__articles {
The way this is being used in the markup suggests this should be a modifier rather than an element. Elements generally go inside of a block so should be used like this
```html
<div class="c-btn-group c-btn-group--row c-btn-group--none">
  <div class="c-btn-group__articles">
    <button>...</button>
  </div>
</div>
```

As it is modifying behaviour I would also name it something more descriptive as to what it's doing `--center` perhaps? So your markup would end up looking like
```html
<div class="c-btn-group c-btn-group--row c-btn-group--none c-btn-group--center">
    <button>...</button>
</div>
```

2023-08-21 07:13 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                    <div className="u-bg-color-gradient-primary-270">
I have updated this in the blog-posts PR, it can be reviewed there

2023-08-21 08:14 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
For the border?

2023-08-21 08:22 UTC, jkellerman commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
For the button. In mobile the width of the button needs to be 100% so it fits the whole viewport. In desktop, if i set width to none, the button has no padding and shrinks. The only solution I know is to use unset here.

2023-08-21 10:15 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
I'm not talking about the width. I'm talking about the `border-bottom`. Also does `width: 100%` not work?

2023-08-21 10:21 UTC, jkellerman commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
No 100% doesn't work, the buttons stack in a column when doing this.

2023-08-21 10:22 UTC, jkellerman commented on packages/osc-ui/src/components/Button/button.scss
> +                        border-bottom: unset;
I've changed border-bottom to none

2023-08-22 08:56 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                    <div className="u-bg-color-gradient-primary-270">
Okay that's fine. Just for future it would be better to do adjustments like that in PR it's related to as it makes reviewing difficult. This is the button group PR so creating the button group component in here would keep the PR's more modular. If that makes sense?

2023-08-22 09:03 UTC, stevenbister approved these changes

2023-08-22 09:03 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                    <div className="u-bg-color-gradient-primary-270">
Yeah definitely, I know it must seem confusing and I'm aware that I could have handled this better. Reason why I did it was because I made a number of changes to how I structured the components in the next PR including the button group so I did all there instead. Will get in the habit of committing more often as well so things like this don't happen, I've noticed things can pile up real fast 😅.

2023-08-23 08:50 UTC, merged