Feature/add autocomplete to site header
Open-Study-College/osc pull request #1409
Opened 2023-08-15 11:06 UTC by mattwendzina

### 🧹 Please check off the following before submitting:

- [X] Close issues
- [X] Request reviewers
- [X] Assign yourself
- [X] Add labels (e.g. `build:osc-ecommerce`)
- [X] Add project
- [X] Set project status
- [X] Add milestone

---

## ☑ List all github issues that this PR will close:

- Closes #1156 
- Closes #1157 

## 📝 Description

Adds Autocomplete to the Site Header

## ⛳️ Current behaviour (updates)

No functionality in site header

## 🚀 New behaviour

- All pages can now access Autocomplete through the site header
- Fixes issue with recentSearches plugin not working

## 💣 Is this a breaking change (Yes/No):
No

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible cross-device impacts (iOS, Android)
- [ ] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information
For manual testing I would suggest using the following set of Algolia env vars:
```
ALGOLIA_APP_ID="832ZSJM9EO"
ALGOLIA_API_KEY_SEARCH="382c5e1a36d4053d208752ffab373418"
ALGOLIA_API_KEY_ADMIN="4404d2748e0fe30a94aebe1f50e78e2e"
ALGOLIA_PRIMARY_PRODUCTS_INDEX=dev_all_records
ALGOLIA_PRIMARY_COLLECTIONS_INDEX=dev_collections
ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID=dev_all_records_grouped_by_id
ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS=dev_all_records_grouped_by_id_query_suggestions
ALGOLIA_HITS_PER_PAGE=10
```

2023-08-16 09:46 UTC, stevenbister requested changes
Nice work!

Couple of minor comments but also some design-y suggestions. 

Could we remove the box-shadow from the autocomplete and in this case use the `isFull` prop on the button. So would look like this instead:

<img width="530" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/0df0870d-ae54-4e91-80b4-bc513b543a7b">

Looks a bit odd with the shadow atm and this should bring it closer to the design.

Another nice to have (and no worries if not possible or a massive faff) is it possible to have the autocomplete suggestions open constantly? So they're there immediately when the modal is opened?

2023-08-16 09:46 UTC, stevenbister commented on packages/osc-ecommerce/app/root.tsx
> +import { algoliaAutocompleteEnvVars } from './types/algolia';
Eslint warning here?

2023-08-16 09:46 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +export const links: LinksFunction = () => {
I think as this is going to be something that's used in the header it'll be across every page so these stylesheets can be just added to the root.tsx? Rather than putting them on every route?

2023-08-22 17:18 UTC, mattwendzina commented
> Nice work!
> 
> Couple of minor comments but also some design-y suggestions.
> 
> Could we remove the box-shadow from the autocomplete and in this case use the `isFull` prop on the button. So would look like this instead:
> 
> <img alt="image" width="530" src="https://user-images.githubusercontent.com/23461173/260950653-0df0870d-ae54-4e91-80b4-bc513b543a7b.png">
> Looks a bit odd with the shadow atm and this should bring it closer to the design.
> 
> Another nice to have (and no worries if not possible or a massive faff) is it possible to have the autocomplete suggestions open constantly? So they're there immediately when the modal is opened?

Shadow and button sorted. Good shout on opening the modal too. I've added an `openOnLoad` prop and a useEffect that will focus the input on load if this is true which triggers the modal to open 👍

2023-08-22 17:26 UTC, mattwendzina commented on packages/osc-ecommerce/app/root.tsx
> +import { algoliaAutocompleteEnvVars } from './types/algolia';
Oops, forgot to put `type`. Eliminated this in the rebase 😅

2023-08-22 17:45 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Header/Header.tsx
> +                        <SearchModal actionNav={actionNav} algoliaEnvVars={algoliaEnvVars} />
I've added styling to align it correctly on the vertical as this was out even on desktop. But yeah I agree. 
I'll create a separate ticket for sorting on mobile. I think it will also need to think about what to do on search page or if marketing have added a search module near top of page as you'll then have two search boxes, so will need some additional logic there too I guess...

2023-08-22 17:45 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +export const links: LinksFunction = () => {
Yeah, good point. Done 👍

2023-08-23 08:31 UTC, stevenbister approved these changes
LGTM!

2023-08-23 15:40 UTC, merged