Feature/blog posts
Open-Study-College/osc pull request #1416
Opened 2023-08-16 08:14 UTC by jkellerman

### 🧹 Please check off the following before submitting:

- [ ] Close issues
- [ ] Request reviewers
- [ ] Assign yourself
- [ ] Add labels (e.g. `build:osc-ecommerce`)
- [ ] Add project
- [ ] Set project status
- [ ] Add milestone

---

## ☑ List all github issues that this PR will close:

- Closes #1001 

## 📝 Description

This branch adds blog posts for the blog index page. These posts include:

- An Island grid with the latest News post on the left card and the latest post for each other categories on the right cards
- A blog card for the latest Featured post
- A list of the latest blog cards that are not in the island grid or the latest Featured post

It uses Sanity groq queries to get the correct posts. Also a new 'featured' field has been added to posts in Sanity to declare whether a post is featured or not.

I have also created a new card paragraph component, which is used to help with the alignment of blog post cards in the grid for the latest posts. This may not be necessary, however I think it maintains a more clean and organised design.

A final note, the list of latest posts at the bottom of the blog page are currently being sliced to show the latest 4 posts. This is to be changed and will be use pagination, which I will complete in a new feature branch. 

## ⛳️ Current behaviour (updates)

N/A

## 🚀 New behaviour

N/A

## 💣 Is this a breaking change (Yes/No): No

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible cross-device impacts (iOS, Android)
- [ ] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

> Any additional contextual information, such as relevant links/articles/documentation

2023-08-16 15:19 UTC, stevenbister requested changes

2023-08-16 15:19 UTC, stevenbister commented on packages/osc-ecommerce/app/types/sanity.ts
> +    body?: ModuleContent[];
I don't think we export the body directly on the hero do we? It lives inside the slides as far as I can tell.

If we do then I think the type would be better off as `contentModule`. That's what's being used in the slide content if not, then it should be `PortableTextBlock[];`

2023-08-16 15:19 UTC, stevenbister commented on packages/osc-ecommerce/package.json
> +    "@react-aria/visually-hidden": "^3.8.3",
Like I said before we have our own visuallyhidden component in osc-ui. Can you uninstall this

2023-08-16 15:19 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                                    <CardHeader>
I've noticed you've nested all of your card components within the card header. You'll need to move the body and the footer out for the card to behave properly. This is why everything looks misaligned. This is how they should look
<img width="1347" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/0634c056-4afe-48b0-9fda-aa6e4c298c2d">

2023-08-16 15:19 UTC, stevenbister commented on packages/osc-ui/src/utils/truncate.ts
> +    if (typeof input === 'function') {
We shouldn't be allowing functions to pass into this you can't run substring against anything but a string. Is there a reason for this?

2023-08-21 13:02 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
I looked into this and it appears that blogCard component in ecommerce is being used in the instantsearch, meaning the data structure of the card is geared towards algolia. I'm not sure if there is an easy way to tweak it so that it works with the content we get from sanitys so what i've done instead is create new components to break it all down, as mentioned in your below comments.

I've also created some utility functions which i've placed in utils folder for cards to get some of the data as they are used across multiple components. Couldn't think of another approach to this, taking into consideration how the data comes in from sanity.

2023-08-21 13:03 UTC, jkellerman commented on packages/osc-ui/src/utils/truncate.ts
> +    if (typeof input === 'function') {
Yeah, I noticed that doing this was unnecessary, I've set it back to how it was and works fine.

2023-08-22 09:08 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
There's one that's in `components/Cards/BlogCard.tsx` I'm pretty sure that one is set up for Sanity data?

2023-08-22 09:16 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
Okay looking at that component a bit more I think it can be used in place of your featured card. You'll just need to pass through a few props such as `data.fullwidth` on line 39.

Could we tweak this component to handle different card variants maybe? I'm conscious that we are duplicating a lot of the cards and functionality within them where we might not need to?

2023-08-22 09:45 UTC, stevenbister requested changes

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Button/ButtonGroup.tsx
> +    data: categoryModule[];
Are we certain we'll always get data back? Might be worth making this an optional prop and setting a check in the component to handle null/undefined responses. Otherwise this component will throw an error when we release to prod without any categories set up

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +    data: postHeroModule;
Same as before I would make this optional and set some checks below for if it returns a falsey value. Likely in a CMS that the data could not be available

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +            <BlogCard
Can we add the `blockLink` prop to this card so the whole thing is clickable? We're using it on the other places this card is usable so keeps things consistent

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +    data: postHeroModule;
I'm not gonna mention this on the other cards but worth doing it there as well

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/utils.tsx
> +    const body = contentModule?.body[0];
Getting a ts error 
```
Property 'body' does not exist on type 'ModuleContent'.
```

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/utils.tsx
> +    const contentModule = data.modules.find(
Worth checking if data exists on all of these utils?

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/IslandGridCard.tsx
> +    date?: boolean;
As these are booleans it would be better to prefix the prop with a verb such as `has` or `is` so in this case it would be `hasBody` or `hasDate`

2023-08-22 09:45 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                    <div className="o-container">
Can you have a copy of this in `PreviewSuspense` as well? 
For reference the preview suspense is for previewing the page before it's published so we want to mimic as much of is as possible

2023-08-22 11:31 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
Okay, maybe you could clarify something for me. That BlogCard component that we already have is being used in our modules and is currently fetching the 3 popular posts at the top of the blogs page. If you look at the data it grabs everything in the 'reference' property. There is no reference property when querying these posts so isn't the best way to just create a separate component for these posts?

2023-08-22 13:34 UTC, jkellerman commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +    data: postHeroModule;
For featured card if it returns a falsey value, what do you think we should have as placeholder, just some text or some dummy content?

2023-08-23 07:55 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Button/ButtonGroup.tsx
> +    data: categoryModule[];
Yeah I think it's worth doing. In a CMS with users you can never be sure they won't remove them for whatever reason so it's a good safety net

2023-08-23 07:55 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +    data: postHeroModule;
I think we just return null, if there's no data then the card shouldn't render

2023-08-23 08:00 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
I think we could just check for the existence of the reference and change the values based on that? If you have a look at the `CourseCard` it's set to handle data from Sanity or Shopify by checking for the `store` property.
e.g.
```tsx
const { product } = props;
const store = product?.reference?.store;

if (!store && !product) return null;

const title = store?.title ?? product.title;
const slug = store?.slug?.current ?? product.handle;
```

I might be oversimplifying but could we do something similar here?

2023-08-23 08:12 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/IslandGridCard.tsx
> +    date?: boolean;
Don't forget to update the places these props are used, looks like these are still being used in `PostsGrid` etc.

2023-08-23 08:13 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +                                    <CardHeader>
I think your best bet would be to add `grid-template-rows: 250px 1fr` to the `c-card--blog` class looks like it does a good job of tightening this up

<img width="1355" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/14ef89ea-53ad-4ce2-a4b1-95207fba2882">

2023-08-23 10:10 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    const getFeaturePostBgColour = (data: postData) => {
As discussed, there are quite a differences between featured card and the blogCard component, which would require a lot of tweaking and could affect some other components elsewhere so will keep these separate.

2023-08-24 08:23 UTC, stevenbister requested changes

2023-08-24 08:23 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +        newsData._id,
Noticed these don't exist in the production dataset atm so causing the app to crash if you have `SANITY_STUDIO_API_DATASET="production"` set in you env

```
TypeError: Cannot read properties of undefined (reading '_id')
    at loader14 (/Users/stevebister/SITES/osc/packages/osc-ecommerce/build/index.js:11560:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.callRouteLoaderRR (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at async callLoaderOrAction (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:3626:16)
    at async Promise.all (index 0)
    at async loadRouteData (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2954:19)
    at async queryImpl (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2735:20)
    at async Object.queryRoute (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/router/router.ts:2675:18)
    at async handleDataRequestRR (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:75:20)
    at async requestHandler (/Users/stevebister/SITES/osc/node_modules/@remix-run/node/node_modules/@remix-run/server-runtime/dist/server.js:49:18)
```

Probably worth adding some optional chaining to prevent this

2023-08-24 08:23 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/IslandGridCard.tsx
> +        return (
I think it would be better to return `null` rather than a message like this in case the live site has any issues. We probably don't want to display an error like this to customers

2023-08-24 08:23 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Button/ButtonGroup.tsx
> +        return (
I think it would be better to return null rather than a message like this in case the live site has any issues. We probably don't want to display an error like this to customers

2023-08-24 08:23 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Cards/FeaturedCard.tsx
> +        return (
I think it would be better to return null rather than a message like this in case the live site has any issues. We probably don't want to display an error like this to customers

2023-08-24 08:23 UTC, stevenbister commented on packages/osc-ui/src/components/Card/card.scss
> +            grid-template-rows: 250px 1fr;
This will need to be wrapped in a media query, the image looks too big on mobile

<img width="465" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/4a9c8c1f-25f9-47af-994e-9943a6c69382">

Should look like

<img width="422" alt="image" src="https://github.com/Open-Study-College/osc/assets/23461173/734f0cc5-f6d6-474f-a8d2-75982e8e74a7">

2023-08-25 10:25 UTC, stevenbister requested changes
Nice work man, one last thing and I think we're good

2023-08-25 10:25 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    if (newsData && careersAdviceData && studyTipsData && successStoriesData && featuredPostData) {
I see what you're trying to do here but ideally we'd want to have the option for posts to show if some of these options are missing. 
At the moment lets say Marketing decide not to feature any posts; then no posts will show at all.

Like I said in my last comment you could use optional chaining to handle this e.g
```ts
const idsToRemoveFromAllPosts = [
        newsData?._id,
        careersAdviceData?._id,
        studyTipsData?._id,
        successStoriesData?._id,
        featuredPostData?._id,
    ];
```
Or if that doesn't quite work/you don't like that this would also work
```ts
const idsToRemoveFromAllPosts = [
        newsData && newsData._id,
        careersAdviceData && careersAdviceData._id,
        studyTipsData && studyTipsData._id,
        successStoriesData && successStoriesData._id,
        featuredPostData && featuredPostData._id,
    ];
```
This way if one of these is missing then the others should still populate the array

2023-08-25 10:27 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    if (newsData && careersAdviceData && studyTipsData && successStoriesData && featuredPostData) {
Oh just to follow on from this, I find it helpful when I'm creating things like this to switch between `staging` and `production` datasets so I can see the differences and possibly catch things we may have in set up in development but aren't in prod yet.

2023-08-25 10:58 UTC, jkellerman commented on packages/osc-ecommerce/app/routes/blog/index.tsx
> +    if (newsData && careersAdviceData && studyTipsData && successStoriesData && featuredPostData) {
Good point thanks, have done this now.

Also thanks for the tip, on switching between staging or prod, very helpful.

2023-08-29 11:31 UTC, merged