Refactor/remove remix from autocomplete
Open-Study-College/osc pull request #1485
Opened 2023-08-25 10:10 UTC by stevenbister

### 🧹 Please check off the following before submitting:

- [ ] Close issues
- [X] Request reviewers
- [X] Assign yourself
- [X] Add labels (e.g. `build:osc-ecommerce`)
- [ ] Add project
- [ ] Set project status
- [ ] Add milestone

---

## ☑ List all github issues that this PR will close:

N/a

## 📝 Description

Using Remix's `Link` or `NavLink` component in osc-ui is causing some issues within Storybook and also when trying to use components in apps with a later version of Remix. E.g. academic hub is now on v 1.19. You get this error:

```
Error: useHref() may be used only in the context of a <Router> component.
    at invariant (http://localhost:6006/node_modules/.cache/sb-vite/deps/@remix-run_react.js?v=4e519c76:200:11)
    at useHref (http://localhost:6006/node_modules/.cache/sb-vite/deps/@remix-run_react.js?v=4e519c76:2689:34)
    at http://localhost:6006/node_modules/.cache/sb-vite/deps/@remix-run_react.js?v=4e519c76:4622:14
    at renderWithHooks (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:12171:26)
    at updateForwardRef (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:14327:28)
    at beginWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:15934:22)
    at beginWork$1 (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:19749:22)
    at performUnitOfWork (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:19194:20)
    at workLoopSync (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:19133:13)
    at renderRootSync (http://localhost:6006/node_modules/.cache/sb-vite/deps/chunk-6ZDUWZXD.js?v=4e519c76:19112:15)
```

I've updated the inner `Link` component within out `Autocomplete` with a `linkComponent` prop. Therefore letting us pass the `Link` or `NavLink` component from outside like this
```tsx
import { Link } from '@remix-run/react';

<OSCAutocomplete
    algoliaSearchClient={algoliaSearchClient}
    ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID={
        algoliaEnvVars.ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID
    }
    ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS={
        algoliaEnvVars.ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS
    }
    openOnFocus={true}
    linkComponent={Link}
/>
```

## ⛳️ Current behaviour (updates)

- Our `Autocomplete` component has a built in `Link` component from Remix

## 🚀 New behaviour

- `Autocomplete` now has a `linkComponent` prop that can pass components like `Link` through

## 💣 Is this a breaking change (Yes/No): Yes

```tsx
// OLD
<OSCAutocomplete
    algoliaSearchClient={algoliaSearchClient}
    ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID={
        algoliaEnvVars.ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID
    }
    ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS={
        algoliaEnvVars.ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS
    }
    openOnFocus={true}
/>

// NEW
import { Link } from '@remix-run/react';

<OSCAutocomplete
    algoliaSearchClient={algoliaSearchClient}
    ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID={
        algoliaEnvVars.ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID
    }
    ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS={
        algoliaEnvVars.ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS
    }
    openOnFocus={true}
    linkComponent={Link}
/>
```
You'll need to import the Link from Remix

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible cross-device impacts (iOS, Android)
- [x] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

> Any additional contextual information, such as relevant links/articles/documentation

2023-08-31 08:55 UTC, jkellerman requested changes

2023-08-31 08:55 UTC, jkellerman commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +            linkComponent={Link}
Error here as well, saying that ALGOLIA_APP_ID doesn't exist as type on Autocomplete

2023-08-31 14:22 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +            linkComponent={Link}
I've fixed the types but the tests are failing which I think are out of scope for this PR

2023-09-04 08:32 UTC, jkellerman approved these changes
LGTM

2023-09-07 10:59 UTC, merged