Feature/add hydrogen UI to eccommerce and academic hub
Open-Study-College/osc pull request #238
Opened 2022-10-03 12:49 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-10-03 14:31 UTC, aaacafe786 commented on packages/osc-academic-hub/app/context/apollo.tsx
> +// const authMiddleware = new ApolloLink((operation, forward) => {
i think we might be able to do auth with apollo too

2022-10-03 15:39 UTC, stevenbister commented on packages/osc-academic-hub/app/context/apollo.tsx
> +// const authMiddleware = new ApolloLink((operation, forward) => {
That's cool! Do you think it's worth removing this commented out code to keep things tidy or do you reckon we'll need it in the near future?

2022-10-03 15:42 UTC, stevenbister commented on packages/osc-academic-hub/shopify-client.js
> +import { createStorefrontClient } from '@shopify/hydrogen-ui-alpha';
Sorry, being a little pedantic on this one. For the Sanity work I put the client & config files into a `app/lib/sanity` folder. 

Think it's worth putting this in the same place? Perhaps `app/lib/shopify`? 

Probs the same for `osc-ecommerce`

2022-10-03 15:43 UTC, aaacafe786 commented on packages/osc-academic-hub/app/context/apollo.tsx
> +// const authMiddleware = new ApolloLink((operation, forward) => {
probably worth removing tbh, link for reference: https://www.apollographql.com/docs/react/networking/advanced-http-networking/

2022-10-03 18:31 UTC, hi-im-si commented on packages/osc-academic-hub/shopify-client.js
> +import { createStorefrontClient } from '@shopify/hydrogen-ui-alpha';
I agree. Application organisation is definitely a +1

2022-10-04 13:19 UTC, aaacafe786 commented on packages/osc-academic-hub/app/context/apollo.tsx
> +// const authMiddleware = new ApolloLink((operation, forward) => {
done

2022-10-04 16:27 UTC, hi-im-si requested changes

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-ecommerce/app/root.tsx
>  // import { PushNotification } from '~/utils/server/pwa-utils.server';
If you need to comment-out code please define a reason so as to ensure it has validity....else, just remove it.

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-ecommerce/.node-persist/storage/b48b13e73a6ac2a86dc54425dd24d9ff
> -{"key":"subscription","value":{"endpoint":"https://fcm.googleapis.com/fcm/send/eawSDl30ElM:APA91bECSCgSO9ANhbH7rTtue9v7emfcg_Eb_KYjsmm7568HiM9oNOYsoQ63ggeS4slpjEV9ZbTa4xdcnhKWTF5UpU_2_PaGwJWgNPnt8tBl
I am guessing these files should be ignored?

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-academic-hub/package.json
> +    "@shopify/hydrogen-ui-alpha": "^2022.7.5",
Can you remind me for the need to install shopify into the academic hub?

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-academic-hub/app/routes/index.tsx
> +
this is just test code introduced via the stability test. i dont think it is necessary to keep at this time.

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-academic-hub/app/routes/index.tsx
> +            />
this is just test code introduced via the stability test. i dont think it is necessary to keep at this time.

2022-10-04 16:27 UTC, hi-im-si commented on packages/osc-academic-hub/.node-persist/storage/b48b13e73a6ac2a86dc54425dd24d9ff
> +{"key":"subscription","value":{"endpoint":"https://fcm.googleapis.com/fcm/send/etRqrTQkhRU:APA91bFfIQ1Ne-hCmYmS0krbPJQ2yCYmZpn20q7u3p3w2BA7GjIzPDNCGQOynD_Bdvyg1ydmCch8v6hli6Ar6ltOTdJCQkM5NSNQqkf_ZYtY
I am guessing these storage files can be added to the .gitignore?

2022-10-05 08:24 UTC, aaacafe786 commented on packages/osc-academic-hub/.node-persist/storage/b48b13e73a6ac2a86dc54425dd24d9ff
> +{"key":"subscription","value":{"endpoint":"https://fcm.googleapis.com/fcm/send/etRqrTQkhRU:APA91bFfIQ1Ne-hCmYmS0krbPJQ2yCYmZpn20q7u3p3w2BA7GjIzPDNCGQOynD_Bdvyg1ydmCch8v6hli6Ar6ltOTdJCQkM5NSNQqkf_ZYtY
done

2022-10-05 08:25 UTC, aaacafe786 commented on packages/osc-academic-hub/app/routes/index.tsx
> +            />
done

2022-10-05 08:25 UTC, aaacafe786 commented on packages/osc-academic-hub/app/routes/index.tsx
> +
done

2022-10-05 10:48 UTC, hi-im-si approved these changes
LGTM!

2022-10-14 10:24 UTC, hi-im-si commented on package.json
> +    "@cypress/webpack-batteries-included-preprocessor": "^2.2.3",
@stevenbister just a note that this will most likely end up being replaced in line with the playwright implementation

2022-10-14 10:26 UTC, hi-im-si commented on packages/osc-ecommerce/app/lib/shopify/shopify-client.js
> +    storefrontApiVersion: '2022-07'
would this be better managed in a ENV variable?

2022-10-14 14:28 UTC, stevenbister commented on package.json
> +    "@cypress/webpack-batteries-included-preprocessor": "^2.2.3",
@aaacafe786 What's this for?

2022-10-17 08:19 UTC, alymkarimg commented on package.json
> +    "@cypress/webpack-batteries-included-preprocessor": "^2.2.3",
testing something, does not need to be here

2022-10-17 08:21 UTC, aaacafe786 commented on packages/osc-ecommerce/app/lib/shopify/shopify-client.js
> +    typeof document !== 'undefined'
done

2022-11-04 16:52 UTC, closed without merging