fix: added modal component
Open-Study-College/osc pull request #381
Opened 2022-10-13 13:08 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-10-17 09:25 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                    <ModalHeader>{title}</ModalHeader>
I think this should have a h2 inside it or a Chakra heading. Semantically it'll make it clearer for screen readers and whatnot.

```ts
<ModalHeader>
    <Heading as="h2">{title}</Heading>
</ModalHeader>
```

2022-10-17 09:26 UTC, stevenbister requested changes

2022-10-17 09:26 UTC, stevenbister commented on .github/workflows/release.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
Should these changes be a separate PR?

2022-10-17 09:26 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                    <ModalHeader>{title}</ModalHeader>
I think this should have a h2 inside it or a Chakra heading. Semantically it'll make it clearer for screen readers and whatnot.

```ts
<ModalHeader>
    <Heading as="h2">{title}</Heading>
</ModalHeader>
```

2022-10-19 11:06 UTC, hi-im-si requested changes
Missing Storybook. Once component is added to storybook then there should be no need to render this in the root.tsx.

Also will need some basic tests

2022-10-27 14:34 UTC, aaacafe786 commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                    <ModalHeader>{title}</ModalHeader>
done

2022-11-01 08:20 UTC, stevenbister approved these changes

2022-11-01 09:04 UTC, Tom-Pearce commented
> Closes #
> 
> ## 📝 Description
> > Add a brief description
> 
> ## ⛳️ Current behavior (updates)
> > Please describe the current behavior that you are modifying
> 
> ## 🚀 New behavior
> > Please describe the behavior or changes this PR adds
> 
> ## 💣 Is this a breaking change (Yes/No):
> ## 📝 Additional Information

Can you fill the template out please Al - I know it's just a modal component and it's pretty self explanatory, but good habit to get into, and also add the `- Closes #XXX` statements for the relevant issues

2022-11-01 09:08 UTC, Tom-Pearce commented
Not sure if chromatic is bugged? I'm not seeing any difference when switching between the small/medium/large/xl modals

2022-11-01 10:35 UTC, Tom-Pearce requested changes

2022-11-01 10:35 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                        )}
I feel the variable names are confusing. To me, `closeDisabled` means the user cannot manually close the modal, and that it would be done programatically, such as after filling out a form - would be useful for a "login modal."

Then `hideCloseButton` should hide both the X button at the top and the "close" button in the footer - or split it into `hideHeaderCloseButton` and `hideFooterCloseButton`. 

Then if `closeDisabled` is true it should automatically set `hideCloseButton` to true - or override the setting at the render level. I.e. `{!hideCloseButton && !closeDisabled} // then render button`

2022-11-03 12:13 UTC, aaacafe786 commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                <ModalOverlay backgroundColor={overlayColour} />
hey mate, as per discussion, i will leave this as default until we have come up with a suitable way of applying colours to components

2022-11-03 13:07 UTC, aaacafe786 commented on packages/osc-ui/src/components/Modal/Modal.tsx
> +                        )}
done

2022-11-04 15:57 UTC, hi-im-si approved these changes

2022-11-04 16:35 UTC, merged