feat: create Badge component, tests and stories
Open-Study-College/osc pull request #444
Opened 2022-10-20 09:17 UTC by mattwendzina

Closes #270 

## 📝 Description

Add Chakra Badge component along with Stories and tests to OSC UI.

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

New Badge component

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

2022-10-20 11:29 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.spec.tsx
> +    test('renders a Span element for the Badge component', () => {
I think this test might be unnecessary. We can safely assume that Chakra would be generating the correct tag.

The only time I might want to test this is if we has something like an `as` prop where we have the option to change the node.

2022-10-20 11:37 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.tsx
> +import './badge.css';
It looks like this might be causing a couple of errors. I _think_ Al's changed how rollup works so this should be `./badge.scss`. @aaacafe786 would be able to confirm though

2022-10-20 15:25 UTC, mattwendzina commented on packages/osc-ui/src/components/Badge/Badge.spec.tsx
> +    test('renders a Span element for the Badge component', () => {
Yeah, sounds reasonable. Removed.

2022-10-20 15:29 UTC, mattwendzina commented on packages/osc-ui/src/components/Badge/Badge.tsx
> +export interface Props {
Hey mate, 
This is covered in tags I think. Have a look at the link below and let me know if this is what you're thinking. This is next up on my todo list = D
https://chakra-ui.com/docs/components/tag

2022-10-20 15:35 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Badge/Badge.tsx
> +export interface Props {
Fair point, I would have consolidated them under the same component personally, but if chakra has separated them then makes sense to stick to that.

2022-10-21 07:51 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.tsx
> +import './badge.css';
Ahh yeah, been there 😂

2022-10-21 08:01 UTC, stevenbister requested changes
Just those last two things from me, otherwise looks good! 🚀

2022-10-21 09:48 UTC, mattwendzina commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Yep, variant controls the look of the button. I've added the Primary variant and spread its args across the other two.
I'm switching the order though so that the control for the chosen variant is the first option. I feel like that make most sense from a UX perspective? e.g. For the 'Colour' variant, the first control to toggle is the colour one, etc...

2022-10-21 10:14 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Cool. Hmm I see what you're saying but I'm not sure I agree 🤔 

If I'm flicking through the controls in Storybook I think I would expect them to be in the same place

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/23461173/197171978-70e55d83-406f-420f-bdb2-fbc6c9354dcb.png">

Having said that it looks like I've not followed my own thoughts entirely on the Trustpilot one as Stars is higher up on the Primary story than the others 😅 Probably because I'm just letting it set itself...

Happy to say this is resolved anyway :)

2022-10-21 10:15 UTC, stevenbister approved these changes
LGTM!

2022-10-21 10:22 UTC, mattwendzina commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Hmm, what do you think of how Chakra themselves have done it?
https://chakra-ui.netlify.app/?path=/story/code--default
This looks pretty neat. 
I may not quite understand the reasoning/use cases for Storybook strongly enough. A lot/most of the examples I can see on their website don't really make any use of controls. I've kind of thought maybe it's useful to be able to change colour - but does that really add any value? I like their approach of just showing all the colours and just settings the variations based on the different looks of the badge. 
I guess controls will have more value in complex components, but in this case I'm now thinking they aren't really important.

2022-10-21 10:33 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Tbh I've been eyeing up Monday.com https://style.monday.com/?path=/docs/buttons-button--overview I really like the idea that they include docs, where they showcase the different variants. Then the Sandbox only contains the primary one for you to change the controls with.

I don't think there is a real direction with Storybook currently, other than an encapsulated place to build the components. [I'd like to make it more of a "thing"](https://github.com/Open-Study-College/osc/discussions/244) but yeah right now there's not a lot to it. It's mostly defaults

2022-10-21 10:35 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
And I think once the design team have done their bit we'll have more direction and rules around what we can & can't do with a component. At the moment it's a still up in the air

2022-10-21 11:13 UTC, mattwendzina commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Yeah I really like this. Would be more work, but it would be really robust if it actually gets used. I just know in my last job that marketing basically never really used Storybook so ultimately it didn't really provide much value in the long term. I'm sure it was useful in the initial stage of building out components though 🤷‍♂️

I've pushed up a commit in the more Chakra way which required rejigging how it works a bit (used the 'creating a template component' example -https://storybook.js.org/docs/react/writing-stories/stories-for-multiple-components)
which I think is nicer. 

Happy either way though, can revert this commit and stick to how it is.

2022-10-21 11:22 UTC, stevenbister commented on packages/osc-ui/src/components/Badge/Badge.stories.tsx
> +Variant.args = {
Yeah for sure, I'd love for it to be adopted but not one for now.

Niiiiice yeah I like that a lot :D LGTM

2022-10-21 11:35 UTC, merged