Feature/algolia instant search green flash
Open-Study-College/osc pull request #521
Opened 2022-11-03 16:58 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-11-07 16:20 UTC, stevenbister commented on packages/osc-academic-hub/app/components/Search/instantSearch/InstantSearch.tsx
> +        ></OscInstantSearch>
I reckon this should be self closing rather than having the closing tag if there are no children to pass to it

2022-11-07 16:25 UTC, stevenbister commented on packages/osc-academic-hub/app/routes/search/index.tsx
> +        ></InstantSearch>
Can this be self closing?

2022-11-07 16:26 UTC, stevenbister commented on packages/osc-academic-hub/app/routes/search/index.tsx
> +        ></InstantSearch>
Can this be self closing?

2022-11-07 16:29 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Search/instantSearch/InstantSearch.tsx
> +        ></OscInstantSearch>
Can this be self closing?

2022-11-07 16:30 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/search/index.tsx
> +        ></InstantSearch>
Can this be self closing?

2022-11-07 16:30 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/search/index.tsx
> +        ></InstantSearch>
Can this be self closing?

2022-11-08 08:35 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/AutoComplete/Autocomplete.tsx
> +            <div className="aa-ItemContent">
Are these our classnames or ones Algolia enforces? Would prefer them to be kebab-case if possible

2022-11-08 08:36 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/AutoComplete/Autocomplete.tsx
> +const ProductItem = ({ item, state }) => {
Don't think the state prop is being used? Can we remove it?

2022-11-08 08:40 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// import {
Can we delete this comment?

2022-11-08 08:45 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                <h1>
Can this be a h2 or a h3 if we reckon there will be a subheading above it? It's semantically incorrect to have multiple h1s on a page

2022-11-08 08:46 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                <div>
I think this should be a `p` or a `span` rather than a div

2022-11-08 08:46 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +            <div>
Do we need the div? Can we just have the `p` tags?

2022-11-08 08:47 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                                <a href="/">Home</a>
Presumably this is just a placeholder? Should we be using a remix `Link` instead?

2022-11-08 08:49 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                    <Tabs>
Do we need this?

2022-11-08 08:49 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// <InstantSearch
Can you delete this comment if it's not being used?

2022-11-08 08:52 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/NumericMenu/NumericMenu.tsx
> +export function NumericMenu(props: NumericMenuProps) {
Is this component being used anywhere? Not sure if I'm being blind but I can't see it in any of the other files?
Wondering if we need to have it?

2022-11-08 08:53 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/Refresh/refresh.scss
> +/* stylelint-disable plugin/selector-bem-pattern */
Is there a reason we've disabled the linting?

2022-11-08 08:56 UTC, stevenbister commented on packages/osc-ui/src/components/InstantSearch/cx.ts
> +export function cx(...classNames: Array<string | number | boolean | undefined | null>) {
This looks like quite a handy utility for other components. Perhaps it could sit in a utils folder or something outside of the instanstsearch stuff?

2022-11-08 08:58 UTC, stevenbister requested changes
Hey man I've given this a first sweep and it looks really good! I've left a few comments, some are just questions but a bit of tidying up needed I think

2022-11-08 10:04 UTC, mattwendzina commented on packages/osc-ui/src/components/InstantSearch/NumericMenu/NumericMenu.tsx
> +    const { hasNoResults, items, refine } = useNumericMenu(props);
In VS Code `hasNoResults` is crossed out because it is deprecated according the the TS file. The TS doc recommends using `canRefine` instead (connectNumericMenu.d.ts - line 59). 
(This is assuming we do need this component - ie steve's comment above).

2022-11-14 09:02 UTC, aaacafe786 commented on packages/osc-academic-hub/app/components/Search/instantSearch/InstantSearch.tsx
> +        ></OscInstantSearch>
done

2022-11-14 09:03 UTC, aaacafe786 commented on packages/osc-academic-hub/app/routes/search/index.tsx
> +        ></InstantSearch>
done

2022-11-14 09:05 UTC, aaacafe786 commented on packages/osc-ecommerce/app/components/Search/instantSearch/InstantSearch.tsx
> +        ></OscInstantSearch>
done

2022-11-14 09:08 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/AutoComplete/Autocomplete.tsx
> +            <div className="aa-ItemContent">
algolia enforced: https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-theme-classic/#templates

2022-11-14 09:10 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// import {
sound, list of component for reference: 
// import {
//     InstantSearch,
//     Breadcrumb,
//     Configure,
//     ClearRefinements,
//     CurrentRefinements,
//     HierarchicalMenu,
//     Highlight,
//     Hits,
//     HitsPerPage,
//     InfiniteHits,
//     Menu,
//     Pagination,
//     RangeInput,
//     RefinementList,
//     SearchBox,
//     SortBy,
//     ToggleRefinement,
//     InstantSearchSSRProvider
// } from 'react-instantsearch-hooks-web';

2022-11-14 09:12 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// import {
done

2022-11-14 09:37 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/NumericMenu/NumericMenu.tsx
> +    const { hasNoResults, items, refine } = useNumericMenu(props);
updated to canRefine

2022-11-14 09:38 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                <h1>
done

2022-11-14 09:47 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                <div>
done

2022-11-14 10:17 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                <ScrollTo className="m-auto flex max-w-6xl gap-4 p-4">
done

2022-11-14 10:21 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                    <Tabs>
done

2022-11-14 10:22 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/NumericMenu/NumericMenu.tsx
> +export function NumericMenu(props: NumericMenuProps) {
not sure, i added all the sub-components from the docs, will have to refer to @hi-im-si

2022-11-14 10:23 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/cx.ts
> +export function cx(...classNames: Array<string | number | boolean | undefined | null>) {
done

2022-11-14 10:24 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// <InstantSearch
done

2022-11-14 13:36 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +                                <a href="/">Home</a>
replaced with custom link function

2022-11-14 14:14 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/Refresh/refresh.scss
> +/* stylelint-disable plugin/selector-bem-pattern */
going to refactor all the styles in a future pr

2022-11-16 09:11 UTC, stevenbister commented
Looks like this needs rebasing @aaacafe786, there's still a bunch of Chakra stuff in here. You mind doing that? And I'll give it another look over

2022-11-17 09:07 UTC, stevenbister requested changes
Nice man, looking good! A few comments for you

Also I'm not sure if we need to add stories and tests for the algolia components in osc-ui? @hi-im-si might have some thoughts?

2022-11-17 09:07 UTC, stevenbister commented on packages/osc-ui/src/index.tsx
> +export { OscInstantSearch as InstantSearch } from './components/InstantSearch/InstantSearch';
Can we put this in alphabetical order please?

If you set this in vscode https://discord.com/channels/915621085872029817/916253090552881153/1040286500518117416 it'll automatically do it when you save :)

2022-11-17 09:07 UTC, stevenbister commented on packages/osc-ui/src/utils/cx.ts
> +export function cx(...classNames: Array<string | number | boolean | undefined | null>) {
Can probably replace this with the classNames file now (osc-ui/src/utils/classNames.ts)

2023-02-24 16:02 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/AutoComplete/constants.ts
> +export const INSTANT_SEARCH_QUERY_SUGGESTIONS = 'dev_shopify_query_suggestions_1';
done

2023-02-24 16:02 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/InstantSearch.tsx
> +// import { QueryRuleCustomData } from './QueryRule/QueryRuleCustomData';
done

2023-02-24 16:02 UTC, aaacafe786 commented on packages/osc-ui/src/index.tsx
> +export { OscInstantSearch as InstantSearch } from './components/InstantSearch/InstantSearch';
done

2023-02-24 16:05 UTC, aaacafe786 commented on packages/osc-ui/src/utils/cx.ts
> +export function cx(...classNames: Array<string | number | boolean | undefined | null>) {
done

2023-02-24 16:12 UTC, aaacafe786 commented on packages/osc-academic-hub/app/routes/search/index.tsx
> +import instantSearchStyles from 'instantsearch.css/themes/satellite-min.css';
done

2023-02-24 16:13 UTC, aaacafe786 commented on packages/osc-ecommerce/app/routes/search/index.tsx
> +import instantSearchStyles from 'instantsearch.css/themes/satellite-min.css';
done

2023-02-24 16:15 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/Tabs/Tabs.tsx
> +                        const isSelected = currentTab === index;
this will probably need a small pr in order to decouple the tabs from instant search and use our own

2023-02-24 16:16 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/Tabs/tabs.scss
> +}
need to resolve all the external css in a new pr

2023-02-24 16:16 UTC, aaacafe786 commented on packages/osc-ui/src/components/InstantSearch/Tabs/tabs.scss
> +}
i have left // TODO AK in all the relevant files

2023-02-24 16:39 UTC, closed without merging