fix: inital commit
Open-Study-College/osc pull request #540
Opened 2022-11-07 21:05 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-11-21 10:25 UTC, stevenbister requested changes
Hey man, looks good! A few comments and questions for ya

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Card/Card.tsx
> +export const CardHeader = (props) => {
Missing some typescript stuff

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Card/Card.tsx
> +export const CardBody = (props) => {
Missing some typescript stuff

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Card/Card.tsx
> +export const CardFooter = (props) => {
Missing some typescript stuff

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +    title: 'osc-ui/Card Carousel',
I think this should still be called just Carousel, perhaps we should add some stories to showcase it with different content? Cards/just images etc.

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +export const VerticalOneSlide = Template.bind({});
Are we keeping vertical carousel? I thought we weren't gonna be using it?

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +    .embla__viewport {
Are these `.embla` classnames generated by embla or can we rename them something like `c-carousel__viewport` etc?

2022-11-21 10:25 UTC, stevenbister commented on packages/osc-ui/src/index.tsx
> +export { Card, CardHeader, CardBody, CardFooter } from './components/Card/Card';
Can we put this in alphabetical order please?

If you set this in vscode https://discord.com/channels/915621085872029817/916253090552881153/1040286500518117416 it'll automatically do it when you save :)

2022-11-21 11:07 UTC, aaacafe786 commented on packages/osc-ecommerce/app/components/Cards/Cards.tsx
> +            active={module.carouselOptions.active} // fine
resolved

2022-11-21 11:20 UTC, aaacafe786 commented on packages/osc-ecommerce/app/components/Module.tsx
> +            if (moduleCard.layout === 'grid') {
resolved

2022-11-21 11:22 UTC, aaacafe786 commented on packages/osc-ui/src/index.tsx
> +export { Card, CardHeader, CardBody, CardFooter } from './components/Card/Card';
resolved and nice tip

2022-11-21 22:37 UTC, hi-im-si reviewed
Aside from the comments, having reviewed the [deploy link](https://pr-540-osc-ecommerce.fly.dev/kitchen-sink) I am unable to see the Cards working with the Grid layout - selecting this option does not output any cards in the DOM

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +    .embla__viewport {
agree. we should be sub-classing everything and avoiding the embla class names

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +export const VerticalOneSlide = Template.bind({});
I think we need to ditch it 👍🏼

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/card.scss
> +    .c-card-body {
```suggestion
    &__body {
```

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/card.scss
> +    .c-card-footer {
```suggestion
    &__footer {
```

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/card.scss
> +        color: var(--colour-primary);
i think until we see what the cards actually look like visually then we should keep this file very basic

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ui/src/components/Card/Card.stories.tsx
> +                    }}
Is there a specific reason for choosing to use inline styles of the main card.scss?

2022-11-21 22:37 UTC, hi-im-si commented on packages/osc-ecommerce/app/components/Module.tsx
> +                console.log(moduleCard);
remove `console.log`

2022-11-21 22:38 UTC, hi-im-si requested changes
see previous comments

2022-11-22 14:24 UTC, aaacafe786 commented on packages/osc-ecommerce/app/root.tsx
> +        { rel: 'stylesheet', href: oscUiCardStyles },
done

2022-11-22 14:35 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +    title: 'osc-ui/Card Carousel',
done

2022-11-22 14:36 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +export const VerticalOneSlide = Template.bind({});
ive disabled the vertical option for now

2022-11-22 14:40 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +    title: 'osc-ui/Card Carousel',
unfortunately, i think we need the classnames for the carousel to function

2022-11-22 14:41 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +    .embla__viewport {
i think we need embla classes to function, eg embla__slide

2022-11-22 14:48 UTC, aaacafe786 commented on packages/osc-ui/src/components/Card/card.scss
> +    .c-card-body {
done

2022-11-22 14:49 UTC, aaacafe786 commented on packages/osc-ui/src/components/Card/card.scss
> +    .c-card-footer {
done

2022-11-22 15:20 UTC, aaacafe786 commented on packages/osc-ui/src/components/Card/Card.stories.tsx
> +                    }}
its just a container to hold the card, not part of the actual card component

2022-11-22 15:20 UTC, aaacafe786 commented on packages/osc-ecommerce/app/components/Module.tsx
> +                console.log(moduleCard);
done

2022-11-23 09:05 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +    .embla__viewport {
I think it's fine to keep the classes in the markup (and maybe add a comment as to why they're there) but maybe add the `c-carousel` subclasses to handle the styling

2022-11-23 09:07 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +    title: 'osc-ui/Card Carousel',
Don't think this is done mate?

2022-11-23 09:08 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +export const VerticalOneSlide = Template.bind({});
Do you mean it's been disabled in Studio? Can we take it out of storybook as well?

2022-11-23 11:43 UTC, aaacafe786 commented on packages/osc-ecommerce/app/components/Cards/Cards.tsx
> +                                      quia quo iure vero. Blanditiis error perspiciatis aperiam
done

2022-12-15 12:40 UTC, closed without merging

2022-12-15 12:41 UTC, hi-im-si commented
Referring to @aaacafe786 confirmation that this PR can be closed without merging