Docs/Add documentation to storybook
Open-Study-College/osc pull request #558
Opened 2022-11-15 16:43 UTC by stevenbister

- Closes #552 

## 📝 Description

I've added some more details into the components in Storybook. Includes a sentence on what the component is and I've added a description to each of the props in the table.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

More detail in Storybook

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

I've only done this for existing Stories. It will be down to the owner of the component to add their own details in when building their stories.

2022-11-15 16:59 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +        },
```suggestion
        hideFooterCloseButton: {
            description: 'Sets whether or not to prevent rendering of the close button in the footer'
        },
```

Would `render` be a better term than `hide`? hide to me implies the button is there but perhaps with `display: none;` and could still be clicked programatically?

2022-11-15 16:59 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +        },
```suggestion
        hideHeaderCloseButton: {
            description: 'Sets whether or not to prevent rendering of the close button in the header'
        },
```

Would `render` be a better term than `hide`? hide to me implies the button is there but perhaps with `display: none;` and could still be clicked programatically?

2022-11-16 08:34 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +        },
Yeah that's a good point! I'll update it

2022-11-16 08:34 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +        },
Yeah that's a good point! I'll update it

2022-11-16 11:47 UTC, mattwendzina commented on packages/osc-academic-hub/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
> +            description: 'Conrol that handles toggling the switch'
Typo- *Control

2022-11-16 11:48 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
> +            description: 'Conrol that handles toggling the switch'
Same as above

2022-11-16 11:54 UTC, mattwendzina commented on packages/osc-ui/src/components/Breadcrumb/Breadcrumb.stories.tsx
> +            description: 'Custom sparator, can be a string or a component'
typo- *separator

2022-11-16 11:56 UTC, mattwendzina commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +                    'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.'
Is this supposed to say `inert`?

2022-11-16 12:02 UTC, mattwendzina commented on packages/osc-ui/src/components/Tabs/Tabs.stories.tsx
> +                    'A set of layered sections of content—known as tab panels—that are displayed one at a time.'
I'd personally put a space in between hyphens unless they're meant to be concatenated as I think it's clearer to read.
e.g. `content - known...` and `panels - that...`

2022-11-16 12:03 UTC, mattwendzina commented
Nice mate. Left a few comments mainly on typos, but other than that LGTM!

2022-11-17 10:00 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +                    'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.'
Yeah, do you think it should say something else?

2022-11-17 10:08 UTC, stevenbister commented on packages/osc-academic-hub/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
> +            description: 'Conrol that handles toggling the switch'
Sorted

2022-11-17 10:08 UTC, stevenbister commented on packages/osc-ecommerce/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
> +            description: 'Conrol that handles toggling the switch'
Sorted

2022-11-17 10:08 UTC, stevenbister commented on packages/osc-ui/src/components/Breadcrumb/Breadcrumb.stories.tsx
> +            description: 'Custom sparator, can be a string or a component'
Sorted

2022-11-17 10:08 UTC, stevenbister commented on packages/osc-ui/src/components/Tabs/Tabs.stories.tsx
> +                    'A set of layered sections of content—known as tab panels—that are displayed one at a time.'
Fair point, sorted

2022-11-17 10:09 UTC, stevenbister commented
Thanks @mattwendzina! You'll be pleased to know I've now installed this https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker 😂

2022-11-17 10:10 UTC, mattwendzina commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +                    'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.'
I'm just not sure what it means by:
`... rendering the content underneath inert`

2022-11-17 10:14 UTC, mattwendzina commented
> Thanks @mattwendzina! You'll be pleased to know I've now installed this https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker 😂

Haha, that's a good shout actually think I'll do the same 😄

2022-11-17 10:20 UTC, stevenbister commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +                    'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.'
Ah right, just that it's inaccessible: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

2022-11-17 10:24 UTC, mattwendzina commented on packages/osc-ui/src/components/Modal/Modal.stories.tsx
> +                    'A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.'
Ah, right got it! Cool, all good then 😎

2022-11-22 10:45 UTC, hi-im-si requested changes
We should probably define defaults for each action/prop e.g.
![image](https://user-images.githubusercontent.com/1517907/203294448-c380a74c-145f-44ac-ad99-3dfd73c29a68.png)

2022-12-05 16:18 UTC, hi-im-si approved these changes
🚀

2022-12-05 16:18 UTC, merged