test: add tests for Avatar component
Open-Study-College/osc pull request #560
Opened 2022-11-16 09:46 UTC by mattwendzina

Closes #539 

## 📝 Description

Adds tests for Avatar component

## ⛳️ Current behavior (updates)

No testing

## 🚀 New behavior

Adds tests

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2022-11-16 10:14 UTC, stevenbister commented on packages/osc-ui/src/components/Avatar/Avatar.spec.tsx
> +    const initial = NAME.charAt(0);
Ha this is way better than I did it in the component itself 😂 Completely forgot about `charAt()`

2022-11-16 10:16 UTC, stevenbister commented on packages/osc-ui/src/components/Avatar/Avatar.spec.tsx
> +describe('Avatar component', () => {
Do we need the describe block if we're grouping everything into it?

2022-11-16 10:18 UTC, mattwendzina commented on packages/osc-ui/src/components/Avatar/Avatar.spec.tsx
> +describe('Avatar component', () => {
I've tended to always use a describe block to group all tests for a given component, just from the conventions in the way I learnt, but not too fussed. If there were other specific groups I would wrap them in another describe, but I'm easy either way.

2022-11-17 08:34 UTC, stevenbister commented on packages/osc-ui/src/components/Avatar/Avatar.spec.tsx
> +describe('Avatar component', () => {
Yeah not a big deal, just curious. I've tended not to unless I'm grouping tests as the filename is included in the test runs e.g.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/23461173/202396440-0d82f637-7747-44e7-b318-7647c7e0c338.png">

But yeah no biggie

2022-11-17 08:35 UTC, stevenbister approved these changes
LGTM!

2022-11-22 12:24 UTC, hi-im-si requested changes

2022-11-29 09:05 UTC, mattwendzina commented
Now displays full initials @hi-im-si 👍

2022-12-05 11:11 UTC, hi-im-si approved these changes
LGTM 🚀

2022-12-13 13:00 UTC, merged