Feature/accordion component
Open-Study-College/osc pull request #565
Opened 2022-11-18 11:47 UTC by stevenbister

- Closes #451 
- Closes #452 
- Closes #453 

## 📝 Description

Adds an accordion component to `osc-ui` & `osc-ecommerce` with controls in `osc-studio`

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

As well as the accordion component in `osc-ui` I've added a "composite" or "[organism](https://bradfrost.com/blog/post/atomic-web-design/#organisms)"  component to `osc-ecommerce` called `Accordion`. This is wrapped in an `<article>`, passes the `<Content />` component and includes the controlled aspects from `osc-studio`.

I've also refactored the `<Content />` component slightly so now it doesn't include the `<article>` tag within it, instead (where appropriate) it should be wrapped. I found that including it in this component caused a case where each accordion panel would be an article which in turn would be nested the parent article -- felt a bit messy and I don't think it's valid. So I've refactored it down into a singular `c-content` `div` which should give the component a bit more flexibility in where it is used. 

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

I've updated the storybook to include details on the props. The majority of them come from Radix so you won't necessarily see them individually defined in the component but they will pass through the `{...props}` instead.
Finally I don't believe there is a way to add the `argTypes` to subcomponents, so although they are listed in the storybook the tables might look a little bare :(

2022-11-18 15:48 UTC, aaacafe786 commented
hey, might want to duplicate the composite component in osc-academic hub

2022-11-22 13:01 UTC, hi-im-si requested changes
Getting a error in Sanity.
![image](https://user-images.githubusercontent.com/1517907/203319893-e2529aab-5e08-41a5-98a6-8af17f78ddf1.png)
All possible content fields have been updated but still receive the error

2022-11-22 14:19 UTC, stevenbister commented
@hi-im-si 

https://user-images.githubusercontent.com/23461173/203337234-4aabae0d-c825-41af-8526-c24a8a4d5de7.mov

2022-12-22 14:27 UTC, hi-im-si requested changes
Requested changes are so minor - looking tidy :)

2022-12-22 14:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +            letter-spacing: 0.188em;
Ideally should be using a design token for `letter-spacing`

2022-12-22 14:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +        --accordion-trigger-font-size: #{rem(24)}; // design has this fixed across breakpoints
Just a thought but would it be worth calculating the value of this from the base-font-size?
```suggestion
        --accordion-trigger-font-size: #{rem(($base-font-size * 0.75) * 2)}
```

2022-12-22 14:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +            background-color: hsl(0deg 0% 96% / 100%);
guessing we should be pulling this colour from our colour variables. think this would be `soft-grey` in our colour library but as we discussed, we need to bring in these neutral colours into our design tokens

2022-12-23 08:52 UTC, stevenbister commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +        --accordion-trigger-font-size: #{rem(24)}; // design has this fixed across breakpoints
Ooo yeah that's a good shout

2022-12-23 08:52 UTC, stevenbister commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +            background-color: hsl(0deg 0% 96% / 100%);
Yeah I agree, I'll add a TODO here to update it once the new neutral colours have been added

2022-12-23 08:53 UTC, stevenbister commented on packages/osc-ui/src/components/Accordion/accordion.scss
> +        }
Yeah happy to swap it over, I'm personally not too bothered by either

2023-01-05 16:53 UTC, merged