Feature/popover component
Open-Study-College/osc pull request #571
Opened 2022-11-21 16:06 UTC by mattwendzina

Closes #536 
Closes #537 

## 📝 Description

Add Popover Component

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Adds a Popover component to the UI Library

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
The Popover component can be composed of many parts. I haven't abstracted any of this into the component itself (e.g. Close button in content, Arrow in component), but just exported each of the composable parts so they can be custom built. The stories give examples of how the Popover can be composed of these different parts.

A [polyfill](https://www.npmjs.com/package/resize-observer-polyfill) has been added to deal with a testing issue. More details can be found [here](https://discord.com/channels/915621085872029817/1044285090601127989).

2022-11-22 08:45 UTC, stevenbister commented
@mattwendzina Vitest and Chromatic are failing, looks like `@radix-ui/react-popover` is missing from the package.json

2022-11-22 08:52 UTC, mattwendzina commented
> @mattwendzina Vitest and Chromatic are failing, looks like `@radix-ui/react-popover` is missing from the package.json

Oops, my bad! Just added in = )

2022-11-22 14:46 UTC, stevenbister requested changes
Looks good man, got a few comments for ya

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +        <PopoverAnchor
Think it's worth styling the anchor a little differently? If you view the docs part of Storybook then it appears in the middle of the page, rather than within the "story" part.

It might be good to illustrate how this might actually be used? Maybe make the anchor a row or some kind of visible element?

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +    parameters: {
Would be good to include the subcomponents here like this:
```ts
component: Popover,
subcomponents: {PopoverAnchor, ...}
```
You won't be able to directly add args (open issue here https://github.com/storybookjs/storybook/issues/14710) but it will pickup some of them from the types/the stories. And I think it's good to illustrate what components are related at the very least.

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +        }
Would be good to add the argsTable to this. I know you're not adding any custom props but taking the ones [from here](https://www.radix-ui.com/docs/primitives/components/popover#root) will mean we don't have to go searching too much for them

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +export const WithAnchor = TemplateFive.bind({});
Perhaps the WithAnchor story could have a description with it so it's a little clearer as to what it's doing?
```ts
WithAnchor.parameters = {
    docs: {
        source: {
            story: 'blah blah blah'
        }
    }
};
```

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__content:focus {
You can nest the focus inside the `&__content` selector above, looks like that's the convention we've been doing on other components so far

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__close:hover {
Same as before about the nesting

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__close:focus {
Same as before about the nesting

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__icon-button:hover {
Same as before about the nesting

2022-11-22 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__icon-button:focus {
Same as before about the nesting

2022-11-22 14:48 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +    parameters: {
For reference this is what it does
![image](https://user-images.githubusercontent.com/23461173/203344056-d65d25c4-cb96-45fa-88b8-d640e410a330.png)

![image](https://user-images.githubusercontent.com/23461173/203344113-eb971a8a-8251-4fac-93ad-0dabbb2c7f9f.png)

2022-11-22 16:25 UTC, hi-im-si requested changes
@mattwendzina Any specific reason for omitting the ability to pass props for things like text displayed for the `PopoverTrigger` and `PopoverContent`? It would be good to display controls in Storybook

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__close:hover {
Done

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__close:focus {
Done

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__icon-button:hover {
Done

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__icon-button:focus {
Done

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +export const WithAnchor = TemplateFive.bind({});
Done

2022-11-28 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +        }
Done

2022-11-28 17:52 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +    parameters: {
I've added in subcomponents, but it doesn't work great because of this issue you mentioned.

2022-11-28 17:52 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +        <PopoverAnchor
I've updated - hopefully this makes it clearer?

2022-11-28 17:54 UTC, mattwendzina commented
> @mattwendzina Any specific reason for omitting the ability to pass props for things like text displayed for the `PopoverTrigger` and `PopoverContent`? It would be good to display controls in Storybook

I followed the documentation which makes the component for composable by passing each component in. I've refactored to use children as a prop in the stories - this means you can control the content in `PopoverTrigger` and `PopoverContent`. Is this what you meant?

2022-11-29 08:37 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/Popover.stories.tsx
> +        <PopoverAnchor
Yep! Exactly what I was thinking :D

2022-11-29 08:39 UTC, mattwendzina commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__content:focus {
Done

2022-11-29 08:40 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +    &__content:focus {
Noice

2022-11-29 08:54 UTC, stevenbister approved these changes
LGTM!

2022-11-30 11:30 UTC, merged