Feature/keen slider
Open-Study-College/osc pull request #573
Opened 2022-11-23 22:40 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2022-12-05 17:50 UTC, stevenbister requested changes
Hi mate, left a few comments for you. I think this can be simplified a lot if we lean more into what Keen Slider gives us. I've not reviewed your tests, Sanity or storybook in this instance I tried to focus on just the component itself. Hopefully my comments make sense!

A couple of other general things:

There are a few things in here that should be separate PRs which is making reviewing a bit hard as it's hard to tell what's required for the carousel and what's needed for something else.

Also can you add more detailed comments throughout your code. It's really helpful to not just state what something is but to maybe also explain _why_ something is done in that way. For example why you're doing the adaptive height in one way whereas Keen give an example with a different implementation that doesn't need a resize observer.
There is also some quite complex logic in some if statements that would benefit from a comment above it explaining in english what is happening.

2022-12-05 17:50 UTC, stevenbister commented on .github/actions/deployment/action.yml
> +      if: ${{ env.PR_CLOSED != 'true' }}
This ideally should be in a different PR

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ecommerce/app/root.tsx
> +    // add comment to deploy
What's this?

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-studio/utils/joinWithAnd.ts
> +export const joinWithAnd = (list: string[]) => {
What is this? I know I added it to an unmerged PR but don't think it's being used in here? Can you remove if not

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-studio/tsconfig.json
> +    "target": "ES2021",
What is this? I know I added it to an unmerged PR but don't think it's being used in here? Can you remove if not

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        const observer = new ResizeObserver(function () {
See my comments around `trueSlidesPerPage` and `updateHeight` we might be able to remove this resize observer

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +.keen-slide1 {
Presume these are just here for testing?

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +    outline: none;
Please don't remove the focus outlines from things as it's an accessibility issue. If you don't want to see it when you use your mouse use `focus-visible` instead

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +            drag: indicatorActive || dotsActive,
This should be true by default, we would always expect the slider to be dragable
```suggestion
            drag: true,
```

2022-12-05 17:50 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +            dragSpeed: 0,
Do we need this? The default is 1 so not sure why you've set it to 0 here?

2022-12-06 08:47 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                (slide) => (slide as any).children[0].getBoundingClientRect().height
please try this out before dropping it, i could not get the intended behaviour to work with the default

2022-12-06 08:51 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
hey man, i think it needs an empty div to function, please test this out before dropping it

2022-12-06 09:00 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
not lazy loading slides means that you can end up loading all the slides in the carousel regardless of how large it is, the following ternary means: if the index is between the slidesInView (array) +/- trueSlidesPerPage (sorry, i know you dont like this, maybe there is an alternative), render the content of the slide in the dom otherwise render and empty div

2022-12-06 09:04 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        if (window.matchMedia('(max-width: 640px)').matches) return 0;
they also expose a prop called portion on each slide, it allows you to calculate all the slides in view, might be an easy replacement
```    
const slidesInView = (slider) => {
        const loadedSlides = slider.track.details.slides.map((slide, idx) => {
            if (slide.portion > 0) {
                return true;
            } else {
                return false;
            }
        });
        return loadedSlides;
    };
```

2022-12-06 09:14 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
the reason it's not just slides in view, is because you can move up-to the number of slides per page in one swipe on desktop and these images need to be preloaded

2022-12-06 09:19 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        if (window.matchMedia('(max-width: 640px)').matches) return 0;
you will still need the observer incase the page is resized, keep this as a minimum: https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/resize/react-typescript?file=/src/App.tsx

2022-12-06 09:23 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +            dragSpeed: 0,
nah, this can go

2022-12-06 09:24 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +.keen-slide1 {
yeah, came with the default keen slider setup

2022-12-06 09:49 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
We shouldn't be lazy loading the entire slide or it's content. The images in the slide yes, but lazy loading the slide itself or the content inside it will remove it from the DOM. This means the content won't exist for things like screen readers or search engines, which require the content to exist for them to function/rank our site.

2022-12-06 09:50 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
you would need to extract all the images from the child of carousel

2022-12-06 09:51 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
plus, there is an aria-hidden attribute which states that the slide is not in view, they can still click the button right

2022-12-06 09:52 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        if (window.matchMedia('(max-width: 640px)').matches) return 0;
But we're not resizing the slider in that way? If you use the `maxId` property then it automatically updates with the breakpoints, which should be handling the page resizing

2022-12-06 09:59 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
You _should_ be able to use the native image lazy loading so you wouldn't need to do that, and again the way Keen works is it removes it from the DOM which isn't really ideal.

Yeah they should still be able to click the button but search engines can't do that so it needs to exist, whether the aria attribute exists or not

2022-12-06 10:24 UTC, aaacafe786 commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
im pretty curious how exactly does a larger amount of slides improve the SEO score, i looked about and couldn't find anything very convincing for either side, lighthouse/webpagetest does not complain about it

2022-12-06 10:36 UTC, stevenbister commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +                    {React.Children?.map(children, (q, index) => {
It's got nothing to do with lighthouse -- it's about how Google works. Crawlers need to be able to parse the content and follow links, if the content isn't there they can't crawl the site fully and therefore can't rank us correctly. It's the same reason you need to prerender your site if you're using an SPA.

2022-12-06 17:20 UTC, mattwendzina commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        console.log('this is the new slides in view', loadedSlides);
Are these console logs needed now?

2022-12-06 17:20 UTC, mattwendzina commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        console.log('this is the new slides in view', loadedSlides);
Same as above comment on console logs

2022-12-06 17:23 UTC, mattwendzina commented
Having had a look at the carousel in Storybooks it looks like the arrows could do with some conditional styling to disable/grey out when it's at the end of the carousel deck. Or when it gets to the end it goes back to the start on the next click.
Perhaps the styling is out of the remit for getting this in now though so ignore if that's the case..!

2022-12-06 17:27 UTC, mattwendzina commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +        // }
Is there a reason this code is commented out or can it be deleted?

2022-12-06 17:39 UTC, mattwendzina commented
Bit confused as it looks like the `Card` component is in this PR as well as the Carousel. Are they going in together under the same PR?

2023-01-26 12:11 UTC, closed without merging