Feature/ecommerce api
Open-Study-College/osc pull request #629
Opened 2022-12-06 15:26 UTC by Tom-Pearce

- Closes #504 
- Closes #505  
- Closes #506 
- Closes #507 
- Closes #508 
- Closes #509 
- Closes #510 

## 📝 Description

First iteration of the Ecommerce API

## ⛳️ Current behavior (updates)

None

## 🚀 New behavior

Connects to Shopify and Algolia, making the API SDKs available via Apollo's context.
Able to query a basic products endpoint via the gateway

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
Also includes a refactor of the gateway to account for the new `OSC-API` utility package.

2022-12-06 16:48 UTC, hi-im-si requested changes
Do we need to keep the shape of the data that is in algolia for the shopify products e.g.
```
{
  "hits": [
    {
      "title": "Edexcel Functional Skills Maths Level 2",
      "updated_at": "2021-11-09T00:02:21.000Z",
      "_tags": [
        "id:7438721679615",
        "indexing_token:513bf011106517fae5bb8ca7daaef89b"
      ],
      "handle": "functional-skills-maths-level-2",
      "vendor": "openstudydev",
      "product_type": "",
      "template_suffix": null,
      "sku": "OSC1373",
      "barcode": null,
      "position": 1,
      "requires_shipping": true,
      "taxable": true,
      "inventory_quantity": 0,
      "option1": "Course Material",
      "option2": "Online",
      "option3": null,
      "id": 7438721679615,
      "tags": [
        "import_2021_11_08_234706",
        "Mathematics & Economics"
      ],
      "option_names": [
        "format",
        "study-method"
      ],
      "variants_count": 4,
      "variants_min_price": 369,
      "variants_max_price": 569,
      "variants_inventory_count": 0,
      "product_image": "https://cdn.shopify.com/s/files/1/0609/0519/3727/products/OSC1332-e1584960693138_7b7080af-f545-4853-b607-a1a345526c83.jpg?v=1636416540",
      "published_at": "2021-11-09T00:14:37.000Z",
      "body_html_safe": null,
      "variant_title": "Course Material / Online",
      "inventory_policy": "deny",
      "inventory_management": "shopify",
      "inventory_management_shopify": 1,
      "inventory_available": false,
      "options": {
        "format": "Course Material",
        "study-method": "Online"
      },
      "price": 369,
      "compare_at_price": 0,
      "price_ratio": 0,
.........
..........
........
}
```
or we just doing a basic initial schema?

2022-12-07 09:29 UTC, Tom-Pearce commented on packages/osc-api-ecommerce/src/types/functions.ts
> +
I can remove it but probably end up creating it again as soon as we build any functionality out.

2022-12-07 09:33 UTC, Tom-Pearce commented
> Do we need to keep the shape of the data that is in algolia for the shopify products e.g.
> 
> ```
> {
>   "hits": [
>     {
>       "title": "Edexcel Functional Skills Maths Level 2",
>       "updated_at": "2021-11-09T00:02:21.000Z",
>       "_tags": [
>         "id:7438721679615",
>         "indexing_token:513bf011106517fae5bb8ca7daaef89b"
>       ],
>       "handle": "functional-skills-maths-level-2",
>       "vendor": "openstudydev",
>       "product_type": "",
>       "template_suffix": null,
>       "sku": "OSC1373",
>       "barcode": null,
>       "position": 1,
>       "requires_shipping": true,
>       "taxable": true,
>       "inventory_quantity": 0,
>       "option1": "Course Material",
>       "option2": "Online",
>       "option3": null,
>       "id": 7438721679615,
>       "tags": [
>         "import_2021_11_08_234706",
>         "Mathematics & Economics"
>       ],
>       "option_names": [
>         "format",
>         "study-method"
>       ],
>       "variants_count": 4,
>       "variants_min_price": 369,
>       "variants_max_price": 569,
>       "variants_inventory_count": 0,
>       "product_image": "https://cdn.shopify.com/s/files/1/0609/0519/3727/products/OSC1332-e1584960693138_7b7080af-f545-4853-b607-a1a345526c83.jpg?v=1636416540",
>       "published_at": "2021-11-09T00:14:37.000Z",
>       "body_html_safe": null,
>       "variant_title": "Course Material / Online",
>       "inventory_policy": "deny",
>       "inventory_management": "shopify",
>       "inventory_management_shopify": 1,
>       "inventory_available": false,
>       "options": {
>         "format": "Course Material",
>         "study-method": "Online"
>       },
>       "price": 369,
>       "compare_at_price": 0,
>       "price_ratio": 0,
> .........
> ..........
> ........
> }
> ```
> 
> or we just doing a basic initial schema?

I'm only exposing data that's getting used. I.e. if it's not being exposed in our GraphQL schema I'm not adding it to the internal types to keep it leaner. If new fields are added they can be added to both places as and when they're needed. Could probably do something fancy to make the types more dynamic, but that's something to look into in the future I think. Unlike Prisma, you don't get a unique client that fully typed based on your data unfortunately.

2022-12-08 08:44 UTC, stevenbister commented
Can't comment too heavily but looks good! Do we need to include any tests?

2022-12-15 13:03 UTC, merged