Feature/dropdown menu
Open-Study-College/osc pull request #630
Opened 2022-12-06 17:11 UTC by mattwendzina

Closes #534 
Closes #535 

## 📝 Description

Add Dropdown Menu component

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Dropdown menu component added

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2022-12-07 09:13 UTC, stevenbister requested changes
Would it be possible to change the functionality of the checkbox and radio options slightly? 

I don't really like how it closes the menu when you select something. I would expect to see the UI update so I know what I have selected and for checkboxes I might want to select multiple options -- having to click back into the menu each time is kinda annoying.

It looks like there's an onSelect prop for the DropdownMenuItem that if you pass `e.preventDefault()` to will prevent this behaviour
https://www.radix-ui.com/docs/primitives/components/dropdown-menu#item

2022-12-09 09:13 UTC, mattwendzina commented on packages/osc-ui/src/components/DropdownMenu/DropdownMenu.spec.tsx
> + */
Done 👍

2022-12-09 10:07 UTC, mattwendzina commented
> Would it be possible to change the functionality of the checkbox and radio options slightly?
> 
> I don't really like how it closes the menu when you select something. I would expect to see the UI update so I know what I have selected and for checkboxes I might want to select multiple options -- having to click back into the menu each time is kinda annoying.
> 
> It looks like there's an onSelect prop for the DropdownMenuItem that if you pass `e.preventDefault()` to will prevent this behaviour https://www.radix-ui.com/docs/primitives/components/dropdown-menu#item

Good idea. Added this in and seems to work fine 👍

2022-12-12 11:27 UTC, stevenbister approved these changes
I'm happy with that 😄

2022-12-13 10:35 UTC, hi-im-si approved these changes

2022-12-13 10:36 UTC, merged