Refactor/carousel from embla to keen
Open-Study-College/osc pull request #631
Opened 2022-12-08 16:16 UTC by stevenbister

- Closes #227 

## 📝 Description

Refactors carousel component from Embla to Keen Slider

## ⛳️ Current behavior (updates)

Current carousel depends on [Embla Carousel](https://www.embla-carousel.com/)

## 🚀 New behavior

New carousel depends on [Keen Slider](https://keen-slider.io/)

Tests and stories have been updated to reflect these new props. 

## 💣 Is this a breaking change (Yes/No): Yes

I have updated the Sanity schema but I **have not** updates the queries into `ecommerce` in this PR as they will be more related to elements like the cards(https://github.com/Open-Study-College/osc/pull/540) or the hero which will depend on this component -- so it felt out of scope for this PR, especially if we'll be updating the usage of the schema anyway.

## 📝 Additional Information
https://keen-slider.io/docs

2022-12-12 11:45 UTC, mattwendzina approved these changes
LGTM

2022-12-14 17:28 UTC, hi-im-si requested changes

2022-12-14 17:28 UTC, hi-im-si commented on packages/osc-studio/schemas/objects/module/carousel.ts
> +            group: 'settings',
is it worth adding a conditional to only allow the autoplay settings IF loop has been set as true?

`hidden: ({ parent }) => parent?.loop !== true`

just means there is no need to add the extra blurb to remind the editor to enable 'loop'

2022-12-14 17:28 UTC, hi-im-si commented on packages/osc-studio/schemas/objects/module/carousel.ts
> +                    type: 'number',
as a just in case it would be worth providing a description as to what these fields are doing and what breakpoint they use - this information can be pulled from our mq tokens

2022-12-14 17:28 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
> +            },
pull these media query breakpoints from our media query tokens

2022-12-14 17:28 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/Carousel.tsx
> +            },
pull these media query breakpoints from our media query tokens

2022-12-14 21:01 UTC, aaacafe786 commented
lgtm

2022-12-15 12:38 UTC, hi-im-si approved these changes
🚀

2022-12-15 12:39 UTC, merged