Feature/button styles
Open-Study-College/osc pull request #636
Opened 2022-12-12 11:39 UTC by stevenbister

- Closes #598 
- Closes #217 

## 📝 Description

Adds the styles for the button variations.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

Adds the styles for the button variations. 
Part of this includes adding a couple of new colour tokens as well as a light font weight to the typography tokens. 
I have added a `forwardRef` to the button component here as I realised it was needed, I also ended up using it myself to set a `min-width` on the `CopyButton` so the button doesn't collapse when the `innerText` changes.

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

There is currently a small bug in running storybook due to a font alias not being found. Matt has added a fix to his [PR here](https://github.com/Open-Study-College/osc/pull/630) so I've left it out of this one.

To view the buttons for now you will need to pull this down, move the fonts out of the ImageGallery component and put them into the `fonts` directory before running `npm run storybook`

2022-12-22 14:27 UTC, hi-im-si commented
Looks like before we can close this, there are now a few more variations on the button component

2022-12-23 08:49 UTC, stevenbister commented
> Looks like before we can close this, there are now a few more variations on the button component

Sure, I'll have a look at getting these added to this PR. 

Any thoughts on naming for them? I think we're up to octonary already, shall I just continue with that sequence? 
But then these new ones would be the "primary" button on the academic hub :S

2023-01-05 14:49 UTC, stevenbister commented
Gonna set this to draft for the time being until Amy has consolidated the buttons

2023-01-27 09:04 UTC, hi-im-si requested changes

2023-01-27 10:24 UTC, stevenbister commented on packages/osc-ecommerce/app/types/sanity.ts
> +        | 'octonary';
All done 👍

2023-01-27 10:24 UTC, stevenbister commented on packages/osc-studio/schemas/objects/module/button.ts
> +                    'octonary',
All done 👍

2023-01-27 10:28 UTC, merged