Feature/select component
Open-Study-College/osc pull request #647
Opened 2022-12-29 17:28 UTC by mattwendzina

Closes #613 
Closes Forms select (Ticket needs creating...)

## 📝 Description

Adds Radix Select component and styling and Label component

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Adds Select component

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2023-01-03 10:32 UTC, stevenbister requested changes
Hey man looking good! Left a few comments for you, appreciate these are fiddly components.

As you've mentioned the colours for greys/errors need adding to the tokens so I've not added comments around them. Just something for you to maybe note; we've decided to use `hsl` as the colour values rather than `hex` or `rgb` so if you can try using that instead that would be great.

Only other thing is you've not committed the package.json with the radix select icon installed :P

2023-01-03 10:32 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +                    <SelectPrimitive.Trigger
Unfortunately we're getting an a11y error in Storybook: `Element does not have inner text that is visible to screen readers`. Having a bit of a look under the hood this custom select is built on a `button` so the label isn't labelling it as you would expect.

It looks like we need to add an `aria-label` or perhaps `aria-lablledby` to this trigger element.

Alternatively it looks like Radix recommends using their `Label` component: https://www.radix-ui.com/docs/primitives/components/select#labelling 

Is there a reason we're not currently using that or is it planned for a separate PR?

2023-01-03 10:32 UTC, stevenbister commented on packages/osc-ui/src/components/Select/select.scss
> +            color: hsl(255deg 3.7% 78.8%);
Assuming these two values are to be updated to the tokens once we add the other greys in?

2023-01-03 10:32 UTC, stevenbister commented on packages/osc-ui/src/components/Select/select.scss
> +        box-shadow: 0 10px 38px -10px rgb(22 23 24 / 35%), 0 10px 20px -15px rgb(22 23 24 / 20%);
Can we update these rgb values to a token at all?

2023-01-03 10:32 UTC, stevenbister commented on packages/osc-ui/src/components/Select/select.scss
> +            width: 25px;
I would use an `em` value here so the icon scales with the font size

2023-01-03 10:32 UTC, stevenbister commented on packages/osc-ui/src/components/Select/select.scss
> +            background-color: var(--color-quinary);
Looks like these colour values get reused a few times here. Could we abstract them into a variable like I suggested with the label maybe?

2023-01-03 10:33 UTC, stevenbister commented on packages/osc-ui/src/components/Button/button.scss
> +    z-index: -1;
Or better yet I think there is a file in `styles/settings/_z-index` that you might be able to use

2023-01-05 11:48 UTC, mattwendzina commented on packages/osc-ui/src/components/Button/button.scss
> +    z-index: -1;
Updated

2023-01-05 11:48 UTC, mattwendzina commented on packages/osc-ui/src/components/Label/label.scss
> +    padding-left: 1px;
Done

2023-01-05 11:48 UTC, mattwendzina commented on packages/osc-ui/src/components/Label/label.scss
> +    font-size: var(--font-scale-centi);
Done

2023-01-05 11:48 UTC, mattwendzina commented on packages/osc-ui/src/components/Label/label.scss
> +.c-label__required {
Done

2023-01-06 10:50 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.stories.tsx
> +    argTypes: {},
Yeah my bad, meant to add this and forgot! Added now. Added the JS Docs too, this is a nice touch for the descriptions 👌

2023-01-06 15:58 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +                    <SelectPrimitive.Trigger
This is a bit tricky. I added the Radix label but this didn't solve the issue. I've added `aria-label` to `SelectPrimitive.Trigger` - which is the the button, and this has worked. I've just passed on the `name` - so when screen reading it starts with the name of the Select, e.g. 'Courses, required box pop-up etc...'

2023-01-06 15:58 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/select.scss
> +            color: hsl(255deg 3.7% 78.8%);
Yep

2023-01-06 16:03 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/select.scss
> +        box-shadow: 0 10px 38px -10px rgb(22 23 24 / 35%), 0 10px 20px -15px rgb(22 23 24 / 20%);
Yep, updated to the `shadow` color token.

2023-01-06 16:10 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/select.scss
> +            width: 25px;
Done

2023-01-06 16:17 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/select.scss
> +            background-color: var(--color-quinary);
Updated.

2023-01-09 09:49 UTC, stevenbister requested changes
Sorry, couple of other things I've noticed -- only minor

2023-01-09 09:49 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +        const setDescription = (desc: Props['description']) => {
Could this just be?
```suggestion
        const setDescription = (desc: Description) => {
```
As you've got a Description type set above

2023-01-09 09:49 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +    icon?: React.ReactNode;
Can you go through and remove this `React.`s? Just so it matches our other components

2023-01-09 09:49 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +export const SelectItem: FC<ItemProps> = React.forwardRef<
Might as well start dropping these `FC` types now. There's a PR waiting to go in https://github.com/Open-Study-College/osc/pull/649 to clean up the others so if we can start omitting them in new PRs that would be great :)

2023-01-10 10:18 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.spec.tsx
> +    ) as any;
I was having some issues  but those are sorted now so removed the type casting 👍

2023-01-10 10:20 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.spec.tsx
> +test('should render a select component', async () => {
Good point, nope! Removed.

2023-01-10 10:36 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +    icon: React.ReactNode;
Updated. I've made both optional as I think it's okay to have the Icon instead of the Label. It's an accessible Icon and it doesn't seem to cause any issues accessibility wise - still lists the name of the Select. Only thing is pressing the label doesn't open the Select... as far as I can see I've implemented this as per docs, so perhaps it doesn't operate like this for a Select. I personally don't think this is a problem given that a dropdown is a pretty big space to click anyway.

2023-01-10 10:38 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +        const setDescription = (desc: Props['description']) => {
Yeah good shout. Updated.

2023-01-10 10:41 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +export const SelectItem: FC<ItemProps> = React.forwardRef<
Done.

2023-01-10 10:46 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.tsx
> +    icon?: React.ReactNode;
Updated 👍

2023-01-11 09:13 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.tsx
> +    icon: React.ReactNode;
Cool! Yeah I think that's default for selects not to be opened when you click the label so that's all good

2023-01-11 09:17 UTC, stevenbister approved these changes
LGTM!

2023-01-12 14:00 UTC, hi-im-si requested changes
When you click on the label, it should focus the select to enable easy keyboard access for the user - can we apply this update

2023-02-14 18:43 UTC, merged