Feature/icons
Open-Study-College/osc pull request #648
Opened 2023-01-03 14:37 UTC by stevenbister

- Closes #633 
- Closes #246 

## 📝 Description

Adds an Icon component to `osc-ui` which references an icon from an external svg spritesheet. I've left the Sanity input side of things out of this PR to keep things a bit easier to review.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

I've added a custom rollup plugin which will optimise our svgs and generate a spritesheet for us to use. Simply add your Icon to the `osc-ui/src/icons` directory and run rollup (or a command that runs rollup e.g. `npm run storybook`). The rollup plugin will then read through that directory, optimise the svgs, replace any hex values with `currentColor` and move them into the `osc-ui/dist/spritesheet.svg`.

I've also updated the `remix.config` file in `osc-ecommerce` so it will bundle svgs as a server dependency, this will allow us to import our spritesheet like so:

```ts
```

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2023-01-03 14:43 UTC, stevenbister commented
Chromatic: https://62cd418bce39ee57e0c8cc30-yiyujpopry.chromatic.com/?path=/story/osc-ui-icons--all-icons

(These are just the initial Icons from Figma)

2023-01-06 15:11 UTC, hi-im-si requested changes

2023-01-06 15:13 UTC, Tom-Pearce commented
Maybe some of the names need changing, seems some of the names are too "use case specific" but could have multiple use cases - I'm guessing they just came straight from figma so probably just using whatever names they were there, but:
- Documents -> document (icon only shows 1, may want another icon to show multiple)
- Files -> folder
- Mail -> envelope
- Notifications -> bell
- Payments -> coins/money/coins-gbp (it has £ sign)
- mobile-menu -> menu (it's not really mobile specific)
- send -> paper-plane
- settings -> gear/cog
- students -> users (the icon isn't specific to students, it's just a mutliple version of the user icon)
- tutor -> graduation-cap

2023-01-06 15:13 UTC, hi-im-si commented on packages/osc-ui/src/icons/mobile-menu.svg
> +</svg>
I would prefer to have the mobile menu icon done in CSS so we can animate the open/close state

2023-01-06 15:17 UTC, stevenbister commented on packages/osc-ui/src/components/Icon/Icon.stories.tsx
> +// Can't use fs in a browser, so we have to manually list the icons 😭
I'll double check but I think this would work locally but due to how we build things with our actions the Icons directory won't be available to Chromatic etc. once it's up

2023-01-06 15:37 UTC, stevenbister commented on packages/osc-ui/src/icons/mobile-menu.svg
> +</svg>
Yeah that's a fair point! I've removed that one

2023-01-06 16:31 UTC, hi-im-si commented on packages/osc-ui/src/components/Icon/Icon.stories.tsx
> +// Can't use fs in a browser, so we have to manually list the icons 😭
yeah for sure. i guess the filesystem should be relatively similar and the`File` and `FileReader` API's are merely part of the javascript standards. try running `flyctl ssh console --app pr-648-osc-ecommerce` to see the file directory once in fly - may help understand if there are any differences

2023-01-09 08:56 UTC, stevenbister commented on packages/osc-ui/src/components/Icon/Icon.stories.tsx
> +// Can't use fs in a browser, so we have to manually list the icons 😭
Had a look into this api (not used it before); unless I've misunderstood something it looks like `File` and `FileReader` only read from the users machine (as opposed to a server) and files that they have specifically allowed to be read so wouldn't quite be what we're after in this case.

Also looking at the directory on Fly, we're only passing in the Remix app, so the other packages in the mono repo aren't available. Not sure about Chromatic, presumably it'll just be `osc-ui`

2023-01-30 17:08 UTC, hi-im-si approved these changes

2023-01-30 17:09 UTC, merged