feat: add TextInput component, styles and tests
Open-Study-College/osc pull request #653
Opened 2023-01-10 12:31 UTC by mattwendzina

Closes #614 

## 📝 Description

Adds TextInput component. 

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Adds TextInput component and covers all required styles

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
There is one accessibility issue on the error message text. It says there is insufficient colour contrast of 4.05 and the expected ratio is 4:5:1. So it's not far off but maybe we need to make the error red colour a touch darker?

2023-01-11 09:50 UTC, stevenbister requested changes
Nice man! Couple of little comments but otherwise all good 😎

2023-01-11 09:50 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +    variants?: string[];
I would maybe try and type the values that can be passed into this array (might need a generic?) but typing that we can only pass "primary", "secondary", "tertiary" etc. would be useful. This is probably the same in the Select component actually?

Another thought might be to remove the "error" variant from here. So when the `displayError` const is true then a `has-error` classname gets added. Might make the dx a little nicer?

2023-01-11 09:50 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +    }, []);
Does this need a dependency? If not might be worth adding
```ts
// eslint-disable-next-line react-hooks/exhaustive-deps
```
With a note as to why its disabled

2023-01-16 17:27 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +    variants?: string[];
Added a union type. I had a look into generics but not sure how you'd use on in this case. If you can think of a better way of doing it I'd be keen to know = )

2023-01-16 17:27 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +    }, []);
Done 👍

2023-01-16 17:28 UTC, mattwendzina commented
This is now rebased and using the correct tokens.

2023-01-18 09:40 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +    variants?: string[];
Ahaa no sorry that's my bad I meant union not generic 😅 What you've done is what I meant

2023-01-18 10:05 UTC, stevenbister requested changes

2023-01-18 10:05 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +            setValue(defaultValue);
Could we set this directly in the state and lose the useEffect?
```ts
const [value, setValue] = useState<string | number | readonly string[]>(defaultValue);
```

2023-01-19 10:41 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    .c-input {
Done

2023-01-19 10:41 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +::placeholder {
Updated

2023-01-19 10:42 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                order: 2;
This is still required and does work despite what the inspector says lol. I've added `display:flex` though to keep it happy.

2023-01-19 10:44 UTC, mattwendzina commented on packages/osc-ui/src/components/Label/label.scss
> +.c-label__required {
Done 👍

2023-01-19 10:46 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +            setValue(defaultValue);
Good shout. I seemed to remember reading a long time ago that this wasn't the best way to do it, but just read another article that advocates it and explains the differences, main one being that it will be available on first render, plus it's a little cleaner!
https://stackoverflow.com/questions/66993812/usestate-vs-useeffect-setting-initial-value
I'll update this for the others too.

2023-01-19 11:22 UTC, mattwendzina commented
@hi-im-si - I should have done the Label as a separate PR, but didn't so I've made a change here, but seems pointless doing it in all the others - as it's such a small change. Letting you know so that the change here is the one that gets used with dealing with conflicts. Is this okay, or would you rather I make the change across all of them?

2023-01-20 08:39 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                order: 2;
Haha fair enough 🤷

2023-01-20 08:41 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +            setValue(defaultValue);
Sweet! Yeah any excuse to get rid of a useEffect lol! Eslint is complaining that the import is still there though

2023-01-20 08:42 UTC, stevenbister requested changes
Looking really good mate! Just got that eslint warning to clear up and I think we're good to go 🚀

2023-01-20 09:31 UTC, mattwendzina commented
Thanks @stevenbister! - removed useEffect! Also just moved passing placeholder in explicitly - this can just go in with the 'rest'.

2023-01-20 10:03 UTC, stevenbister approved these changes
Nice! All good to go 🚀

2023-01-30 13:26 UTC, hi-im-si reviewed
need to discuss whether these should be actioned or we close and refernce in a separate fix branch. any thoughts @stevenbister

2023-01-30 13:26 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                padding: 0.375em 2.563em 0.375em 0;
see padding comments previous

2023-01-30 13:26 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
we should be using the `sr-only` class or method

2023-01-30 13:26 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                height: 1.875em;
this is actually a good example of where `em` probably is better to use

2023-01-30 13:26 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
is there a specific reason for why the label sits below the input and we are using flex order to readjust?

2023-01-30 14:27 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
Rather than add a wrapper we could use grid instead? And we'd benefit from the same (if not more?) control than if we used flex. 
I'd imagine something along these lines:

```scss
__container {
    display: grid;
    grid-template-rows: repeat(3, minmax(0, auto));  // could omit this and let the rows be set implicitly
}

__label,
__input,
__icon,
__error {
    // explicitly set the column position as we're going to be layering some items into the same row
    // and we don't want the implicit columns to be added.
    grid-column: 1; 
}

__label {
    grid-row: 1;
}

__input,
__icon {
    // layer the icon and input into the same row
    // this means we can remove the position: absolute / transform: translate stuff
    grid-row: 2;
}

__icon {
    justify-self: end;
    align-self: center;
}

__error {
  grid-row: 3;
}
```

2023-01-30 14:28 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
Aha I missed this! Yeah, unless there's a good reason it should sit before the input to keep the reading/tabbing order

2023-01-30 14:34 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                <Button className="c-input__button">
I disagree on this one, buttons will assume the `type="submit"` when it's associated with a form by default

> The default behavior of the button. Possible values are:
> `submit`: The button submits the form data to the server. This is the default if the attribute is not specified for buttons associated with a `<form>`, or if the attribute is an empty or invalid value.

I think we discussed it a while back with Chakra because they add `type="button"` so we would have to explicitly change it, but our buttons don't do that

2023-01-30 14:36 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
We have a `<VisuallyHidden>` component we could wrap around this which uses that `sr-only` class

```tsx
<VisuallyHidden asChild>
    <Label ... />
</VisuallyHidden>
```

2023-01-30 14:39 UTC, stevenbister commented
> need to discuss whether these should be actioned or we close and refernce in a separate fix branch. any thoughts @stevenbister

I'm guessing most of these comments will be in the other form fields as well, so perhaps we merge these in and open a couple of issues to tackle them all in one PR rather than keeping track across several?

2023-01-30 14:41 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                <Button className="c-input__button">
You are correct @stevenbister - happy to retract :)

2023-01-30 14:50 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    padding: 0.375em 2.563em 0.375em 1.25em;
Hmmm, yeah looking at this again I think these should be `px` as I guess we wouldn't want the space around the text to scale especially the x-axis as it could cause the actual "text area" to become quite narrow

2023-01-30 14:57 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
Here's a basic example:
https://codesandbox.io/s/white-platform-xqdneu?file=/src/styles.css

2023-01-30 15:32 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
even better :)

2023-01-30 15:37 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
> > need to discuss whether these should be actioned or we close and refernce in a separate fix branch. any thoughts @stevenbister
> 
> I'm guessing most of these comments will be in the other form fields as well, so perhaps we merge these in and open a couple of issues to tackle them all in one PR rather than keeping track across several?
> 
> Although having said that maybe worth waiting for @mattwendzina to answer a couple of your questions before closing?

Yeah unfortunately i think theres a couple in there that @mattwendzina will need to answer just to be 100% sure. i think the padding/units need to be addressed as a team - not sure if they have filtered across other work.

2023-01-30 16:36 UTC, hi-im-si requested changes
see previous comments

2023-01-31 10:36 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                height: 1.875em;
https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#widths-and-heights-9

2023-01-31 10:41 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                height: 1.875em;
we could even remove the `height` and then add in some top position on the label to bump it down inline with the design

2023-02-01 12:56 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
Updated 👍

2023-02-01 12:56 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    padding: 0.375em 2.563em 0.375em 1.25em;
Done

2023-02-01 12:57 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        transform: translateY(-50%);
Replaced with the css grid approach 👍

2023-02-01 12:57 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                height: 1.875em;
Removed

2023-02-01 12:57 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                top: 35%;
Removed

2023-02-01 12:57 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                padding: 0.375em 2.563em 0.375em 0;
Sorted

2023-02-01 12:58 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
Added VisuallyHidden component into the Label component with an optional `hidden` prop for setting it.

2023-02-01 12:58 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
I've left below as per our conversation.

2023-02-01 13:10 UTC, mattwendzina commented
I've also added reduced the size of the svg that sits in the button on the quaternary style since this has updated in the rebase to have correct button styling. This is obviously a bit different from the styling now anyway... so need to decided whether we want to keep like this or change back?

2023-02-01 15:13 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                />
Sweeeeeeet

2023-02-01 15:15 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
Noice! Nothing you need to change, but if you add the `asChild` prop it'll pass the props through to the child component and remove the extra div that gets added as it's using https://www.radix-ui.com/docs/primitives/utilities/slot 😎 

Like I said though, not need to change what you've done, just a fun fact :P

2023-02-01 15:20 UTC, stevenbister commented
> I've also added reduced the size of the svg that sits in the button on the quaternary style since this has updated in the rebase to have correct button styling. This is obviously a bit different from the styling now anyway... so need to decided whether we want to keep like this or change back?

You might have to adjust the icon size but if you use `variant="quaternary"` to give you the correct styling

2023-02-01 15:27 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
Noice.

2023-02-02 10:46 UTC, stevenbister requested changes
Sorry Matt bet this feels endless 😅 Hopefully last couple of comments and fairly minor, I think

2023-02-02 10:46 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    max-width: 30ch;
I don't think we should be setting a max width on this, looking at Figma the inputs have potential to be wider than this. I would probably control the size of the inputs with the container. So take this off here, then on `__container` class add a width of 100%, that way the layout of the form will be able to control the width. 

Does that make sense? Sorry didn't occur to me before :S

2023-02-02 10:46 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        flex-direction: column;
This `flex-direction` won't have an effect anymore now we're using `grid`

2023-02-02 10:46 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +        <Button className="c-input__button">
Not sure if you saw my comment yesterday about the quaternary style?

https://github.com/Open-Study-College/osc/pull/653#issuecomment-1412237632

2023-02-02 11:52 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    max-width: 30ch;
Updated 👍

2023-02-02 11:54 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        flex-direction: column;
Removed

2023-02-02 11:54 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +        <Button className="c-input__button">
Added now 👍

2023-02-02 13:20 UTC, stevenbister approved these changes
LGTM

2023-02-14 11:31 UTC, hi-im-si requested changes

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        padding-right: 5%;
use `$space-` variable

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +$input-pl: var(--space-scale-epsilon);
switch to sass variables

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    font-size: var(--font-scale-base);
should not need to define the font size as this should inherit from the `<body>`

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        box-shadow: 0 0 0 2px var(--color-primary);
use the variables defined in the new `settings/shadows.scss`

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        box-shadow: 0 0 0 2px var(--color-primary);
the default focus styles should work here instead of defining it. these can be found in: `packages/osc-ui/src/styles/elements/_type.scss`

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                border-radius: 6px;
use a `$rad-` variable defined in `settings/radius.scss`

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                transition: 100ms ease-in-out;
use variables for animation timing:
```suggestion
                transition: $timing-s ease-in-out;
```

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                    transform: translate(0, -1.25em) scale(0.8);
I would tend to avoid using `em` for transforms. Maybe @stevenbister could share his views on this?

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
i guess because you have used the `VisuallyHidden` component, then you can remove these redundant styles?

2023-02-14 11:31 UTC, hi-im-si commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                    font-size: var(--font-scale-base);
is this needed - can it just be inherited by the `<body>`

2023-02-14 11:59 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +        padding-right: 5%;
Done

2023-02-14 12:00 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +$input-pl: var(--space-scale-epsilon);
Done

2023-02-14 12:00 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +    font-size: var(--font-scale-base);
Removed

2023-02-14 12:00 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                border-radius: 6px;
Done

2023-02-14 12:01 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                left: -9999px;
Yep, good spot 👍

2023-02-14 12:01 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                    font-size: var(--font-scale-base);
Yep, not needed. Removed.

2023-02-14 12:13 UTC, stevenbister commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                    transform: translate(0, -1.25em) scale(0.8);
Hmmm, tbh I don't really have a strong opinion. I guess I generally would use `px` or `rem` but in this case as you're wanting to move the label to make space for some text I reckon `em` might be better? As you'd want it to move relative to the text size 🤔 

@hi-im-si Is there any reason you'd avoid using em? 

As an aside @mattwendzina This transform property is used in a couple of places (also on line 98 `.c-input:focus + .c-label`) so might be worth either consolidating the selectors or putting it in a variable

2023-02-14 12:22 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/text-input.scss
> +                    transform: translate(0, -1.25em) scale(0.8);
Left as is, and moved label transform into a variable 👍

2023-02-14 12:50 UTC, hi-im-si approved these changes

2023-02-14 12:52 UTC, merged