feat: add RadioGroup component, styles and tests
Open-Study-College/osc pull request #654
Opened 2023-01-11 13:07 UTC by mattwendzina

Closes #616 

## 📝 Description

> Adds RadioGroup component

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

This adds the Radix RadioGroup component and styling

## 💣 Is this a breaking change (Yes/No): No

2023-01-12 09:43 UTC, stevenbister requested changes
Nice man! Few comments for ya

2023-01-12 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +    &__item {
I think we need to add `cursor: pointer;` to this property. At the moment it's only on the label so it looks a bit like you can't click on the "dot"

2023-01-12 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +            <p className="c-radio-group__description" id={description?.id}>
I think a `fieldset` and a `legend` would be better here as opposed to a `div` and a `p` it's better semantically.

I would also maybe consider how to handle what to do if a description isn't added. You've set the type as optional but there's no conditions here so if it's not added we'll get some empty markup.
Personally I would make it required as you'd always want to include a `legend` / description for your group.

2023-01-12 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +                aria-labelledby={description?.id}
You don't need both `aria-label` and `lablledby`. Labelled by takes precedence over `aria-label` so you can probably just use that, that way it'll also match your legend above.

2023-01-12 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +        color: #b9b9b9;
Can this be a variable or hsl value?

2023-01-12 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +            height: 0.875em;
I think these values should be calculated from the `__item` width and height. That way if anything changes we don't have to workout the size again

2023-01-16 12:24 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +                aria-labelledby={description?.id}
Thanks mate, I've had a think and play with this. Basically I see `aria-label` working as a fallback. `Lablledby` is pointing to the description, but I've made this optional, perhaps wrongly so, but the actual designs don't have description text, I just added it so though perhaps there may be use cases where a written description isn't needed. In these cases it would fall back to the name given to the Label.

2023-01-16 17:36 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +    &__item {
Done

2023-01-16 17:51 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +            <p className="c-radio-group__description" id={description?.id}>
Good shout. I've updated this and agree it should be required. I've taken the optional chaining off, but I don't know whether it should be kept really. The TS will ensure correct typing but won't stop runtime errors so without setting a default I wonder whether we should always be using optional chaining?

2023-01-16 17:52 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +                aria-labelledby={description?.id}
So I wrote this comment before the above one lol. Given that I'm now making it required, I've removed `aria-label`.

2023-01-16 18:01 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +        color: #b9b9b9;
Yep, updated 👍

2023-01-16 18:05 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +            height: 0.875em;
I'm not sure exactly what you mean, how would I do this?

2023-01-18 10:38 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +                aria-labelledby={description?.id}
Haha no worries

2023-01-18 11:02 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +            height: 0.875em;
So you've got a width and height set to 1.25em right and the after has a width & height of 0.875. So the difference is 0.7 (0.875 / 1.25 = 0.7).

Now with that info you just need to do a calc, i'd probably set it up something like this

```scss
&__item {
    --radio-item-size: 2em;
    --radio-indicator-diff: 0.7;

    width: var(--radio-item-size);
    height: var(--radio-item-size);

    &:after {
        width: calc(var(--radio-item-size) * var(--radio-indicator-diff));
        height: calc(var(--radio-item-size) * var(--radio-indicator-diff));
    }
```

Now if we change the --radio-item-size at any point then the `after` indicator should scale with it :)

2023-01-19 10:56 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/RadioGroup.tsx
> +            <p className="c-radio-group__description" id={description?.id}>
Yeah, good point, didn't think of that 👍

2023-01-19 11:15 UTC, mattwendzina commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +            height: 0.875em;
Ahh, nice, I hadn't quite made the connection, but makes sense now! Thanks = ) Updated 👍

2023-01-20 09:14 UTC, stevenbister commented on packages/osc-ui/src/components/RadioGroup/radio-group.scss
> +            height: 0.875em;
Yeah, in the grand scheme of things it's probably not that big a deal but I feel like it makes things a little more maintainable & scalable

2023-01-20 10:02 UTC, stevenbister approved these changes
LGTM

2023-02-14 17:35 UTC, merged