Checkbox component
Open-Study-College/osc pull request #655
Opened 2023-01-12 11:25 UTC by mattwendzina

Closes #615 

## 📝 Description

Adds Checkbox component

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

This adds the Radix Checkbox component and styling

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

For the secondary styling I've changed the Focus colour to `secondary` when selected because when the checkbox is selected it's the same colour as the Focus ring and there is no border colour so you can't differentiate it. See pic below:
<img width="257" alt="Screenshot 2023-01-12 at 09 25 56" src="https://user-images.githubusercontent.com/36510083/212054614-e09cfda0-c458-47c1-be35-43708ce798e3.png">

2023-01-17 11:15 UTC, mattwendzina commented
This is now rebased and using the correct colour tokens.

2023-01-18 10:20 UTC, stevenbister requested changes

2023-01-18 10:20 UTC, stevenbister commented on packages/osc-ui/src/components/Label/label.scss
> +.c-label__required {
Think I mentioned this on a previous pr but can this be nested?

2023-01-18 10:20 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    .c-checkbox {
Should this be nested within the container? I think ideally we'd want it to have a lower specificity if possible?

2023-01-18 10:34 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +    description?: { id: string; value: string };
I think similar to #654 this should be required

2023-01-19 11:21 UTC, mattwendzina commented on packages/osc-ui/src/components/Label/label.scss
> +.c-label__required {
Just updating this on the TextInput rather than doing it across the files - will add a comment there and let @hi-im-si know for resolving conflicts = )

2023-01-19 11:31 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    .c-checkbox {
Yep, good shout. Done 👍

2023-01-19 11:39 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +    description?: { id: string; value: string };
Don't think it will always be required as you can have single checkboxes, and as per as discussion, looks like you can have a `<fieldset/>` without a `<legend/>`.

2023-01-20 08:48 UTC, stevenbister commented on packages/osc-ui/src/components/Label/label.scss
> +.c-label__required {
Sounds good

2023-01-20 08:50 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +    description?: { id: string; value: string };
Yep! Definitely an interesting one! Just dropping this here for future reference
https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element

2023-01-20 08:50 UTC, stevenbister approved these changes
LGTM

2023-02-14 09:55 UTC, aaacafe786 commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +        const [checked, setChecked] = useState<string | boolean>(false);
gonna move this out of the checkbox component in a different pr

2023-02-14 13:07 UTC, hi-im-si commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    }
i would sub-class the icon rather than take this approach e.g. `.c-checkbox__icon` or `c-checkbox__checkmark`

2023-02-14 13:08 UTC, stevenbister requested changes
Looks good, couple of minors/nitpicks

2023-02-14 13:08 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +        &.check {
Can we change this class to `is-checked`?

2023-02-14 13:08 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    width: 1.25em;
Perhaps these values could be variables?

2023-02-14 13:08 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +        width: 0.875em;
Same as before could these be variables? Or even better calculated from the checkbox size? Think we did something similar for the radios if I remember right?

2023-02-14 13:08 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +            width: 0.625em;
Icon has a css variable `--icon-size` which sets the width and height, so you might be able to use that here instead?

2023-02-14 13:24 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    width: 1.25em;
`rem` would probably be best so we can scale it still, I think 🤔

2023-02-14 13:42 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.stories.tsx
> +import { CheckIcon } from '@radix-ui/react-icons';
Deleted

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +        &.check {
Updated

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    width: 1.25em;
Done 👍

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +        width: 0.875em;
Sorted

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +            width: 0.625em;
Done

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    }
Cool, sorted.

2023-02-14 13:43 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/checkbox.scss
> +    width: 1.25em;
Updated to rem

2023-02-14 13:57 UTC, merged