Feature/navbar
Open-Study-College/osc pull request #659
Opened 2023-01-17 16:31 UTC by stevenbister

- Closes #179
- Closes #182 

## 📝 Description

Adds a header, navbar and burger component to `osc-ui`

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

Adds three new composable components, which can work together to build a header with a navbar.

The biggest chunk of work is in the Navbar component which is is inspired by Radix and consists of `Navbar`, `NavContent`, `NavItem`, `NavLink`, `NavList`, `NavSubMenu` and `NavTrigger`.
The `NavSubMenu` makes use of React's `useContext` hook to allow us to keep the component composable while still being able to pass some props through to it's children, such as an `isOpen` state. To access the context `NavSubMenu` is wrapper in a context provider and I've added a custom `useSubNavContext` hook to the end of the file which allows us to access it.

All styling has been added for each component, some styles are shared across files (ie. header.scss may contain some small styles that influence the navbar when it's nested)

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

To generate the unique Ids for the content & trigger components I've installed lodash's uniqueId package and wrapped it in a `useMemo`. Once we fully upgrade to React 18 this can be dropped in favour of the new `useId` hook.

Once  #648 is merged we can replace the inline svgs with the `Icon` component and make use of the spritesheet.

I haven't added the search bar or any of the functionality to the buttons in the "actionNav" as they need dependencies we don't have on main yet (algolia/hydrogen)

2023-01-17 16:40 UTC, stevenbister commented
Storybook links:

- Buger: https://62cd418bce39ee57e0c8cc30-srntyupecx.chromatic.com/?path=/docs/osc-ui-burger--primary
- Navbar: https://62cd418bce39ee57e0c8cc30-srntyupecx.chromatic.com/?path=/docs/osc-ui-navbar--primary
- Header: https://62cd418bce39ee57e0c8cc30-srntyupecx.chromatic.com/?path=/docs/osc-ui-header--primary
(there's some weird overflow on here which has something to do with the iframe I think, generally that should break before it does that 🤔 ... if only container queries had better support...)

2023-01-17 16:51 UTC, stevenbister commented
Just thought, I probably need to style a single level nav a little more as it looks a bit funky if there's only one level of links

![image](https://user-images.githubusercontent.com/23461173/212961320-a66314ac-dc1c-45ee-ba13-871703b6f4a1.png)

2023-01-18 11:20 UTC, mattwendzina commented on packages/osc-ui/src/components/Burger/Burger.tsx
> +export const Burger = forwardRef<ElementRef<BurgerRef>, ComponentPropsWithoutRef<BurgerRef>>(
I still find some of this TS stuff pretty confusing lol, but from what I've understood I think it may be that one should use `ComponentPropsWithRef` when using `forwardRef`. I got this from the following article that I'd used a bit when building out some of the form stuff with `forwardRef`:
https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/

They show the use case for `withoutProps` as a way of extending `button` props but then note that for when using `forwardRef` that you can use `ComponentPropsWithRef`.

2023-01-19 09:02 UTC, stevenbister commented on packages/osc-ui/src/components/Burger/Burger.tsx
> +    isOpen: boolean;
Ahh good catch! I decided to make it required after I'd written the tests. I found it easy to miss off and generally it'll be controlled by some state so should always be there.

I've updated the test file 👍

2023-01-19 09:08 UTC, stevenbister commented on packages/osc-ui/src/components/Burger/Burger.tsx
> +export const Burger = forwardRef<ElementRef<BurgerRef>, ComponentPropsWithoutRef<BurgerRef>>(
Ahhh nice find! I hadn't come across that before I'd just been following the [Radix extending primitive pattern](https://www.radix-ui.com/docs/primitives/overview/styling#extending-a-primitive) but it does make more sense to use withRef! I've updated

2023-01-31 10:33 UTC, Tom-Pearce reviewed
Added a few code comments, more thoughts than requests.

Only other thing I noted is the dark mode styling is broke on Nav in storybook - dunno if this is something that should be working or something we're doing later down the line - makes more sense to me to do it as we're going though?

2023-01-31 10:33 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Burger/burger.scss
> +$burger-gap: 4px;
Should these be dynamic from some var/settings somewhere else?

2023-01-31 10:33 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Header/Header.tsx
> +            </svg>
Are we planning to move the SVG out in the future, or should it be done now? Just seems messy to have it in here to me?

2023-01-31 10:33 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Navbar/Navbar.spec.tsx
> +        const navTrigger = screen.getByRole('button', { name: 'Courses' });
This might be my ignorance of testing, but would it be better to have these dynamically reference the values found in `testNestedSubMenuNav`? Just thinking if someone was to change the values (could be as simple as spotting a spelling error) then it would cause it to fail at this point. 

Although at the same time I can appreciate that may be the point - ensuring that the final result matches the original data since we know the data as it's defined for the purpose of the test. Just a thought.

2023-02-01 09:49 UTC, stevenbister commented on packages/osc-ui/src/components/Burger/burger.scss
> +$burger-gap: 4px;
Yes they should, I've updated it to be calculated from the base-size of 16px.

Re the dark mode, yeah that's probably something that needs discussing @hi-im-si, @mattwendzina any thoughts?
Probably makes sense to do it as we go, but I'm conscious we probably need to decide how the colours are gonna swap (i.e. what should the `--color-primary` dark version be.

2023-02-01 09:50 UTC, stevenbister commented on packages/osc-ui/src/components/Header/Header.tsx
> +            </svg>
Yep! Was waiting for #648 to be merged, now that's done I've moved the logo into the spritesheet and we can use the `<Icon />` component instead 😎

2023-02-01 09:56 UTC, stevenbister commented on packages/osc-ui/src/components/Navbar/Navbar.spec.tsx
> +        const navTrigger = screen.getByRole('button', { name: 'Courses' });
I think in this case I wouldn't reference the data. Generally in FE testing you want to test based on what you'd expect the user to see, for example if I had something on there that was capitalising the text to `Courses` but the data was `courses` it would fail as a user should expect to see the capital `C`.

I guess I could wrap the reference in the test with the same function to capitalise it but I think this makes it clearer as to what I'd expect

2023-02-03 16:45 UTC, Tom-Pearce commented on packages/osc-ui/src/components/Navbar/Navbar.spec.tsx
> +        const navTrigger = screen.getByRole('button', { name: 'Courses' });
Fine by me, thought that might be the case

2023-02-14 12:38 UTC, hi-im-si requested changes
Mate, such a good job. Left a couple tiny bits and also noticed that the arrow was missing from the larger nav items:
![image](https://user-images.githubusercontent.com/1517907/218740829-93847f05-6ede-4e2e-8f7f-8e6a7612fc9a.png)
Other than that, when the new variables come across that will be a fun job....NOT!

2023-02-14 12:38 UTC, hi-im-si commented on packages/osc-ui/src/styles/objects/_icon.scss
> +.o-icon:not(.o-logo) {
would probably switch this out to be a state class, something like `is-logo`. If the logo does have a corresponding file then it should be a component rather than an object

2023-02-14 12:38 UTC, hi-im-si commented on packages/osc-ui/src/components/Header/Header.tsx
> +            <Icon id="logo" size={[278, 33]} className="o-logo" />
would probably switch this out to be a state class, something like `is-logo`. If the logo does have a corresponding file then it should be a component rather than an object

2023-02-14 12:38 UTC, hi-im-si commented on packages/osc-ui/src/components/Header/header.scss
> +    }
when the new variables come across, there has been a global `:focus` style setup so you will probably be able to remove this

2023-02-14 12:38 UTC, hi-im-si commented on packages/osc-ui/src/components/Navbar/navbar.scss
> +    }
when the new variables come across, there has been a global `:focus` style so this can probably be removed

2023-02-14 13:10 UTC, stevenbister commented
>  also noticed that the arrow was missing from the larger nav items:

I knew I'd forgotten something 😅 

> Other than that, when the new variables come across that will be a fun job....NOT!

😭

2023-02-14 13:13 UTC, stevenbister commented on packages/osc-ui/src/components/Header/Header.tsx
> +            <Icon id="logo" size={[278, 33]} className="o-logo" />
Ah yeah I did toss and turn about whether it should be a component or object! So are you thinking something like

```tsx
<Icon id="logo" size={[278, 33]} className="is-logo" />
```

2023-02-16 12:32 UTC, stevenbister commented on packages/osc-ui/src/styles/objects/_icon.scss
> +.o-icon:not(.o-logo) {
Sorted! I decided to move the logo into it's own component file as it's gonna get used in the footer too. So now it's `c-logo` :)

2023-02-16 12:32 UTC, stevenbister commented on packages/osc-ui/src/components/Header/header.scss
> +    }
Done!

2023-02-16 12:32 UTC, stevenbister commented on packages/osc-ui/src/components/Navbar/navbar.scss
> +    }
Done!

2023-02-16 12:33 UTC, stevenbister commented on packages/osc-ui/src/components/Header/Header.tsx
> +            <Icon id="logo" size={[278, 33]} className="o-logo" />
See other comment

2023-02-16 17:14 UTC, hi-im-si requested changes

2023-02-16 17:14 UTC, hi-im-si commented on packages/osc-ui/src/styles/utilities/_util.scss
> +        @include mq(mq-token("desk"), max) {
use sass variable `$mq-desk`

2023-02-16 20:34 UTC, stevenbister commented on packages/osc-ui/src/components/Header/header.scss
> +            button {
Yeah, I see your point and generally I would agree. However in this case I left them as tag selectors as we haven't fully built the component that are to go in the "action bar" (search button, cart etc.) so I wanted to keep the selectors generic enough that we could drop anything in there and they would take on the required styles... Having said that this did remind me of the `Slot` primitive from Radix, so I've wrapped the children in a `Slot` with the class of `.c-header__action-item` so we can target that instead :D

2023-02-16 20:34 UTC, stevenbister commented on packages/osc-ui/src/components/Header/header.scss
> +        > button {
As above

2023-02-16 20:34 UTC, stevenbister commented on packages/osc-ui/src/styles/objects/_container.scss
> +    @include mq(mq-token("desk")) {
Ahh knew I'd missed some! Done!

2023-02-16 20:34 UTC, stevenbister commented on packages/osc-ui/src/styles/utilities/_util.scss
> +        @include mq(mq-token("desk"), max) {
Done!

2023-02-17 11:19 UTC, merged