Feature/Datepicker component
Open-Study-College/osc pull request #667
Opened 2023-02-02 14:06 UTC by mattwendzina

Closes #619 

## 📝 Description
Add a Datepicker component

## ⛳️ Current behavior (updates)
N/A

## 🚀 New behavior
A Datepicker component

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

I'm opening this as a draft PR for any comments. There are some styling tweaks needed. 
A couple of things I haven't sussed out:
1) I've set a hard width and can't figure out a way of getting it to just take up the width of the content. 
2) The time presets and buttons below (Clear, Go to today) cause all the content to move slightly. Same with selecting the DateField itself.

Aware there is an Accessibility violation on the contrast for the Label. This is using the darkest grey - neutral-600. This is `hsl(0deg 0% 60%)`. It needs to move to around `hsl(0deg 0% 45%)` in order to pass. Do we want to add this in?

2023-02-06 11:41 UTC, stevenbister requested changes
Looking awesome man! Looks like loads of work gone into this! I appreciate this is a WIP so you might already be aware of some of these, feel free to ignore them if you are :)

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/Calendar/DecadeCalendar.tsx
> +                    <Icon className="chevron" id="chevron-left" />
These classNames might need to be "BEM'd" `c-calendar__chevron` or `c-calendar__icon` or something

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/Calendar/YearCalendar.tsx
> +                    <Icon className="chevron" id="chevron-left" />
See other comment about BEM

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
You might still be working on this but should this be accessible from clicking on the date in the calendar?

I've whipped up a prototype if that doesn't make sense: https://www.figma.com/proto/UELMnQtduiz7FIxF17YeEX/Datepicker-example-proto?page-id=0%3A1&node-id=1%3A2939&viewport=446%2C430%2C0.61&scaling=min-zoom&starting-point-node-id=1%3A2939


https://user-images.githubusercontent.com/23461173/216957655-72673805-7315-4ad2-b41d-1eacf473bb8c.mov

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +    clearSelection,
Noticed the props set like this one a few of these now, we'll need to refactor them into the `(props: DateRangePickerProps)` and then destructure them outside like our other components.

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            <div {...labelProps} className="c-datepicker__label">
Should this be a `label` element?

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +            <div className="c-datepicker__label" {...labelProps}>
Should this be a `label` element?

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/Calendar/Calendar.tsx
> +};
How would you feel about co-locating the CalendarCell & CalendarGrid into this file? I think as they're essentially sub-components it might make sense to keep them together in this file

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangerPickerContainer.tsx
> +import type { AriaDateRangePickerProps } from '@react-aria/datepicker';
Similar to my other comment about co-locating, perhaps we could move this into the DateRangePicker file?

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendarContainer.tsx
> +import { getLocalTimeZone, GregorianCalendar, today } from '@internationalized/date';
Another one to maybe co-locate?

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +    width: max-content;
> I've set a hard width and can't figure out a way of getting it to just take up the width of the content.

Is this what you were talking about? I think that's probably fine

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +        width: 40px;
Perhaps these values could be a variable? Seen it reused here and further down

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            border-radius: 50%;
There's a global variable saved for this `$radius` I think

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +                background: var(--highlighted-color) !important;
Is there a reason we're using `!important` here? Ideally we shouldn't use it so we might need to look at whether there's a way we can restructure the scss so it's not needed here

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            background: #00a698 !important;
See other comment re `!important` also the colour value should be a variable

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            .chevron {
See comment about BEM-ing this

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/date-field.scss
> +    max-width: 30ch;
Wouldn't use a max-width here and let the container handle the width of the input

2023-02-06 11:41 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +export const Primary = Template.bind({});
Noticed there's no background on the calendar so you can see all of the stuff behind it when it's open
![image](https://user-images.githubusercontent.com/23461173/216946704-f09d25f0-6ef3-4cc4-8a3b-64f1df9e7948.png)

2023-02-06 16:30 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/Calendar.tsx
> +};
Agree, done 👍

2023-02-06 16:30 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangerPickerContainer.tsx
> +import type { AriaDateRangePickerProps } from '@react-aria/datepicker';
Updated

2023-02-06 16:31 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +export const Primary = Template.bind({});
Good spot. Sorted 👍

2023-02-06 16:50 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/Calendar.tsx
> +                <h3>
Updated 👍

2023-02-06 17:05 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/DecadeCalendar.tsx
> +                    <Icon className="chevron" id="chevron-left" />
Good point. Done.

2023-02-06 17:05 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/YearCalendar.tsx
> +                    <Icon className="chevron" id="chevron-left" />
Done

2023-02-06 17:05 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendarContainer.tsx
> +import { getLocalTimeZone, GregorianCalendar, today } from '@internationalized/date';
Done

2023-02-06 17:06 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            .chevron {
Done

2023-02-06 17:29 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +    clearSelection,
Oooh yeah, forgot about doing that 😅 
Updated 👍

2023-02-06 17:31 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            <div {...labelProps} className="c-datepicker__label">
Yup, updated.

2023-02-06 17:31 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +            <div className="c-datepicker__label" {...labelProps}>
Updated

2023-02-06 17:59 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +    width: max-content;
Yeah, but I had hard-coded the width. Turns out I worked out what the issue was that was causing it to span entire width. I was using flex with flex-wrap and have the 2 inner containers and flex-basis 100. I just changed the flex-direction to column instead and this solved the issue 👍

2023-02-06 18:02 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +        width: 40px;
Yeah good shout. Done.

2023-02-06 18:11 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            border-radius: 50%;
Nice. Updated for all border radius'.

2023-02-06 18:28 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/date-field.scss
> +    max-width: 30ch;
Yeah, good point. I've changed to `width:100%` and added some right-padding to the last date segment to match the spacing between the year and calendar icon.

2023-02-06 18:52 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +                background: var(--highlighted-color) !important;
Yeah, I was struggling to get the right order of priority. Upon inspecting it a bit further I managed to figure it out by swapping some of the ordering around 🙌

2023-02-06 18:53 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            background: #00a698 !important;
Done 👍

2023-02-06 18:55 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
Ah. I hadn't anticipated that this is how it would work. I thought these were just separate date pickers rather than allowing you to drill into selecting the year and month like so... 
@hi-im-si - can you enlighten on if this is how you envisioned it would work?

2023-02-07 16:45 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +    clearSelection,
Haha yeah my preference is to do it like this rather than the props thing but 🤷

2023-02-07 16:48 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +    width: max-content;
Nooice

2023-02-07 16:53 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
Yeah... I mean I might be wrong but it feels like it would be a nice UI to be able to jump into years/months rather than mashing the arrows

2023-02-09 10:30 UTC, hi-im-si commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
Just to confirm based on our convo @mattwendzina - the prototype @stevenbister put together is the exact UX of how this form of datepicker should function. I am looking into how this can be achieved affectively from a UX perspective with the range datepicker

2023-02-09 10:33 UTC, hi-im-si commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
just an FYI, I did raise the expected UX on discord via the screenshot i provided: https://discord.com/channels/915621085872029817/1060951309366341632/1060954218736918609
I realised this should have been detailed in further context on the github task

2023-02-09 10:40 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
Ah yes. Reading this now it makes sense. I think at the time I just read this as - there needs to be an individual year and decade view for different use cases - as opposed to they are inner sections of the calendar. Makes complete sense now I think about it of course! 🤦

2023-02-13 10:44 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +                id={uuidv4()}
Be wary of this as it can cause issues with SSR as the server will generate a different ID to the client.

PR (#661) is still open but I had to create a hook to keep them in-sync: https://github.com/Open-Study-College/osc/blob/0655a1473efb7f1e6fa8d49b86023ea06f7784cd/packages/osc-ui/src/hooks/useUniqueId.ts

2023-02-13 10:47 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +                        <ReactAriaButton {...buttonProps} id={uuidv4()}>
See https://github.com/Open-Study-College/osc/pull/667/commits/4fb4a4b3ae9e106afc8de9d6eca299fd93fbb931#r1104286016

2023-02-13 10:58 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +YearCalendar.args = {
Nice! Exactly that :D

2023-02-16 09:08 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +                id={uuidv4()}
Updated 👍

2023-02-16 09:08 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +                        <ReactAriaButton {...buttonProps} id={uuidv4()}>
Updated.

2023-02-16 09:51 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            <label {...labelProps} className="c-datepicker__label">
Should this use the `c-label` class or the `Label` component? I guess the `Label` is pretty Radix-y so that might not work here?

2023-02-16 10:23 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            <label {...labelProps} className="c-datepicker__label">
Good point. Yes, to Radix for Label component, but just updating to `c-label` is fine and removes some more lines of css. I've updated, and updated the label to use colour `neutral-700` meaning all the form will use this darker grey as default.

2023-02-16 11:20 UTC, stevenbister requested changes
Looking really good! A few comments and questions for ya

2023-02-16 11:20 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +            <label className="c-datepicker__label" {...labelProps}>
Another label here, perhaps `c-label`?

2023-02-16 11:20 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendar.tsx
> +                            <h2>{calendarProps['aria-label']}</h2>
If you're setting a visually hidden element to describe the calendar then it's probably worth taking the `aria-label` off. Although VoiceOver doesn't announce it, others might and then we'd be announcing it twice for some users.

I'll see if I can find the article again but I think I read once that `aria-label` is a bit flakey, so I tend to use `VisuallyHidden` over it these days

2023-02-16 11:20 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/ReactAriaComponents/ReactAriaComponents.tsx
> +import type { AriaButtonProps } from '@react-aria/button';
I assume we're using the aria buttons, dialogs etc. because they integrate better with the calendar?

2023-02-16 11:20 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            overflow-x: scroll;
As an aside I would recommend always switching on scrollbars on Mac (if you don't already) as it'll help you catch overflow bugs 😎  And as an added bonus you can judge other websites when you notice it on them too 😂 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/23461173/219350105-7146fb76-e38b-484f-98d0-beb47c588e11.png">

2023-02-16 11:21 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            <label {...labelProps} className="c-datepicker__label">
Sweet

2023-02-16 12:12 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +        &:focus {
Ah, good spot. Done. I hadn't noticed that. And yeah, agree on the focus ring. Didn't know about the focus-visible trick, so that's a handy one to know 🙌

2023-02-16 12:14 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            background: var(--selected-color);
Fixed

2023-02-16 15:21 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.stories.tsx
> +MinAndMaxDates.args = {
Yeah, good shout. Not a quick fix lol, but done.

2023-02-16 15:22 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +        &:hover {
Noice. Done.

2023-02-16 15:28 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +            overflow-x: scroll;
Ah, cool very handy to know 😎 
Updated 👍

2023-02-16 15:29 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateField/DateField.tsx
> +    const buttonId = useUniqueId('buttonId:');
Yeah, fair. Done.

2023-02-16 15:48 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateField/DateField.tsx
> +const DateSegment = ({ segment, state }) => {
Old habits die hard 😅 Updated

2023-02-16 15:51 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/ReactAriaComponents/ReactAriaComponents.tsx
> +import type { AriaButtonProps } from '@react-aria/button';
Yeah exactly. I didn't want to add all of the react-aria props into our radix props. And for not many lines of code, a few hooks I thought it would be easier/clearer to use these ones together with the DatePicker.

2023-02-17 08:54 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/ReactAriaComponents/ReactAriaComponents.tsx
> +import type { AriaButtonProps } from '@react-aria/button';
Yeah makes sense, just wanted to confirm :)

2023-02-17 09:06 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendar.tsx
> +                            <h2>{calendarProps['aria-label']}</h2>
Do you mean take aria-label off of the DateRange on line 138?

2023-02-17 09:14 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendar.tsx
> +                            <h2>{calendarProps['aria-label']}</h2>
Yeah, that's right

2023-02-17 10:01 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/CalendarGridAndCell.tsx
> +    const classesList = Object.keys(classes)
For some reason I was getting a load of additional whitespace one the classes originally. Must have been doing something slightly wrong as this seems to work fine now lol. Updated 👍

2023-02-17 10:04 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/DecadeCalendar.tsx
> +                {[...Array(4).keys()].map((_) => {
Yeah exactly. It's a bit of a hardcoded approach but thought this is unlikely to change so hopefully should be okay. Added a comment in just to make it a bit clearer.

2023-02-17 10:56 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/YearCalendar.tsx
> +    } = props;
Yep good point. Done.

2023-02-17 10:56 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/YearCalendar.tsx
> +        state: CalendarState;
Done

2023-02-17 10:56 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/Calendar/YearCalendar.tsx
> +        return [...Array(4).keys()].map((_, idx) => (
Same as above

2023-02-17 11:28 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/calendar.scss
> +        &:hover {
Nice man! May have brought in something else though 😅 Could be a non-issue though, but you get the hover styles on empty cells now

https://user-images.githubusercontent.com/23461173/219639581-6dc0ba78-91b9-4f60-aa67-25f4a7302a05.mov

... sorry 😬

2023-02-17 13:17 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/RangeCalendar/RangeCalendar.tsx
> +                            <h2>{calendarProps['aria-label']}</h2>
Okay yeah makes sense. Removed 👍

2023-02-17 15:37 UTC, stevenbister approved these changes
Just needs a rebase but otherwise good to go! 🎉

2023-02-24 13:45 UTC, hi-im-si commented
We got there in the end! Great work @mattwendzina ! A very well done component 👍🏼

2023-02-24 13:46 UTC, hi-im-si approved these changes

2023-02-24 13:46 UTC, merged