Feature/update token naming convention
Open-Study-College/osc pull request #688
Opened 2023-02-08 15:47 UTC by hi-im-si

## 📝 Description

Refactoring our styles to consider a new variable naming convention and updated design tokens

## ⛳️ Current behavior (updates)

outdated naming conventions and structure not inline with our design system

## 🚀 New behavior

- replaced CSS variables (excluding colours) with Sass Variables
- update to naming conventions of variables
- updated design tokens
- replaced all static values with variables

## 💣 Is this a breaking change (Yes/No):

No

2023-02-08 16:36 UTC, stevenbister requested changes
Nice man! Well happy with that 😄 I've left a few comments, although pretty minor.

I did notice a couple of files that might have been missed
`osc-studio/constants.js` & `osc-ui/src/types.ts` still contain alpha, beta etc. And the `test.html` still references those sizes and classnames, dunno if you think it's worth updating that as well or just direct the others to Figma?

2023-02-08 17:25 UTC, hi-im-si commented on packages/osc-ui/src/components/Popover/popover.scss
> +        border-radius: 4px; // todo: create border radius variable;
I need to consolidate all the border radius' s. theres an absolute shit ton of different ones and they just need consolidating into a small list of $radius variables. one for another time i feel?

2023-02-08 17:26 UTC, hi-im-si commented on packages/osc-ui/src/components/Popover/popover.scss
> +            hsl(206deg 22% 7% / 20%) 0 10px 20px -15px; // todo: create box-shadow variable;
Will need to go through the entire sass codebase and try and consolidate all the box shadows. feel like this could be one for another time?

2023-02-08 17:26 UTC, hi-im-si commented on packages/osc-ui/src/components/Slider/slider.scss
> +        box-shadow: 0 1px 3px hsl(0deg 0% 0% / 10%), 0 1px 2px hsl(0deg 0% 0% / 6%); // todo: assign variable;
see previous comment on box shadow variables

2023-02-08 17:27 UTC, hi-im-si commented on packages/osc-ui/src/styles/tools/functions/_rem.scss
> +    @debug $size;
removed

2023-02-08 17:27 UTC, hi-im-si commented on packages/osc-ui/package.json
> +    "sass": "sass --watch src/styles/main.scss src/styles/main.css"
done

2023-02-08 17:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +$carousel-dot-dimensions: 12px;
done

2023-02-08 17:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Carousel/carousel.scss
> +$carousel-arrow-dimensions: 30px;
done

2023-02-08 17:27 UTC, hi-im-si commented on packages/osc-ui/src/components/Content/textContent.ts
>                  {
done

2023-02-09 08:38 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +        border-radius: 4px; // todo: create border radius variable;
Yeah that's fair, just wasn't sure if this was intentionally left there or not

2023-02-09 08:39 UTC, stevenbister commented on packages/osc-ui/src/components/Popover/popover.scss
> +            hsl(206deg 22% 7% / 20%) 0 10px 20px -15px; // todo: create box-shadow variable;
Yeah same as before, I agree

2023-02-10 13:02 UTC, hi-im-si commented on packages/osc-ui/src/components/Switch/switch.scss
> +$switch-radius: 9999px;
done

2023-02-10 13:03 UTC, hi-im-si commented on packages/osc-ui/src/components/Popover/popover.scss
> +        border-radius: 4px; // todo: create border radius variable;
now done

2023-02-14 08:58 UTC, stevenbister approved these changes
LGTM!

2023-02-14 10:09 UTC, merged