Feature/assignments api
Open-Study-College/osc pull request #690
Opened 2023-02-10 13:31 UTC by Tom-Pearce

## 📝 Description

Authenticates S3 client, and exposes an endpoint to get a signed URL to upload a file to.

## ⛳️ Current behavior (updates)

None

## 🚀 New behavior

Exposes an endpoint to get a signed URL to upload a file to.

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
We need to keep the AWS package versions in sync otherwise it causes TS errors.

2023-02-17 16:55 UTC, mattwendzina commented on packages/osc-api-assignments/src/server/permissions.ts
> +    { debug: true }
Have you intentionally left `debug` in here?

2023-02-17 17:01 UTC, mattwendzina commented on packages/osc-api-assignments/src/resolvers/resolver.ts
> +            return await getSignedUrl(s3Client, command, getSignedUrlParams);
Not exactly sure how error handling is dealt with inside of resolvers. Don't think it's somewhere you can wrap things in a try catch. Just thinking whether we'd need any error handling around this `getSignedUrl` for example for when things go awry? Perhaps this gets picked up elsewhere though?

2023-02-17 17:04 UTC, mattwendzina requested changes
Added a couple of comments mate.
Same as Admin API - guessing this needs some testing around it (and lms API). Wonder if it's worth getting some tickets created around this if it's not being done now?

2023-02-20 13:25 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/server/permissions.ts
> +    { debug: true }
No, I was having issues and forgot it was there, will remove it.

2023-02-20 13:33 UTC, Tom-Pearce commented on packages/osc-api-assignments/src/resolvers/resolver.ts
> +            return await getSignedUrl(s3Client, command, getSignedUrlParams);
Sorry, we need to `return` an error, not throwing them, but GQLShield will also catch any thrown errors and return them nicely as mentioned

2023-02-20 14:14 UTC, mattwendzina commented on packages/osc-api-assignments/src/resolvers/resolver.ts
> +            return await getSignedUrl(s3Client, command, getSignedUrlParams);
Cool, sounds good mate 👍

2023-02-20 14:18 UTC, mattwendzina requested changes
Looks good mate. Guessing you're leaving testing out then for these atm, like the others and will come back to it once they get fleshed out a bit more? 
Assuming that's the case, happy to give it a 👍

2023-02-23 09:15 UTC, Tom-Pearce commented
> Looks good mate. Guessing you're leaving testing out then for these atm, like the others and will come back to it once they get fleshed out a bit more? Assuming that's the case, happy to give it a 👍

Yeah, I need to find some time to at least build some contract testing in for the APIs, and we can do unit/integration later as we extend the functionalities.

2023-02-23 15:45 UTC, mattwendzina commented
> > Looks good mate. Guessing you're leaving testing out then for these atm, like the others and will come back to it once they get fleshed out a bit more? Assuming that's the case, happy to give it a 👍
> 
> Yeah, I need to find some time to at least build some contract testing in for the APIs, and we can do unit/integration later as we extend the functionalities.

Sounds good mate.

2023-02-23 15:45 UTC, mattwendzina approved these changes
LGTM

2023-02-24 14:55 UTC, hi-im-si commented
Nice work @Tom-Pearce 🎉  
Might be worth creating an issue in regard to setting up contract testing as referenced by @mattwendzina to ensure we have this logged for future reference.

2023-02-24 14:55 UTC, merged