fix: moved tokens to osc-ui
Open-Study-College/osc pull request #704
Opened 2023-02-14 11:17 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2023-02-14 14:55 UTC, stevenbister commented on package.json
> +  },
Huh any idea why? Seems a bit weird that `node-sass` is the reason lol

2023-02-14 14:55 UTC, stevenbister commented on package.json
> +    "build:osc-studio": "lerna run build --scope osc-studio --skip-nx-cache",
Can we not cache it?

2023-02-17 09:07 UTC, aaacafe786 commented on package.json
> +  },
theres a table here: https://www.npmjs.com/package/node-sass

2023-02-17 10:04 UTC, stevenbister commented
Just another thought on this @aaacafe786 Will this allow the tokens to work in Remix as well? For example I'm using them here: https://github.com/Open-Study-College/osc/pull/691/files#diff-953aaa92ddb0db1c4571d8b89c2f150c786533b1137a98679bd0eb3a35774b03 but I think it's causing the build to not work?

2023-02-17 11:05 UTC, aaacafe786 commented
@stevenbister i think it will work once this pr is merged in, im copying the tokens folder into the dist folder like the fonts, so anything that imports osc-ui should be able to import them, in order to get studio to work i simply included osc-ui as a dependency

2023-02-17 11:22 UTC, aaacafe786 commented on package.json
> +    "build:osc-studio": "lerna run build --scope osc-studio --skip-nx-cache",
@stevenbister might be possible, i ran into an error where it would not build in CI, but reported the build as a success, some time ago, might need to make seperate commands specifically for CI, probably worth doing in another pr (ef feature/improve-caching-efficiency)

2023-02-17 11:36 UTC, aaacafe786 commented
@stevenbister i can confirm that tokens work in osc-ecommerce

2023-02-17 11:38 UTC, aaacafe786 commented on package.json
>      "tokens:generate": "json-to-scss ./tokens/**/*.* ./packages/osc-ui/src/styles/settings/_tokens.scss --tn 2",
done

2023-02-17 13:43 UTC, stevenbister commented on package.json
> +    "build:osc-studio": "lerna run build --scope osc-studio --skip-nx-cache",
Yeah that's fair, I was just curious

2023-02-20 14:28 UTC, stevenbister requested changes
Hey man getting a lot of errors when running `npm run setup`, `npm run dev:osc-studio` and `npm run storybook`


```shell
npm run setup

> osc@0.42.0 setup
> npm i && npx prisma generate && cd packages/osc-studio && npm i --legacy-peer-deps


> osc@0.42.0 prepare
> husky install

husky - Git hooks installed

changed 7 packages, and audited 3908 packages in 18s

450 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (1 low, 11 moderate, 23 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
warn Preview feature "referentialIntegrity" is deprecated. The functionality can be used without specifying it as a preview feature.

✔ Generated Prisma Client (4.9.0 | library) to ./node_modules/@prisma/client in 147ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

warn Versions of prisma@4.10.1 and @prisma/client@4.9.0 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/stevebister/SITES/osc/packages/osc-studio/packages/osc-ui/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/stevebister/SITES/osc/packages/osc-studio/packages/osc-ui/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevebister/.npm/_logs/2023-02-20T14_27_43_646Z-debug-0.log
```

```shell
npm run dev:osc-studio

> osc@0.42.0 dev:osc-studio
> cd packages/osc-studio && npm run dev


> osc-studio@1.0.0 dev
> npx @sanity/cli@2.29.3 start

Using project ID from environment config (v6lebos6)
Using dataset from environment config (staging)
✔ Checking configuration files...
⠼ Compiling...webpack built 12ec9ee64879cc6f50a3 in 6792ms
✔ Compiling...
Failed to compile.

Error in ./components/inputs/ColorPicker.tsx
Module not found: Error: Can't resolve 'osc-ui/dist/tokens/colors' in '/Users/stevebister/SITES/osc/packages/osc-studio/components/inputs'
 @ ./components/inputs/ColorPicker.tsx 12:37-73
 @ ./schemas/objects/module/content.ts
 @ ./schemas/schema.ts (part:@sanity/base/schema)
 @ ./node_modules/@sanity/base/lib/util/getNewDocumentOptions.js
 @ ./node_modules/@sanity/base/lib/_exports/_internal.js
 @ ./node_modules/@sanity/base/_internal.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/index.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Error in ./schemas/blocks/body.tsx
Module not found: Error: Can't resolve 'osc-ui/dist/tokens/colors' in '/Users/stevebister/SITES/osc/packages/osc-studio/schemas/blocks'
 @ ./schemas/blocks/body.tsx 7:37-73
 @ ./schemas/schema.ts (part:@sanity/base/schema)
 @ ./node_modules/@sanity/base/lib/util/getNewDocumentOptions.js
 @ ./node_modules/@sanity/base/lib/_exports/_internal.js
 @ ./node_modules/@sanity/base/_internal.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/index.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js

Error in ./schemas/blocks/body.tsx
Module not found: Error: Can't resolve 'osc-ui/dist/tokens/fluid-scale' in '/Users/stevebister/SITES/osc/packages/osc-studio/schemas/blocks'
 @ ./schemas/blocks/body.tsx 8:41-82
 @ ./schemas/schema.ts (part:@sanity/base/schema)
 @ ./node_modules/@sanity/base/lib/util/getNewDocumentOptions.js
 @ ./node_modules/@sanity/base/lib/_exports/_internal.js
 @ ./node_modules/@sanity/base/_internal.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/index.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js
```

```shell
npm run storybook

> osc@0.42.0 storybook

...

ModuleNotFoundError: Module not found: Error: Can't resolve 'osc-ui/dist/tokens/media-queries' in '/Users/stevebister/SITES/osc/packages/osc-ui/src/components/Carousel'
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/Compilation.js:2016:28
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:798:13
[1]     at eval (eval at create (/Users/stevebister/SITES/osc/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:270:22
[1]     at eval (eval at create (/Users/stevebister/SITES/osc/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:434:22
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:116:11
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:670:25
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:855:8
[1]     at /Users/stevebister/SITES/osc/node_modules/webpack/lib/NormalModuleFactory.js:975:5
```

2023-02-20 14:28 UTC, stevenbister commented on packages/osc-studio/package.json
> +    "osc-ui": "file:packages/osc-ui",
This seems to be causing an issue with running `npm run setup`

```shell
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/stevebister/SITES/osc/packages/osc-studio/packages/osc-ui/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/stevebister/SITES/osc/packages/osc-studio/packages/osc-ui/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
```

2023-02-20 15:34 UTC, aaacafe786 commented on packages/osc-studio/package.json
> +    "osc-ui": "file:packages/osc-ui",
resolved in v19

2023-02-20 15:36 UTC, stevenbister commented on packages/osc-studio/package.json
> +    "osc-ui": "file:packages/osc-ui",
Are you suggesting we upgrade to node v19?

2023-02-21 13:33 UTC, aaacafe786 commented on packages/osc-studio/package.json
> +    "osc-ui": "file:packages/osc-ui",
new changes allow this to work with Node v18.14.1

2023-02-21 14:25 UTC, stevenbister reviewed
Followed these steps but getting an error?

1. `npm run nuke`
2. `npm run setup`
3. `npm run dev:osc-ecommerce`


![image](https://user-images.githubusercontent.com/23461173/220370607-4bb1851a-202a-4227-9d1f-78a5e27f7aed.png)

I have all of the .env files

2023-02-21 14:25 UTC, stevenbister commented on packages/osc-ui/package.json
> -  "browserslist": [
Is there a reason you've removed this? Pretty sure it's important for autoprefixer?

2023-02-21 14:25 UTC, stevenbister commented on packages/osc-ui/package.json
> -    "@types/react": "^17.0.45",
I actually think that this and react should be dependencies (see [packages have strong boundaries](https://monorepo.guide/thinking-in-monorepos)) of this package? Is there a reason you've removed it completely?

2023-02-21 14:29 UTC, stevenbister commented
Oh also getting this when running studio

```
[WARN] The following package versions have not yet been marked as supported:
  react (installed: 18.2.0, want: ^16.9 || ^17)
  react-dom (installed: 18.2.0, want: ^16.9 || ^17)
You _may_ encounter bugs while using these versions.
  To downgrade, run either:
  yarn add "react@17.0.0" "react-dom@17.0.0"
  or
  npm install "react@17.0.0" "react-dom@17.0.0"
✔ Checking configuration files...
- Compiling...
webpack built 7388edcea2f9e7ea7c2f in 9240ms
Content Studio successfully compiled! Go to http://localhost:3333
```

It runs and _seems_ okay but I'm not sure if the react version will cause issues down the line?

2023-02-21 15:13 UTC, aaacafe786 commented on packages/osc-ui/package.json
> -    "@types/react": "^17.0.45",
added back in and updated to the latest version

2023-02-21 15:14 UTC, aaacafe786 commented on packages/osc-ui/package.json
> -  "browserslist": [
added back in, its because i was using an old version of node in the ci workflows and did not realise what was causing the error

2023-02-21 15:28 UTC, aaacafe786 commented
fixed the warning, by adding overrides to the studio package.json

2023-02-22 08:55 UTC, aaacafe786 commented
hey mate, with regards to the following warning: 
```
[WARN] The following package versions have not yet been marked as supported:
  react (installed: 18.2.0, want: ^16.9 || ^17)
  react-dom (installed: 18.2.0, want: ^16.9 || ^17)
You _may_ encounter bugs while using these versions.
  To downgrade, run either:
  yarn add "react@17.0.0" "react-dom@17.0.0"
  or
  npm install "react@17.0.0" "react-dom@17.0.0"
✔ Checking configuration files...
- Compiling...
webpack built 7388edcea2f9e7ea7c2f in 9240ms
Content Studio successfully compiled! Go to http://localhost:3333
```
i think what overrides does is that it forces all versions of react to become a certain version, thus leaving only 1 version of react in our app

2023-02-22 08:57 UTC, aaacafe786 commented
https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md is an instruction manual on how to use overrides

2023-02-22 09:14 UTC, closed without merging