Form Component Validation
Open-Study-College/osc pull request #746
Opened 2023-02-24 12:27 UTC by mattwendzina

Closes #745 

## 📝 Description

Add client and server validation to the form components. Each form component has been given the following new props:
- Errors: string[]
- SetErrors: Dispatch<SetStateAction<any>>  (Shouldn't be any, need to update this)
- Schema- ZodSchema

1) Errors  - Will be a list of errors set in state in a parent, most likely server errors. 
2) SetErrors - The corresponding dispatch for Errors which will allow for errors to be updated on the client
3) Schema- Used for validation - Will be using ZodSchema, but this could be replaced for a different schema if required. This will be the same schema used for both server and client validation to keeps things simple and consistent.

## ⛳️ Current behavior (updates)
The form inputs only had basic validation in order to work on the styling for error handling 

## 🚀 New behavior

See above

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information
There are a few additional things to note as I did some cleanup/refactoring as I went along:

- TextInput:
1. Id and name weren't set to required, but need to be as they won't function correctly without them.
2. Use of Icons (for errors and otherwise has been tidied up - was still using a radix icon)
3. Added <VisuallyHidden/> for Button Icon as this was an accessibility violation (there was no text)
4. Changed text colour on Quaternary style to `neutral-700` as it was a contrast violation

- TextArea:
1. Now imports the <InputError/> from TextInput to reduce code

- Switch:
1. I've added option for a validation error message - Looked at some examples and saw that there could be issues where for example a switch is used to set a preference on the server - If this fails the should be reset and helpful to give the user a message. Perhaps we don't forsee this usage, but as I was adding in all the error validation anyway I thought I'd just update it. Can remove though.
2. Added the option to add a name to the switch, as well as a required description along with <VisuallyHidden/> component as this was a accessibility violation.

2023-02-28 11:56 UTC, stevenbister requested changes
Looking good! Couple of questions/thoughts. I've added most comments to the checkbox but they apply to all of the components.

Also agree with the switch changes you've made, makes sense to reset it if it fails

2023-02-28 11:56 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                    errors
I think it might be worth tweaking this to `errors.length > 0` as if you get an empty array returned then this will still evaluate as true and you'll get some potentially unexpected results.

2023-02-28 11:56 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                {errors ? (
See previous comment about length

2023-02-28 11:56 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                        {errors}
If you have more than one item in the array they get placed together without any space e.g.
<img width="333" alt="image" src="https://user-images.githubusercontent.com/23461173/221846441-174f9ad5-356a-4434-b81c-62dc961ce5d5.png">
Might be worth mapping over the array and wrapping each one in a `span` or something with a bit of padding or something to give it some space.
I reckon `<span className="u-pr-2xs">` would work nicely

2023-02-28 11:56 UTC, stevenbister commented on packages/osc-ui/src/utils/clientSideValidation.ts
> +export const clientSideValidation = (
Think it's worth adding some tests for this? Or expanding the component tests to include multiple messages or to assert that the validation message clears when the input meets the criteria?

2023-02-28 11:56 UTC, stevenbister commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +        }, [checked]);
Think this is in all of them actually

2023-03-06 10:34 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +import type { ZodSchema } from 'zod';
Yeah, makes sense, thanks for the link. Updated with Zod in the `osc-ui` package. Guess it should be added to `osc-ecommerce` when it's being explicitly used there.

2023-03-06 11:39 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                    errors
Good point. I've added this into all the components. Also added a check on the if block to ensure there is also a schema and a dispatch before running the `clientSideValidation` function

2023-03-06 11:39 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                {errors ? (
See above

2023-03-06 12:19 UTC, mattwendzina commented on packages/osc-ui/src/components/Checkbox/Checkbox.tsx
> +                        {errors}
Yeah, this works well thanks. I've added an example onto the TextInput validation, but added it to all the components.
Also realised a refactor was needed on Switch component - all props were getting spread onto the DOM elements, so have updated so only the rest get passed in.

2023-03-07 10:21 UTC, mattwendzina commented on packages/osc-ui/src/utils/clientSideValidation.ts
> +export const clientSideValidation = (
Yep, good idea. I've added some more into the TextInput tests. 

I'm not sure whether to add these across the suite of form inputs or not... 

If something breaks in the function it should get picked up by the TextInput tests and it means potentially only needing to fix the tests in TextInput rather than having to go through all of them (assuming a fix is required in the actual tests). But then maybe it's worth just having them in all of them for some edge cases that I may not be thinking about?

What do you think?

2023-03-07 12:00 UTC, stevenbister requested changes
Sorry spotted a few other things, also the test for the datepicker is failing on my local run, not quite sure what's changed? Looks like it's a `div` that's holding that year now
```
❯ Object.getElementError ../../node_modules/@testing-library/dom/dist/config.js:40:19
 ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
 ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
 ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19
 ❯ src/components/DatePicker/DatePicker/DatePicker.spec.tsx:97:30
     95|     await user.click(decButton);
     96|
     97|     const yearButton = screen.getByRole('button', { name: '2023' });
       |                              ^
     98|     await user.click(yearButton);
     99|

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed | 37 passed (38)
     Tests  1 failed | 175 passed (176)
      Time  9.53s (in thread 12.54s, 75.99%)
```

2023-03-07 12:00 UTC, stevenbister commented on packages/osc-ui/src/components/Select/Select.spec.tsx
> +        <SpritesheetProvider>
If you import the render function from `test-utils` you can drop the spritesheet provider off these tests
https://github.com/Open-Study-College/osc/wiki/OSC-UI#testing 

Although you might need to rebase this branch first 😅

2023-03-07 12:00 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            {errors ? (
Do we need to check the length of the array here and loop the output on line 85?

2023-03-07 12:00 UTC, stevenbister commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +                aria-invalid={props.errors ? true : false}
Is there a reason for not using the destructured value here? Also; might need to check against the length of the array

2023-03-08 08:11 UTC, mattwendzina commented on packages/osc-ui/src/utils/clientSideValidation.ts
> +export const clientSideValidation = (
Yeah, I think it would be okay to just use the TextInput as representative of the others 👍

2023-03-08 08:40 UTC, mattwendzina commented
> Sorry spotted a few other things, also the test for the datepicker is failing on my local run, not quite sure what's changed? Looks like it's a `div` that's holding that year now
> 
> ```
> ❯ Object.getElementError ../../node_modules/@testing-library/dom/dist/config.js:40:19
>  ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:90:38
>  ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:62:17
>  ❯ ../../node_modules/@testing-library/dom/dist/query-helpers.js:111:19
>  ❯ src/components/DatePicker/DatePicker/DatePicker.spec.tsx:97:30
>      95|     await user.click(decButton);
>      96|
>      97|     const yearButton = screen.getByRole('button', { name: '2023' });
>        |                              ^
>      98|     await user.click(yearButton);
>      99|
> 
> ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
> 
> Test Files  1 failed | 37 passed (38)
>      Tests  1 failed | 175 passed (176)
>       Time  9.53s (in thread 12.54s, 75.99%)
> ```

Thanks mate, going through these now. DatePicker tests sorted (there was a failure on Range too). I had set `shouldCloseOnSelect` to `true` as needed this for the forms. It was hardcoded and meant to go back and make it a prop and forgot lol. Have done that now and updated the tests with this 👍

2023-03-08 08:41 UTC, stevenbister commented on packages/osc-ui/src/utils/clientSideValidation.ts
> +export const clientSideValidation = (
Sounds good to me

2023-03-08 12:08 UTC, mattwendzina commented on packages/osc-ui/src/components/Select/Select.spec.tsx
> +        <SpritesheetProvider>
All done. Updated this on the other form components too.

2023-03-08 12:09 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +            {errors ? (
Yeah, good shout. Done.

2023-03-08 12:09 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +                aria-invalid={props.errors ? true : false}
Yeah, think I just missed this. Destructured now 👍

2023-03-08 12:09 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DatePicker/DatePicker.tsx
> +                    aria-describedby={props.errors ? `${dateFieldId}-error` : undefined}
Sorted as above

2023-03-08 12:10 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +                    aria-invalid={errors ? true : false}
Yep, done

2023-03-08 12:10 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +                            aria-describedby={errors ? `${dateFieldId}-error` : undefined}
👍

2023-03-08 12:10 UTC, mattwendzina commented on packages/osc-ui/src/components/DatePicker/DateRangePicker/DateRangePicker.tsx
> +            {errors ? (
👍

2023-03-08 12:10 UTC, mattwendzina commented on packages/osc-ui/src/components/TextInput/TextInput.tsx
> +                    aria-describedby={errors ? `${id}-error` : undefined}
👍

2023-03-08 12:11 UTC, mattwendzina commented on packages/osc-ui/src/components/Switch/Switch.tsx
> +                <div
Ah, good spot. Yep, so added data-state to the parent. I'm just pointing to the value of the toggle here though - so just true/false - updated the scss to reflect this and all is working.

2023-03-22 11:45 UTC, closed without merging