Feature/algolia autocomplete v2
Open-Study-College/osc pull request #786
Opened 2023-03-10 11:55 UTC by aaacafe786

Closes # 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2023-03-15 15:20 UTC, stevenbister requested changes
Looks really good man, great work 😎 I've left you a few comments below. But also a couple of UX things to maybe consider

1. Do we want to be able to close the panel when you blur the text input? As someone who uses computers a lot I realised that pressing <kbd>esc</kbd> will close it but most users will probably not realise that.

https://user-images.githubusercontent.com/23461173/225355095-bbabf4aa-8721-4d64-9197-b143e11a4d09.mov

2. Similar to above would you expect clicking on the clear button to reset the results? At the moment it just clears the input but my search remains

https://user-images.githubusercontent.com/23461173/225356209-9bf631b8-d53f-424d-9b1f-9fb753bcd988.mov

Happy to discuss and hear your thoughts

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Highlight.tsx
> +    return createElement(
Can you explain the reason for using the `createElement` api rather than jsx? Seems a bit unusual

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +// TODO - Add No results back in
Still need this?

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +// TODO - Add Results Header back in
Still need this?

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +            <span className="aa-SourceHeaderTitle">{title}</span>
Again, do we need these `aa-` classnames?

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +                        <img src={item.image} alt={item.title} width="40" height="40" />
On these images, can you update the `alt` tag so it returns an empty string if the title doesn't exist? At the moment we're rendering them without an alt tag which is an accessibility issue.

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +                        alt={item.title}
See above comment on alt tag

2023-03-15 15:20 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/types/autoComplete.ts
> +// TODO - FIGURE OUT WHAT TO REPLACE THIS WITH
Still need this TODO?

2023-03-15 16:34 UTC, aaacafe786 commented on packages/osc-ui/package.json
> +    "@portabletext/types": "^2.0.0",
thanks, done

2023-03-15 16:35 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +        // eslint-disable-next-line
done

2023-03-15 16:41 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +    const sections = await screen.findAllByTestId('hits');
hey, it cant find one with listitem

2023-03-15 16:42 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +import type { AutocompleteItem, AutocompleteProps } from './types/autoComplete';
done

2023-03-15 16:42 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +// TODO - Refactor this out of the component and put credentials into env vars
done

2023-03-15 16:43 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +export function Autocomplete(props: AutocompleteProps) {
done

2023-03-15 16:43 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +        // eslint-disable-next-line
done

2023-03-15 16:44 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    const inputRef = React.useRef<HTMLInputElement>(null);
done

2023-03-15 16:44 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    const inputRef = React.useRef<HTMLInputElement>(null);
FYI few component that still have this

2023-03-15 16:45 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    // TODO - Work out exactly what this is doing..!
done, yes see the link in the description

2023-03-15 16:46 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        type="text"
done

2023-03-15 16:47 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        'aa-Panel',
hey, yeah, see: custom renderer stuff

2023-03-15 16:48 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +        &__input_clear_button {
done

2023-03-15 16:53 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +            right: 55px;
done

2023-03-15 16:54 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                font-size: calc($fs-s - 2px);
done

2023-03-15 16:57 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +// TODO - Add No results back in
done

2023-03-15 16:58 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +// TODO - Add Results Header back in
done

2023-03-15 16:58 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +            <span className="aa-SourceHeaderTitle">{title}</span>
yeah, built in algolia functionaility

2023-03-15 16:59 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +                        <img src={item.image} alt={item.title} width="40" height="40" />
done

2023-03-15 16:59 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +                        alt={item.title}
done

2023-03-15 17:00 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/types/autoComplete.ts
> +// TODO - FIGURE OUT WHAT TO REPLACE THIS WITH
done

2023-03-16 09:06 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Highlight.tsx
> +    return createElement(
Also I came across this: https://www.algolia.com/doc/guides/building-search-ui/getting-started/react-hooks/#highlight-matches Is there a reason we're not using the Highlight from there?

2023-03-16 09:43 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +    const sections = await screen.findAllByTestId('hits');
Ahh okay looks like Algolia is redefining the `role` attribute
<img width="633" alt="image" src="https://user-images.githubusercontent.com/23461173/225577741-b714165d-6f76-401e-bac7-264f76dfb663.png">

So use `screen.findAllByRole('option')` instead

2023-03-16 10:32 UTC, mattwendzina commented
Hi mate,

Looking great. A couple of initial comments. 

First, in relation to @stevenbister comment about closing of the panel - this was working before - ie - when you clicked outside of the panel it would close the search results. Though I've just tested and this doesn't appear to be working. Do you know what has changed/may be causing this? I have a feeling that when this is working again it will resolve @stevenbister other point about the results actually closing when you hit the 'X' close button.

We're still missing the styling for when you go through the search results with the down arrow - ie there is nothing to visually show the user what result they are on (apart from the search title changes).

In terms of the debouncing behaviour - is this what @hi-im-si has intentionally asked for? I personally think it's nice to get the results live with each keystroke. It feels like this is one of the big features that Algolia offers. I can see in their docs that there are a couple of reasons they suggest that you may not want this - 1) rate limits- I don't think this will be an issue as we have a decent paid for account? 2) accessibility - can see that for a certain disorder it can cause problems - but they seem to suggest this could be something that users could adjust when signed in through preferences. I think particularly for academic hub- on each stroke would be helpful for users. Also it looks like this is pretty commonly used behaviour- tailwind, remix, shopify all taking advantage of this feature.

2023-03-16 10:41 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    const {
done

2023-03-16 10:42 UTC, mattwendzina commented
Okay, so the panel wasn't closing because the panelRef needs to be added to the panel div. ie:
lines 154-163
```
 <div
                    className={[
                     ...
                    ref={panelRef}
                    {...autocomplete.getPanelProps({})}
                >
  ```

2023-03-16 10:46 UTC, mattwendzina commented
You can do something like the following to close the panel when the X button is clicked: 
```
 <button
                            onClick={() => {
                                setQuery('');
                                setAutocompleteUiState((prevState) => ({
                                    ...prevState,
                                    isOpen: false,
                                }));
                            }}
                            className="aa-ClearButton c-autocomplete__input_clear_button"
                        >
                        ```
This would keep the state in tact and just update `isOpen` to false which will close the panel

2023-03-16 10:49 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        type="text"
@mattwendzina

2023-03-16 10:50 UTC, mattwendzina commented
In terms of the styling when you use the up/down buttons to go through the results. You can add the following inside of `&__item` and then style appropriately.
```
&__item {
...
&[aria-selected="true"] {
                // Add styles
 }
}
```

2023-03-16 14:40 UTC, aaacafe786 commented
Hey, so with regards to the first video, i have changed the input to "search type" which provides a default cancel button that seems to have the correct functionality

2023-03-16 14:41 UTC, aaacafe786 commented
with regards to the second video, i have added a panelRef to the aa-panel element, this should fix the error

2023-03-16 15:39 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +    const sections = await screen.findAllByTestId('hits');
cannot differentiate between popular courses, recent searches and actual results with this

2023-03-17 08:46 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                return `/courses/${item.handle}`;
Should the url be hardcoded to begin with courses? Is that the only place they'll ever be routed to?

2023-03-17 08:55 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    const { getEnvironmentProps, setQuery } = autocomplete;
Doesn't look like `setQuery` is being used.

2023-03-17 09:04 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        'aa-Panel',
We aren't using any aa classnames and so I think you're going to need to create this `stalled` class otherwise not sure how it's going to work? 
Would also be worth testing if this then works? 
You could maybe put a useeffect in just to test it, something that just changes the status to stalled, e.g. 
```
 useEffect(() => {
        setAutocompleteUiState((prevState) => ({ ...prevState, status: 'stalled' }));
    }, [autocompleteUiState.activeItemId]);
    ```

2023-03-17 09:08 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                color: rgb(var(--aa-text-color-rgb) var(--aa-text-color-alpha));
Not sure why colour is being set twice here and neither our using our tokens. Also, is `description` actually being used, I couldn't see the classname anywhere?

2023-03-17 09:11 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                                            key={item.objectID + '_' + index}
Prob personal preference so up to you, but I tend to thing string interpolation looks neater than concatenation, e.g. 
`${item.objectID}_${index}`

2023-03-17 09:25 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        type="search"
Looks like the old 'x' button is back again. Were there some additional classes you needed to add?
Also, can't see the other close button either now = (

2023-03-17 10:57 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        'aa-Panel',
> see: custom renderer stuff

What's this? Have you got a link or something you can share?

2023-03-17 12:26 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                return `/courses/${item.handle}`;
we are going to update this in a future pr, fom my understanding this will be linked to the product page

2023-03-17 12:28 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    useEffect(() => {
done

2023-03-17 12:30 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        // Overriding to type "text" from type "search" as we don't want the styled cancel button
still there, just not visible, we want type search for additional features

2023-03-17 12:35 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                        type="search"
will address this in the latest commit

2023-03-17 12:48 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                color: rgb(var(--aa-text-color-rgb) var(--aa-text-color-alpha));
removed, done

2023-03-17 12:51 UTC, aaacafe786 commented
> onClick={() => {
>                                 setQuery('');
>                                 setAutocompleteUiState((prevState) => ({
>                                     ...prevState,
>                                     isOpen: true, , <--- note*
>                                 }));
>                             }}

this is implemented, think si wants it like google

2023-03-17 12:52 UTC, aaacafe786 commented
> In terms of the styling when you use the up/down buttons to go through the results. You can add the following inside of `&__item` and then style appropriately.
> 
> ```
> &__item {
> ...
> &[aria-selected="true"] {
>                 // Add styles
>  }
> }
> ```

done

2023-03-17 12:54 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/components/Templates.tsx
> +            <span className="aa-SourceHeaderTitle">{title}</span>
no, we did not

2023-03-17 15:40 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    useEffect(() => {
except one @mattwendzina

2023-03-20 08:33 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    const inputRef = React.useRef<HTMLInputElement>(null);
Thanks, yeah that's fine they were probably missed in other PRs. I just want to try and avoid introducing any more if possible

2023-03-20 09:37 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    useEffect(() => {
Not sure what you mean by this @aaacafe786 ?

2023-03-20 09:47 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +test('limits the amount of results to three', async () => {
Just thought, on this one it would be better to change the `resultsLimit` to something other than three. You've set three as the default in the component so if passing the prop fails the test will still pass, perhaps two or four would be better to test?

2023-03-20 09:47 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +            height: 0;
Does `appearance: none;` not work here?

2023-03-20 09:47 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/components/Highlight.tsx
> +    return createElement(
Ahh okay, still not really sure why the hooks from the package won't work but 🤷‍♂️ 

The `tagName` is something you've declared though so you can change it? Doesn't look like it's being changed from the default `mark` so can you not just do something like this?
```tsx
if (isHighlighted) {
    return <mark key={index}>{value}</mark>
}
```
Or if you want to use the `tagName` just capitalise it and change your type to be a `ReactNode` rather than a `string`

2023-03-20 09:48 UTC, stevenbister requested changes
Sorry man, noticed a couple of other things

2023-03-20 10:09 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
@aaacafe786  - think you should be able to achieve this pretty easily by just calling focus on the inputRef when you the search close button is called, e.g:
```
onClick={() => {
      const resultsIndex = autocompleteUiState.collections.findIndex(
          (q) => q.source.sourceId === 'Results'
      );
     ...
     inputRef.current.focus();
}
```

2023-03-20 10:11 UTC, mattwendzina commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +    useEffect(() => {
Ah, can see that this is done 👍

2023-03-21 09:49 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                setQuery('');
when you click the clear button, the input should clear, this function is destructured from the autocomplete instance

2023-03-21 09:49 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                    ></TextInput>
done

2023-03-21 09:51 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                setQuery('');
Cool, are you okay to pop that in as a comment?

2023-03-21 09:56 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +                                setQuery('');
done

2023-03-21 10:52 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
hey, there was a weird effect as the input defocused then focused again, i used this instead: 
```
onMouseDown={(e) => {
    e.preventDefault();
}}
```

2023-03-21 10:52 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
done

2023-03-21 10:52 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +        input[type="search" i]::-webkit-search-decoration,
done

2023-03-21 10:54 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.spec.tsx
> +test('limits the amount of results to three', async () => {
done

2023-03-21 10:55 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +            height: 0;
done

2023-03-21 11:03 UTC, aaacafe786 commented
i have refactored the highlight component to use functional components

2023-03-21 11:15 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
@aaacafe786 Can you add a comment with that for future reference as to why we need it?

2023-03-21 11:24 UTC, stevenbister commented
> Hi mate, looks like it's nearly there. Found another weird bug thing though 🙈 Looks like you can't click the search icon when you start searching for results which kind of renders it redundant as you can only click it when the input is empty. I think this behaviour was working at some point so not sure what's changed that means it no longer does?

Related to that, if you click on the search icon you can no longer click into to the textarea :/

https://user-images.githubusercontent.com/23461173/226592012-f9a2a327-a2af-43c4-87c8-f5b55b080091.mov

2023-03-21 11:35 UTC, stevenbister requested changes

2023-03-21 11:35 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                width: 12px; /* width of the entire scrollbar */
Can we make this smaller? Perhaps 6px instead? Feels a bit too bulky currently

2023-03-21 11:35 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                width: 10px;
Same as before, perhaps 5px would be better? And can you add both to the top of the file as variables?

2023-03-21 11:35 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                border-radius: 40px; /* roundness of the scroll thumb */
Can you use one of the `$rad-` variables here? Perhaps `$rad-xs`?

2023-03-21 11:35 UTC, stevenbister commented on packages/osc-ui/src/icons/close.svg
> +        stroke="white"
Not sure if this is the best approach here 🤔 This will only really work on a white background, for instance this icon is used in the nav and because that has a grey background you can see the white border around it. :/

<img width="82" alt="image" src="https://user-images.githubusercontent.com/23461173/226594212-437f5bf7-6262-4c49-8d1f-1f5c3dd234df.png">

Dunno if I'm being pedantic.. @hi-im-si What do you think? Is it worth seeing if we can get another icon from Amy? I'd edit it in Figma myself but I don't have edit access

2023-03-21 11:40 UTC, hi-im-si commented on packages/osc-ui/src/icons/close.svg
> +        stroke="white"
I think my preference would be to replace the icon with something that matches the thickness of the other icons. see the chevrons as an example

2023-03-21 11:43 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                width: 12px; /* width of the entire scrollbar */
done

2023-03-21 11:45 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.stories.tsx
> +        openOnFocus: { description: 'Whether to open the panel on focus when there’s no query.' },
sound, i think all of these will be used tbf

2023-03-21 11:46 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.stories.tsx
> +        openOnFocus: { description: 'Whether to open the panel on focus when there’s no query.' },
I couldn't find them in the codebase? Do they come from somewhere?

2023-03-21 11:48 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                width: 10px;
done

2023-03-21 11:48 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/autocomplete.scss
> +                border-radius: 40px; /* roundness of the scroll thumb */
done

2023-03-21 11:50 UTC, aaacafe786 commented on packages/osc-ui/src/icons/close.svg
> +        stroke="white"
done

2023-03-21 11:52 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.stories.tsx
> +        openOnFocus: { description: 'Whether to open the panel on focus when there’s no query.' },
ill add a comment to where they are used in autocomplete.tsx: https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-core/createAutocomplete/

2023-03-21 11:53 UTC, aaacafe786 commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.stories.tsx
> +        openOnFocus: { description: 'Whether to open the panel on focus when there’s no query.' },
we pass them as ...props to the createAutocomplete function

2023-03-21 13:19 UTC, aaacafe786 commented
> > Hi mate, looks like it's nearly there. Found another weird bug thing though 🙈 Looks like you can't click the search icon when you start searching for results which kind of renders it redundant as you can only click it when the input is empty. I think this behaviour was working at some point so not sure what's changed that means it no longer does?
> 
> Related to that, if you click on the search icon you can no longer click into to the input :/

hey, i added in navigation and sorted out some stuff with overlays, please let me know if you are getting further problems

2023-03-21 14:46 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.stories.tsx
> +        openOnFocus: { description: 'Whether to open the panel on focus when there’s no query.' },
Cool

2023-03-21 14:59 UTC, stevenbister requested changes
Looking really good mate :) Last couple of comments and I think we're there 🎉 

Still looking a little off on Safari on my iPhone (iPhone SE | iOS 16.2)
<img src="https://user-images.githubusercontent.com/23461173/226646975-94d4a04f-c4d0-4b38-b63a-16f78e454880.jpeg" width="400" />

2023-03-21 14:59 UTC, stevenbister commented on packages/osc-ui/src/components/Autocomplete/Autocomplete.tsx
> +import { useNavigate } from 'react-router-dom';
Can we change the import to the remix version? 
```suggestion
import { useNavigate } from '@remix-run/react';
```

`react-router-dom` is installed but only as a dev dependency for using the `MemoryRouter` in tests.

2023-03-22 09:51 UTC, stevenbister commented
@aaacafe786 Sorry mate couple of other things that caught my eye 😅 

I think the "recently viewed" & "popular searches" headings etc. need to be bold. e.g.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/23461173/226865176-02713605-a21e-4681-a60b-a25a7262530a.png">

And from a UX perspective, when you search, can you move the search results above the Popular searches? I think it makes for a better UX to have the users search front and centre. Similar to Coursera:

https://user-images.githubusercontent.com/23461173/226865943-8c17808e-e6e6-41c1-80bc-4fce6ab83748.mov




That's it, I'll leave it alone now :P

2023-03-24 07:39 UTC, aaacafe786 commented
> @aaacafe786 Sorry mate couple of other things that caught my eye 😅
> 
> I think the "recently viewed" & "popular searches" headings etc. need to be bold. e.g. <img alt="image" width="478" src="https://user-images.githubusercontent.com/23461173/226865176-02713605-a21e-4681-a60b-a25a7262530a.png">
> 
> And from a UX perspective, when you search, can you move the search results above the Popular searches? I think it makes for a better UX to have the users search front and centre. Similar to Coursera:
> 
> That's it, I'll leave it alone now :P

done

2023-03-24 07:46 UTC, aaacafe786 commented on packages/osc-ui/src/components/TextInput/TextInput.spec.tsx
> +test('should render multiple errors if present, and clear them once valid inputs are correctly validated', async () => {
@mattwendzina should this be in this pr?, sorry it happened after i rebased

2023-03-24 16:20 UTC, aaacafe786 commented
> I think a rebase has gone a little wonky somewhere in here? Your `TextInput.spec.tsx` has ended up with some duplicate tests?
> 
> Realised the design changes discussed are in the other branch so other than that test comment I think it looks good 👍

done

2023-03-24 16:44 UTC, stevenbister approved these changes
LGTM

2023-03-27 09:21 UTC, mattwendzina approved these changes
LGTM

2023-03-27 09:21 UTC, mattwendzina commented
Had one more look in Storybook and the styling looks right now 🙌

2023-03-27 11:04 UTC, merged