Feature/contact form in ecommerce hubspot integration
Open-Study-College/osc pull request #799
Opened 2023-03-21 13:20 UTC by mattwendzina

Closes https://github.com/Open-Study-College/osc/issues/724
Closes https://github.com/Open-Study-College/osc/issues/728
Closes https://github.com/Open-Study-College/osc/issues/729

## 📝 Description

This builds upon the `feature/form-component-validation-updates` & `contact-form-in-ecommerce` branches by adding the ability to dynamically import the form inputs directly from hubspot.  

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

- Adds form component validation for server and client side using Zod
- Adds Hubspot integration:
1) Enables forms to be created and will pull in the form input and data
2) Allows these forms to be submitted back to Hubspot
- Adds Sanity integration:
1) Enables Marketing to select a form Hubspot
2) Adds settings to enable the form to be a slide-out form if required

## 💣 Is this a breaking change (Yes/No):
No

## 📝 Additional Information

- Currently the formIds are being hardcoded. Eventually want these to be pulled in dynamically using the Hubspot Forms API. This will likely need a proxy and will be re-visited further down the line.

2023-03-21 14:36 UTC, stevenbister requested changes
Looking good man! Left a few comments and thoughts. I'm also getting an error when running locally
![image](https://user-images.githubusercontent.com/23461173/226639272-b67f7079-9806-4f19-b108-b0cbf8d0aa34.png)

Think we might have to add any environment variables into GitHub/the workflows as well. Happy to have that in here or as a separate PR, whichever you think is easiest

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Forms/FormContainer.tsx
> +                <Button variant="quaternary" className="c-form__container--slide-out-btn">
I think rather than a modifier this would be an element, for example `c-form__slide-out-btn`

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Forms/HubspotForm/HubspotForm.spec.tsx
> +                titleAndDescription={textContent.titleAndDescription}
Looks like a few of these props aren't being used anymore?

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Forms/HubspotForm/textContent.ts
If we update the test file to remove those props will we still need this file?

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Forms/types.ts
Assuming that these types are pulled from the Hubspot docs? But have a few questions/suggestions
- Worth changing the comments to JSDoc?
- Do we need to include the deprecated ones? If so I think you can mark them as deprecated with JSDoc `@deprecated`
- Worth making the readonly ones readonly with ts? https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype

Appreciate we might not be directly hitting these so happy to leave it as is if it's a lot of effort

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/components/Forms/utils.tsx
> +                        // variants={data.variants}
Should this be commented out?

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +export const action: ActionFunction = async ({ request }: ActionArgs) => {
Rather than having this in here it might be worth moving it into it's own route (`actions/hubspot` or something) and updating the `RemixForm` action to post to that path.

Doing it in the the route means we'll have to duplicate this in each of the other route files (collections, products, posts etc.)

What do you think?

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/hubspot.helpers.ts
> +    debugger;
Can we take this out?

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/hubspot.helpers.ts
> +            `https://api.hsforms.com/submissions/v3/integration/secure/submit/${process.env.CONTACT_PORTAL_ID}/${formId}`,
Might be worth adding this env to the README if you've not already

2023-03-21 14:36 UTC, stevenbister commented on packages/osc-ecommerce/app/utils/server/hubspot.server.ts
> +        accessToken: process.env.HUBSPOT_DEV_ACCESS_TOKEN,
Might be worth adding this env to the README if you've not already

2023-03-21 16:04 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/HubspotForm/HubspotForm.spec.tsx
> +                titleAndDescription={textContent.titleAndDescription}
Removed.

2023-03-21 16:05 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/HubspotForm/textContent.ts
Yeah good point, there was still some data being used, but moved it all into the mockData and organised it a bit better so it's clear what mockData is Hubspot and which is Sanity.

2023-03-21 16:30 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/types.ts
I think all the above is good. Done.

2023-03-21 16:33 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/utils.tsx
> +    // TODO - Need to work out the correct type for this!
Updated

2023-03-21 16:33 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/utils.tsx
> +                        // variants={data.variants}
I think this was used on some of the other forms, but can't remember now lol. I've removed and will just add back in if needed.

2023-03-22 09:03 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +export const action: ActionFunction = async ({ request }: ActionArgs) => {
Yep, thanks mate, this was part of the flow I hadn't fully figured out. Makes sense. Implemented. Took a while though as I hadn't used useFetcher so initially it was reloading the page with Remix Form, and then it took some more time to work out that the data gets returned via useFetcher rather than useLoaderData 😅 
Got there eventually though 😄

2023-03-22 09:06 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/hubspot.helpers.ts
> +    debugger;
Ooops lol. Done.

2023-03-22 09:07 UTC, mattwendzina commented on packages/osc-ecommerce/app/utils/server/hubspot.server.ts
> +        accessToken: process.env.HUBSPOT_DEV_ACCESS_TOKEN,
Added.

2023-03-22 10:09 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +export const action: ActionFunction = async ({ request }: ActionArgs) => {
Nooiiice

2023-03-22 10:37 UTC, stevenbister requested changes
Good stuff man, last couple of bits and I think we're there!

Something we'll need to think about doing is adding in success messages once the form submits "Thank you, we'll be in touch soon" kind of stuff, and how we handle that. Probs a separate task, I'll pop a note into Whimsical and perhaps we can discuss in the next sprint planning session?

2023-03-22 10:37 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +    }
This whole block will need adding to all of the routes as we'll want the option to use a form on any of them

2023-03-22 13:06 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/utils.tsx
> +        fetcher.submission.formData.get('_action') === 'submitForm';
Nice spot! Done.

2023-03-22 13:06 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/Forms/HubspotForm/HubspotForm.tsx
> +                <Button
Good idea. Done.

2023-03-22 14:38 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +    }
I've refactored into one helper function and added to all same routes where modules are imported.

2023-03-22 15:14 UTC, stevenbister approved these changes
Nice man! LGTM 🚀

2023-03-22 17:52 UTC, mattwendzina commented
@stevenbister - I've had to make some additional changes..! After finishing I went and added a second form to start working on the newsletter to discover that it just displayed the contact form twice 😬 
Realised I was using a `.find()` on module.forms and so it only returned first one. I've changed this to a filter and then had to introduce some additional shaping and logic to ensure that the right form module gets the correct hubspot data.

2023-03-22 17:54 UTC, mattwendzina commented
Also needed to tweak the ids for the form components to make sure they are unique for the case of multiple forms where there could be overlap.

2023-03-23 08:38 UTC, stevenbister commented
> @stevenbister - I've had to make some additional changes..! After finishing I went and added a second form to start working on the newsletter to discover that it just displayed the contact form twice 😬 Realised I was using a `.find()` on module.forms and so it only returned first one. I've changed this to a filter and then had to introduce some additional shaping and logic to ensure that the right form module gets the correct hubspot data.

Ahaa oops! Tbf I didn't test putting multiple forms on a page 😅 I'll give it another once over now

2023-03-23 08:43 UTC, stevenbister requested changes
Just that eslint warning but otherwise the new changes look good to me

2023-03-23 08:43 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +import type { HubspotFormData } from '~/components/Forms/types';
Eslint warning here `'HubspotFormData' is defined but never used`

2023-03-23 08:52 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/$slug.tsx
> +import type { HubspotFormData } from '~/components/Forms/types';
Removed 👍

2023-03-23 16:16 UTC, merged