Feature/user signup
Open-Study-College/osc pull request #942
Opened 2023-06-02 16:50 UTC by hall2521

Closes #878 #875 #890 #879  

## 📝 Description

- Added create non-student customer sign up functionality
- Added magic key token generation
- Added HubSpot email function that can be reused
- Modified schema to allow for interested courses
- Modified User roles / permissions
	- Added some user roles and permissions
	- Reworked the permissions check to work per request as opposed to per token

## ⛳️ Current behavior (updates)

Permissions now work on a per request basis whereas before they worked on per token

## 🚀 New behavior

I've added the functionality for a non-student customer to sign up without choosing a password.
User will be sent an email with a magic key token link. This can be verified and basic user data sent back - name etc
User will then be prompted to choose a password for their account and this can then be added.
I've also reworked the permissions structure within the API to validate permissions per request as opposed to per token (which lasted a day). This will allow for immediate changes to permissions/roles

## 💣 Is this a breaking change (Yes/No): No

## 📝 Additional Information

2023-06-06 12:16 UTC, Tom-Pearce requested changes

2023-06-07 08:47 UTC, hall2521 commented on packages/osc-api/user/index.ts
> +    // To Do - Format cod eto allow email function to be reusable
yup this makes sense. I've added this in

2023-06-07 10:00 UTC, Tom-Pearce requested changes

2023-06-08 07:57 UTC, Tom-Pearce requested changes

2023-06-08 07:57 UTC, Tom-Pearce commented on packages/osc-api/emails/index.ts
> +        return 'Email request sent to HubSpot';
Can we change this to `return true` or `return id` - I want to avoid string returns for "success/failure" responses for internal functions, as they're just going to get messy down the line.

Throwing errors is fine as that will feedback through apollo to the requester as an error message, but on a successful running of. a function just return true/false dependant upon the success of the run.

2023-06-08 12:26 UTC, Tom-Pearce approved these changes

2023-06-12 11:21 UTC, merged