Feature/algolia instantsearch
Open-Study-College/osc pull request #943
Opened 2023-06-05 09:32 UTC by mattwendzina

Closes #198 
Closes #899 
Closes #900 
Closes #932 

## 📝 Description

This integrates Algolia InstantSearch into the /search route. It has two ways of refining search results. One, the SearchBox component which refines the search results on each keystroke, and two, the Refinement Lists which enable results to be refined based on categories. 'Filter By Result Type' and 'Filter By Monthly Payments' have not yet been implemented. They require Federated search results and Etika information respectively and will be added in due course. 

The Collection Card highlights are currently hardcoded to ALevels and GCSEs, but we will update this once Algolia Insights is fully integrated.

The SortBy options are created through replica indices with the relevant SortBy configuration. There are currently four of these and they are hardcoded into the `data.ts` folder. We can easily add more if required. 

## ⛳️ Current behavior (updates)

N/A

## 🚀 New behavior

Integrates Algolia InstantSearch for searching products. Searching for Blogs and Information Pages will follow. 

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

The following env_vars are required:
ALGOLIA_APP_ID
ALGOLIA_API_KEY_SEARCH
ALGOLIA_PRIMARY_PRODUCTS_INDEX
ALGOLIA_PRIMARY_COLLECTIONS_INDEX
ALGOLIA_PRODUCTS_INDEX_GROUPED_BY_ID
ALGOLIA_HITS_PER_PAGE

Note that the names of some of these have changed slightly to be clearer. I can send these across as and when required.

2023-06-05 14:54 UTC, stevenbister requested changes
Hey man, this is looking really good! A few comments for you, hopefully nothing too major. 

> I do wonder whether we want any text above the search box when nothing is typed

I agree, perhaps just have it set to something like "Showing X results" where X is just the unfiltered total?

> So I've just stuck to using the Icon variant which admittedly does like slightly different from design and can refactor/tweak this if we want.

Could we tweak it so the icon sits outside of the input on that variant?

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                <Price>
The prices feel a bit big, if you add `size="sm"` to these components then it'll shrink them down a bit

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                            {uniqueProductVariants?.map((variant: string) => {
I'm not sure if something else is going on but it doesn't look like this is quite working right? Not all of the products are showing the course options:

![image](https://github.com/Open-Study-College/osc/assets/23461173/4f8cb227-97c5-4b61-9986-936dc2fcbbd8)

AAT level 3 diploma in accounting should have a couple, I think

![image](https://github.com/Open-Study-College/osc/assets/23461173/cb8dac33-64a7-40de-968b-597abffe9fca)

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                to="/courses/aat-level-3-diploma-in-accounting"
Can this value be dynamic?

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/data.ts
Do we update any of these at any point? Wondering if it's worth casting each one as a const to tell ts that they're readonly values
eg
```ts
export const SORTING_INDEXES = [
    {
        value: 'shopify_products_grouped_by_id_price_desc',
        label: 'Price - High to Low',
    },
] as const;
```

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +            font-size: 26px;
Is there a reason this isn't `$fs-l`? If so then font sizes should always be rem, there's a `rem()` function you can use like this which will save you doing the maths
```scss
font-size: rem(26);
```

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ecommerce/app/routes/search/index.tsx
Do you expect this route to have children at all (/search/foo)? If not could we move it out of the search directory and just have it as `routes/search.tsx`? I appreciate you didn't set this up but I think this might be a good opportunity to improve the consistency here?

2023-06-05 14:54 UTC, stevenbister commented on packages/osc-ui/src/components/Slider/Slider.tsx
> +                    setExternalValue(event);
Think you need some kind of check here to make this exists, currently errors if you try and use the component without it

https://github.com/Open-Study-College/osc/assets/23461173/60b9f869-427d-498a-8aea-34ed96bc6166

2023-06-05 15:03 UTC, stevenbister commented
I think the `SortBy` should have a default value. I think a lot of other ecommerce stores tend to use 'relevance' not sure if we have something like that? If not maybe A-Z?

2023-06-06 17:28 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +    const { hits, sendEvent } = useHits();
These are all there as they will be implemented as part of the sending events to Algolia work, which I think is next sprint.

2023-06-07 07:10 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +    const { className, hit, sendEvent, view } = props;
Yep 👍

2023-06-07 07:12 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                <Price>
Done

2023-06-07 07:17 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                            {uniqueProductVariants?.map((variant: string) => {
Yeah. It's where we had to add the Meta fields into Shopify. Didn't fancy doing this for every product, hoping maybe marketing can do this..? 😅 Or if not, can create a ticket to get this done further down the line.

2023-06-07 07:25 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                to="/courses/aat-level-3-diploma-in-accounting"
Ah yeah, good point! 😅 Done

2023-06-07 07:32 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
> +            font-size: 26px;
No that was my bad, should have used the sass variable, but that's handy to know about the rem function 😄

2023-06-07 07:38 UTC, mattwendzina commented on packages/osc-ecommerce/app/routes/search/index.tsx
Yeah, good shout. 👍

2023-06-07 07:39 UTC, mattwendzina commented on packages/osc-ui/src/components/Slider/Slider.tsx
> +                    setExternalValue(event);
Ah, nice spot. I swear I did put a check in there lol, but obviously removed it 😅 It's back in there now..!

2023-06-07 07:54 UTC, mattwendzina commented
> 

Ah yeah, more good spots..! Sorted the naming, and the padding/borders sorted themselves when I removed an extraneous <div>!

2023-06-07 09:20 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/data.ts
Might have to leave that out for now, unless you know a way around the following. I get the following error on the SortBy component:

```
...
<SortBy items={SORTING_INDEXES} />
...
```

Red line on `items` with the error:
`is readonly and cannot be assigned to the mutable type `items: {value: string; label: string}[]`

I've tried setting to readonly inside of `SortBy` component but this doesn't fix it. Tried a couple of other options from forums, but nothing worked, and nothing specific to the example of getting this error when passing the read_only property in as a prop 🤷

2023-06-08 07:50 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/data.ts
Ahh fair enough, lets leave it

2023-06-08 09:43 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +const Card = (props: CardProps) => {
Yep! Done 👍

2023-06-08 09:44 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +export const CollectionCards = (props: CollectionCardsProps) => {
It now has a prop = )

2023-06-08 09:44 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +                    handle={collection.handle as string}
Done

2023-06-08 09:44 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +                    title={collection.title as string}
Done

2023-06-08 09:45 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
> +                to="/courses/aat-level-3-diploma-in-accounting"
Now actually done/pushed up lol!

2023-06-08 09:48 UTC, mattwendzina commented
Everything has been addressed now (I think..!)

Only thing to say - `CollectionCard.tsx` is looking a bit more messy. Because we're pulling in Sanity data client side in `CollectionCards.tsx` we need to be able to account for fact that we might not get data due to network request failure or something else so it's possible that `data` will be `undefined`.

2023-06-08 11:04 UTC, stevenbister requested changes
Cool man, nearly there I think! Were we going to add a default to the sort by? I know you spoke to Si about that but not sure what the outcome was?

2023-06-08 11:04 UTC, stevenbister commented on packages/osc-ecommerce/app/components/InstantSearch/Components/ItemCounter.tsx
> +                <strong key={`${results?.nbHits}`}>Showing {results?.nbHits} Results for</strong>
Rather than showing "for" constantly could we change it so that if the user hasn't searched then is says 

"Showing 664 results"

and then when they've searched it could be 

"Showing 34 results for"

Maybe?

2023-06-08 11:04 UTC, stevenbister commented on packages/osc-ecommerce/app/queries/sanity/collection.ts
> +    *[ _type == "collection" && store.slug.current == $highlightCategoryOne || store.slug.current == $highlightCategoryTwo] {"alt": image.alt, "image":image.image, "slug": store.slug.current}
Is there a reason you're only querying the image here? You could instead add 
```
"featuredImage": {
            ${MODULE_IMAGES}
        },
```
To this query which includes all of the image properties as well as the styles (overlay colours etc.)

2023-06-08 11:40 UTC, mattwendzina commented on packages/osc-ecommerce/app/queries/sanity/collection.ts
> +    *[ _type == "collection" && store.slug.current == $highlightCategoryOne || store.slug.current == $highlightCategoryTwo] {"alt": image.alt, "image":image.image, "slug": store.slug.current}
Because I'm a querying rookie 😂 

Updated 👌

2023-06-08 11:40 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
> +                                                querySanityDataset[index].image.imageStyles,
Sorted

2023-06-08 11:43 UTC, mattwendzina commented on packages/osc-ecommerce/app/components/InstantSearch/Components/ItemCounter.tsx
> +                <strong key={`${results?.nbHits}`}>Showing {results?.nbHits} Results for</strong>
Good shout!  Done.

2023-06-08 11:45 UTC, mattwendzina commented
> Cool man, nearly there I think! Were we going to add a default to the sort by? I know you spoke to Si about that but not sure what the outcome was?

Thanks mate = ) Chasing Si on the sortby stuff!

2023-06-08 13:16 UTC, stevenbister approved these changes
🚢  it!

2023-06-12 13:24 UTC, merged